Repository openshift/cluster-monitoring-operator, pull requests merged in 2018-11, with the labels that each got.

#141 README: distinguish app vs cluster monitoring
  README.md
Labels: approved, lgtm, size/S

#138 *: Enable multi-namespace monitoring
  assets/prometheus-k8s/prometheus.yaml
  cmd/operator/main.go
  jsonnet/prometheus.jsonnet
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/prometheusoperator.go
Labels: approved, lgtm, size/M

#143 Update kube-prometheus and Prometheus to v2.5.0
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#145 Telemeter Client Serving Certs CA
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  assets/telemeter-client/deployment.yaml
  assets/telemeter-client/secret.yaml
  assets/telemeter-client/serving-certs-c-a-bundle.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/tasks/telemeter.go
Labels: approved, lgtm, size/L

#146 assets,jsonnet,pkg: regenerate assets
  assets/prometheus-k8s/rules.yaml
  assets/telemeter-client/deployment.yaml
  assets/telemeter-client/serving-certs-c-a-bundle.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#154 Use RBAC roles for resource metrics API for pod metrics in console
  assets/prometheus-k8s/kube-rbac-proxy-secret.yaml
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#157 pkg/tasks/telemeter: enable only cluster ID and token is given
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/tasks/telemeter.go
Labels: approved, lgtm, size/L

#155 Add config sharing scheme to share URLs with console
  pkg/client/client.go
  pkg/manifests/manifests.go
  pkg/operator/operator.go
  pkg/tasks/configsharing.go
Labels: approved, lgtm, size/M

#151 pkg/manifests: etcd defaults to disabled
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests_test.go
Labels: approved, lgtm, size/S

#159 assets: bump telemeter, node-exporter
  assets/grafana/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  assets/telemeter-client/service-monitor.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L

#161 assets,jsonnet: fix grafana port
  assets/grafana/deployment.yaml
  jsonnet/grafana.jsonnet
Labels: approved, lgtm, size/XS

#162 manifests/bindata.go: regenerate
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#163 assets,jsonnet: add host to grafana probe
  assets/grafana/deployment.yaml
  jsonnet/grafana.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#167 configsharing: Add Grafana host syncing
  pkg/manifests/manifests.go
  pkg/tasks/configsharing.go
Labels: approved, lgtm, size/S

#170 manifests: Make URL uppercase in config sharing scheme
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/XS

#171 jsonnet/grafana: disable http probe against grafana, ...
  assets/grafana/deployment.yaml
  jsonnet/grafana.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S
