Repository openshift/cluster-monitoring-operator, pull requests merged in 2018-05, with the labels that each got.

#19 Remove resource limits
  assets/alertmanager/alertmanager.yaml
  assets/kube-state-metrics/kube-state-metrics-deployment.yaml
  assets/kube-state-metrics/kube-state-metrics-role-binding.yaml
  assets/kube-state-metrics/kube-state-metrics-role.yaml
  assets/node-exporter/node-exporter-ds.yaml
  assets/prometheus-k8s/prometheus-k8s.yaml
  assets/prometheus-operator/prometheus-operator.yaml
  manifests/cluster-monitoring-operator-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/kubestatemetrics.go
Labels: approved, lgtm, size/L

#20 Remove SCC from prometheus-operator
  assets/prometheus-operator/prometheus-operator.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#21 *: Cut v0.0.3
  CHANGELOG.md
  VERSION
Labels: approved, lgtm, size/XS

#22 Set GOOS=linux to build binaries for Linux by default
  Makefile
Labels: approved, lgtm, size/XS

#27 Remove securityContext by default
  assets/alertmanager/alertmanager.yaml
  assets/prometheus-k8s/prometheus-k8s.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#26 *: Cut v0.0.4
  CHANGELOG.md
  VERSION
Labels: approved, lgtm, size/XS

#24 Add namespace label to pod cpu, memory, and disk pod recording rules
  assets/prometheus-k8s/prometheus-k8s-rules.yaml
  pkg/manifests/bindata.go
  rules/k8s/kubernetes.rules.yaml
Labels: approved, lgtm, size/S

#28 manifests: Use emptydir to shadow Dockerfile volume directive
  assets/kube-state-metrics/kube-state-metrics-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S
