Repository openshift/cluster-monitoring-operator, pull requests merged in 2018-08, with the labels that each got.

#53 *: create CMO service monitor and alerting rule
  Dockerfile
  Dockerfile.generate
  Makefile
  assets/cluster-monitoring-operator/service-monitor.yaml
  assets/cluster-monitoring-operator/service.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/kube-state-metrics/cluster-role.yaml
  assets/kube-state-metrics/role.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-k8s/secret-etcd-certs.yaml
  assets/prometheus-operator/deployment.yaml
  hack/build-jsonnet.sh
  jsonnet/cluster-monitoring-operator.jsonnet
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/rules.jsonnet
  manifests/cluster-monitoring-operator-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/operator/operator.go
  pkg/tasks/clustermonitoringoperator.go
  scripts/deploy-on-openshift.sh
Labels: approved, lgtm, size/XL

#55 config: add http configuration
  assets/alertmanager/alertmanager.yaml
  jsonnet/alertmanager.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, lgtm, size/L

#56 Bump Prometheus Operator and Kube-Prometheus
  Gopkg.lock
  Gopkg.toml
  assets/prometheus-k8s/role-binding-default.yaml
  assets/prometheus-k8s/role-binding-kube-system.yaml
  assets/prometheus-k8s/role-binding-namespace.yaml
  assets/prometheus-k8s/role-binding-specific-namespaces.yaml
  assets/prometheus-k8s/role-default.yaml
  assets/prometheus-k8s/role-kube-system.yaml
  assets/prometheus-k8s/role-namespace.yaml
  assets/prometheus-k8s/role-specific-namespaces.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/service-monitor.yaml
  hack/merge_cluster_roles.py
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/cluster-monitoring-operator-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/tasks/prometheus.go
  vendor/github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go
  vendor/github.com/coreos/prometheus-operator/pkg/alertmanager/statefulset.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/client.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/openapi_generated.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1alpha1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/promcfg.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/rule_configmap_migration.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/rules.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/statefulset.go
  vendor/github.com/coreos/prometheus-operator/test/framework/alertmanager.go
  vendor/github.com/coreos/prometheus-operator/test/framework/cluster_role.go
  vendor/github.com/coreos/prometheus-operator/test/framework/cluster_role_binding.go
  vendor/github.com/coreos/prometheus-operator/test/framework/config_map.go
  vendor/github.com/coreos/prometheus-operator/test/framework/framework.go
  vendor/github.com/coreos/prometheus-operator/test/framework/helpers.go
  vendor/github.com/coreos/prometheus-operator/test/framework/ingress.go
  vendor/github.com/coreos/prometheus-operator/test/framework/namespace.go
  vendor/github.com/coreos/prometheus-operator/test/framework/pod.go
  vendor/github.com/coreos/prometheus-operator/test/framework/prometheus.go
  vendor/github.com/coreos/prometheus-operator/test/framework/prometheus_rule.go
  vendor/github.com/coreos/prometheus-operator/test/framework/role-binding.go
  vendor/github.com/mitchellh/hashstructure/LICENSE
  vendor/github.com/mitchellh/hashstructure/hashstructure.go
  vendor/github.com/mitchellh/hashstructure/include.go
Labels: approved, lgtm, size/XXL

#58 Makefile: prevent which logs in stderr
  Makefile
Labels: approved, lgtm, size/XS

#60 hack,manifests: deduplicate cluster roles
  hack/merge_cluster_roles.py
  manifests/cluster-monitoring-operator-role.yaml
Labels: approved, lgtm, size/L

#62 Makefile: don't install binaries as direct deps
  .travis.yml
  Dockerfile
  Makefile
Labels: approved, lgtm, size/M

#63 *: enable unit tests
  .travis.yml
  cmd/operator/main.go
  pkg/manifests/manifests_test.go
Labels: size/S

#64 OWNERS: add lucas and sergiusz
  OWNERS
Labels: approved, lgtm, size/XS

#65 config: add no_proxy configuration
  assets/alertmanager/alertmanager.yaml
  jsonnet/alertmanager.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, lgtm, size/M

#66 pkg/manifests: add nodeSelector to prometheus operator config
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, lgtm, size/S

#67 Remove Prometheus Operator container security context
  assets/prometheus-operator/deployment.yaml
  jsonnet/prometheus-operator.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#68 Update integration of cluster components description
  README.md
Labels: approved, lgtm, size/S

#69 Makefile: container build operator with deps
  .travis.yml
  Dockerfile
  Makefile
Labels: approved, lgtm, size/S

#70 prometheus-operator: Update to v0.23.1
  assets/grafana/dashboard-sources.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator/deployment.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
Labels: approved, lgtm, size/M

#71 assets: bump kube-prometheus assets
  assets/alertmanager/alertmanager.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
Labels: approved, lgtm, size/S

#73 add recording rule for build metrics
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#78 Update kube-prometheus dependency
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L

#79 Fix duplicate rule group name
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#80 node-exporter: bind-mount correct root filesystem
  assets/node-exporter/daemonset.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#81 Update kubernetes-mixin
  assets/grafana/dashboard-definitions.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#83 Update kubernetes-mixin
  assets/grafana/dashboard-definitions.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L

#84 Bump kube-state-metrics scrape timeout
  assets/kube-state-metrics/service-monitor.yaml
  jsonnet/kube-state-metrics.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS
