Repository openshift/cluster-monitoring-operator, pull requests merged in 2018-09, with the labels that each got.

#86 assets: bump kubernetes-mixins
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#87 Add cluster-monitoring-view ClusterRole
  assets/cluster-monitoring-operator/cluster-role.yaml
  jsonnet/cluster-monitoring-operator.jsonnet
  manifests/cluster-monitoring-operator-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/clustermonitoringoperator.go
Labels: approved, lgtm, size/M

#89 jsonnet: Remove runbooks
  Makefile
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  jsonnet/remove_runbook.libsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#90 Makefile: re-vendor when jsonnetfile changes
  Makefile
Labels: approved, lgtm, size/XS

#92 Update kubernetes mixins with dashboards using a default timezone
  assets/grafana/dashboard-definitions.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#93 Remove duplicate dashboards
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XXL

#94 Merge master into 3.11 release
  Makefile
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/remove_runbook.libsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XXL

#91 Makefile: comment for operator-no-deps
  Makefile
Labels: approved, lgtm, size/XS

#95 manifests: Set operator version to v0.1.0
  manifests/cluster-monitoring-operator.yaml
Labels: approved, lgtm, size/XS

#96 Fix cluster monitoring operator alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#99 *: Add priority classes
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-operator/deployment.yaml
  jsonnet/grafana.jsonnet
  jsonnet/kube-state-metrics.jsonnet
  jsonnet/node-exporter.jsonnet
  jsonnet/prometheus-operator.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#105 bump version
  VERSION
Labels: approved, size/XS

#103 add Telemeter client
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  assets/telemeter-client/deployment.yaml
  assets/telemeter-client/secret.yaml
  assets/telemeter-client/service-monitor.yaml
  assets/telemeter-client/service.yaml
  cmd/operator/main.go
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/operator/operator.go
  pkg/tasks/kubestatemetrics.go
  pkg/tasks/telemeter.go
Labels: approved, lgtm, size/XL

#106 Integrate into cluster version operator
  Dockerfile
  Makefile
  VERSION
  cmd/operator/main.go
  hack/cluster-monitoring-operator-role.yaml.in
  hack/merge_cluster_roles.py
  manifests/01-namespace.yaml
  manifests/02-role-binding.yaml
  manifests/02-role.yaml
  manifests/03-config.yaml
  manifests/04-deployment.yaml
  manifests/cluster-monitoring-operator-role.yaml
  manifests/image-references
  manifests/secret-etcd-certs.yaml
  pkg/client/client.go
Labels: approved, lgtm, size/L

#107 manifests: add missing namespace to service account
  manifests/02-role-binding.yaml
Labels: approved, lgtm, size/XS
