Repository openshift/cluster-monitoring-operator, pull requests merged in 2018-06, with the labels that each got.

#30 Cleanup rules
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
  rules/etcd/etcd3_alert.rules.yaml
  rules/k8s/alertmanager.rules.yaml
  rules/k8s/general.rules.yaml
  rules/k8s/kube-controller-manager.rules.yaml
  rules/k8s/kube-scheduler.rules.yaml
  rules/k8s/kube-state-metrics.rules.yaml
  rules/k8s/kubelet.rules.yaml
  rules/k8s/kubernetes.rules.yaml
  rules/k8s/node.rules.yaml
  rules/k8s/prometheus.rules.yaml
Labels: approved, lgtm, size/XL

#31 manifests: Fix default role to be in default namespace
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/XS

#32 Update to prometheus-operator v0.20.0
  Gopkg.lock
  Gopkg.toml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  hack/build-jsonnet.sh
  jsonnet/jsonnetfile.lock.json
  manifests/cluster-monitoring-operator-role.yaml
  pkg/manifests/bindata.go
  vendor/github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/alertmanager.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/client.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/openapi_generated.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/prometheus.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/prometheusrule.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/monitoring/v1alpha1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/promcfg.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/rule_configmap_migration.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/rules.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/statefulset.go
  vendor/github.com/coreos/prometheus-operator/test/framework/prometheus.go
  vendor/github.com/coreos/prometheus-operator/test/framework/rulefile.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
Labels: approved, lgtm, size/XXL

#33 *: Cut v0.0.5
  CHANGELOG.md
  VERSION
Labels: approved, lgtm, size/XS

#34 Fix creation of default rules
  pkg/client/client.go
  pkg/manifests/manifests.go
  pkg/tasks/prometheus.go
Labels: approved, lgtm, size/M

#35 *: Cut v0.0.6
  CHANGELOG.md
  VERSION
Labels: approved, lgtm, size/XS

#37 Grafana
  assets/alertmanager/secret.yaml
  assets/grafana/cluster-role-binding.yaml
  assets/grafana/cluster-role.yaml
  assets/grafana/config.yaml
  assets/grafana/dashboard-datasources.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/dashboard-sources.yaml
  assets/grafana/deployment.yaml
  assets/grafana/proxy-secret.yaml
  assets/grafana/route.yaml
  assets/grafana/service-account.yaml
  assets/grafana/service.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/htpasswd-secret.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/grafana.jsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/prometheus.jsonnet
  manifests/cluster-monitoring-operator-role.yaml
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/grafana.go
  pkg/tasks/prometheus.go
Labels: approved, size/XXL

#40 Use openshift/origin-base as base container image
  .dockerignore
  Dockerfile
  assets/alertmanager/alertmanager.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/main.jsonnet
  manifests/cluster-monitoring-config.yaml
  manifests/cluster-monitoring-operator.yaml
  pkg/manifests/bindata.go
Labels: approved, size/M

#42 Change default retention to 15 days
  pkg/manifests/config.go
Labels: approved, lgtm, size/XS
