Repository openshift/cluster-monitoring-operator, pull requests merged in 2018-07, with the labels that each got.

#41 Update jsonnet and use openshift based images
  assets/grafana/config.yaml
  assets/grafana/dashboard-datasources.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-operator/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  manifests/cluster-monitoring-config.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/grafana.go
  pkg/tasks/prometheus.go
Labels: approved, lgtm, size/L

#44 *: Update Prometheus and Alertmanager
  assets/alertmanager/alertmanager.yaml
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, size/S

#45 manifests: Make node-selectors configurable
  pkg/manifests/config.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/S

#43 *: Add etcd monitoring
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  assets/prometheus-k8s/endpoints-etcd.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-k8s/service-etcd.yaml
  assets/prometheus-k8s/service-monitor-etcd.yaml
  hack/build-jsonnet.sh
  hack/generate-etcd-secret.sh
  jsonnet/main.jsonnet
  jsonnet/prometheus.jsonnet
  manifests/cluster-monitoring-config.yaml
  manifests/secret-etcd-certs.yaml
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/prometheus.go
  scripts/deploy-on-openshift.sh
Labels: approved, lgtm, size/XXL

#39 Disable the wifi collector in node_exporter
  assets/node-exporter/daemonset.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/node-exporter.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#47 Normalize Grafana setup
  assets/grafana/config.yaml
  assets/grafana/deployment.yaml
  hack/ocp-images.sh
  jsonnet/grafana.jsonnet
  pkg/manifests/bindata.go
Labels: approved, size/L

#52 *: add basic instrumentation
  cmd/operator/main.go
  hack/ocp-images.sh
  manifests/cluster-monitoring-operator.yaml
  pkg/operator/operator.go
Labels: approved, lgtm, size/M
