Repository openshift/cluster-monitoring-operator, pull requests merged in 2018-12, with the labels that each got.

#175 Fix telemeter client metrics
  assets/alertmanager/service-monitor.yaml
  assets/kube-state-metrics/service-monitor.yaml
  assets/node-exporter/service-monitor.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/service-monitor.yaml
  assets/prometheus-k8s/serving-certs-ca-bundle.yaml
  assets/telemeter-client/service-monitor.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/kube-state-metrics.jsonnet
  jsonnet/node-exporter.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#176 Add OpenShift apiserver ServiceMonitor
  assets/prometheus-k8s/role-binding-specific-namespaces.yaml
  assets/prometheus-k8s/role-specific-namespaces.yaml
  assets/prometheus-k8s/service-monitor-open-shift-apiserver.yaml
  jsonnet/main.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheus.go
Labels: approved, lgtm, size/L

#180 Set correct image for Prometheus Adapter
  assets/prometheus-adapter/deployment.yaml
  jsonnet/main.jsonnet
  jsonnet/prometheus-adapter.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#181 Dockerfile: cleanup rpm dependencies
  Dockerfile
Labels: approved, lgtm, size/XS

#182 pkg/client: fix namespaceSelector being ignored when creating client
  pkg/client/client.go
Labels: approved, lgtm, size/S

#183 jsonnet: add named tenancy port
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#186 assets/grafana: Regenerate dashboard definitions
  assets/grafana/dashboard-definitions.yaml
Labels: approved, lgtm, size/XS

#185 test/e2e: Replace e2e tests with basic stub
  Makefile
  test/e2e/main_test.go
Labels: approved, lgtm, size/S

#188 test/e2e: fix panic in parsing kubeconfig cli flag
  test/e2e/main_test.go
Labels: approved, lgtm, size/XS

#189 route: Use insecureEdgeTerminationPolicy to redirect from http to https
  assets/alertmanager/route.yaml
  assets/grafana/route.yaml
  assets/prometheus-k8s/route.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/grafana.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S
