Repository openshift/cluster-monitoring-operator, pull requests merged in 2019-04, with the labels that each got.

#275 jsonnet: Decrease KubeClientCertificateExpiration expiration threshold
  assets/alertmanager/secret.yaml
  assets/grafana/deployment.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#299 test/e2e: check if telemeter-client is present
  test/e2e/main_test.go
Labels: approved, lgtm, size/XS

#301 pkg/operator: do not print "Error" when log msg is a warning
  pkg/operator/operator.go
Labels: approved, lgtm, size/XS

#303 jsonnet: Update kube-prometheus
  assets/prometheus-adapter/config-map.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#304 Patch recording rules to only pending and running cpu & memory requests
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#305 Bump KubeletTooManyPods alert threshold to 250
  Makefile
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#307 use new instructions on how to build go-jsonnet
  Makefile
Labels: approved, lgtm, size/XS

#306 use containerized yamllint in CI pipeline
  .travis.yml
  hack/yamllint.sh
Labels: approved, lgtm, size/S

#310 [backport] node-exporter tolerate all nodes
  assets/node-exporter/daemonset.yaml
  jsonnet/node-exporter.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#313 Add SessionAffinity to Prometheus and Alertmanager services
  assets/alertmanager/service.yaml
  assets/prometheus-k8s/service.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#317 rules: Fix KubeletTooManyPods alert message
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#318 test/e2e: Disable scheduler and controller-manager e2e until fixed
  test/e2e/main_test.go
Labels: approved, lgtm, size/XS

#311 Priority class & jsonnet update
  assets/alertmanager/alertmanager.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/rules.yaml
  assets/telemeter-client/deployment.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XXL

#320 Support previous bash versions (Mac included)
  hack/build-jsonnet.sh
Labels: approved, lgtm, ok-to-test, size/XS

#321 Update cluster-monitoring-operator image
  manifests/cluster-monitoring-operator.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#319 jsonnet: Update deps
  assets/alertmanager/service.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-k8s/service-monitor-kubelet.yaml
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#315 Bug 1697644: operator: use openshift-config/pull-secret to fetch the pull secret for cloud.openshift.com
  pkg/operator/operator.go
Labels: approved, lgtm, size/XS

#323 jsonnet: etcd_object_counts recording rule
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#326 alerts: Remove node interface down alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#302 pkg/manifests/operator: synthesize etcd secret
  assets/prometheus-k8s/service-monitor-etcd.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/operator/operator.go
  pkg/tasks/prometheus.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/L

#328 pkg/client: compare Service object before updating it
  pkg/client/client.go
Labels: approved, lgtm, size/XS

#329 pkg/client: compare only parts of Service resource instead of full object
  pkg/client/client.go
Labels: approved, lgtm, size/XS

#316 serviceMonitorKubeScheduler/serviceMonitorKubeControllerManager: enable TLS
  assets/prometheus-k8s/service-monitor-kube-controller-manager.yaml
  assets/prometheus-k8s/service-monitor-kube-scheduler.yaml
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#327 jsonnet: bump telemeter client version
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#332 pkg/tasks/prometheusadapter: deploy aggregated cluster role
  assets/prometheus-adapter/cluster-role-aggregated-metrics-reader.yaml
  jsonnet/jsonnetfile.lock.json
  manifests/02-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheusadapter.go
  test/e2e/framework/framework.go
  test/e2e/prometheusadapter_test.go
Labels: approved, lgtm, size/L

#337 test/e2e: Remove tests for components this repo is not responsible for
  test/e2e/main_test.go
Labels: approved, lgtm, size/XS

#334 *: Use timex metrics instead of ntp
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#333 *: Change ClusterOperator failing status to degraded
  Gopkg.lock
  pkg/client/clusteroperator.go
  pkg/client/condition.go
  pkg/client/condition_test.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_console.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/scheduler.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/scheduling.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/securitycontextconstraints.go
Labels: approved, lgtm, size/XXL

#335 test/e2e: use built-in logger insted of 'log'
  test/e2e/alertmanager_test.go
  test/e2e/multi_namespace_test.go
  test/e2e/prometheus_test.go
  test/e2e/prometheusadapter_test.go
Labels: approved, lgtm, size/M

#336 pkg/manifests: Update etcd namespace
  assets/prometheus-k8s/service-monitor-etcd.yaml
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#339 manifests: Add openshift-etcd role and role-binding
  assets/prometheus-k8s/role-binding-specific-namespaces.yaml
  assets/prometheus-k8s/role-specific-namespaces.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#340 manifests: Remove etcd gRPC calls failed alerts
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M
