Repository openshift/cluster-monitoring-operator, pull requests merged in 2019-12, with the labels that each got.

#554 Alertmanager configured route metric
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#557 Bug 1773246: Add a rule that sums the nodes reporting virt_platform types
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/node-exporter.jsonnet
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#574 add bparees to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#575 jsonnet: unpin dependencies
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#578 Bug 1779912: Add a whitelist cluster:usage:* for telemetry for simple usage metric exposure
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#576 test/e2e/prometheusadapter: reenable CA rotation test
  test/e2e/framework/route_client.go
  test/e2e/main_test.go
  test/e2e/prometheusadapter_test.go
Labels: approved, lgtm, size/L

#580 Bug 1780037: Undo creating alertmanager-access role
  Documentation/user-guides/configuring-prometheus-alertmanager.md
  Makefile
  assets/alertmanager/alertmanager.yaml
  assets/alertmanager/role.yaml
  assets/prometheus-k8s/cluster-role.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/prometheus.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/alertmanager.go
  test/e2e/framework/framework.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#579 jsonnet: Gather ~10 metrics that tell us workloads that are being used
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#582 Bug 1780408: Gather ~10 metrics that tell us workloads that are being used
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#573 Bug 1773246: Bump telemeter to get whitelist changes for virt_platform
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#583 Bug 1781104: revert failed pod marked as NotReady
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#434 *: Move sending telemetry to Prometheus native functionality
  Documentation/data-collection.md
  README.md
  cmd/operator/main.go
  go.mod
  go.sum
  hack/build-jsonnet.sh
  hack/local-cmo.sh
  hack/shellcheck.sh
  jsonnet/cluster-monitoring-operator.jsonnet
  jsonnet/main.jsonnet
  jsonnet/prometheus.jsonnet
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
  manifests/0000_50_cluster_monitoring_operator_05-deployment.yaml
  manifests/0000_50_cluster_monitoring_operator_06-clusteroperator.yaml
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/operator/operator.go
  pkg/relabelgen/relabelgen.go
  pkg/relabelgen/relabelgen_test.go
  pkg/tasks/telemeter.go
  test/e2e/main_test.go
  test/e2e/telemeter_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#584 Bug 1779913: Add a whitelist cluster:usage:* for telemetry for simple usage metric exposure
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#586 Revert "Merge pull request #434 from brancz/telemetry-via-prom"
  Documentation/data-collection.md
  README.md
  cmd/operator/main.go
  go.mod
  go.sum
  hack/build-jsonnet.sh
  hack/local-cmo.sh
  hack/shellcheck.sh
  jsonnet/cluster-monitoring-operator.jsonnet
  jsonnet/main.jsonnet
  jsonnet/prometheus.jsonnet
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
  manifests/0000_50_cluster_monitoring_operator_04-deployment.yaml
  manifests/0000_50_cluster_monitoring_operator_05-clusteroperator.yaml
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/operator/operator.go
  pkg/relabelgen/relabelgen.go
  pkg/relabelgen/relabelgen_test.go
  pkg/tasks/telemeter.go
  test/e2e/main_test.go
  test/e2e/telemeter_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#588 jsonnet: bump kubernetes-mixin
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L

#572 Bug 1773665: add cluster cpu recording rules
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/node-exporter.jsonnet
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#589 Bug 1773665: Bump telemeter to backport changes BZ 1760393 to 4.2.z
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/XS

#591 Bug 1784144: Bump jsonnet dependencies
  assets/alertmanager/secret.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/node-exporter/daemonset.yaml
  assets/node-exporter/service-monitor.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L, ¯\_(ツ)_/¯

#593 jsonnet/jsonnetfile.lock.json: Update dependencies
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-k8s/service-monitor-kubelet.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#595 Bug 1784166: Alert on high number of etcd leader changes in a short time window
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
