Repository openshift/cluster-monitoring-operator, pull requests merged in 2019-10, with the labels that each got.

#494 Increase time periods for promQL expressions
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#496 bump kube-prometheus to latest revision
  assets/prometheus-adapter/config-map.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#498 enable node_exporter cpu_info metric
  assets/node-exporter/daemonset.yaml
  jsonnet/node-exporter.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS, ¯\_(ツ)_/¯

#501 Bug 1759880: update container and pod labels
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#504 pkg/tasks/prometheusoperator.go: Remove migration code
  pkg/tasks/prometheusoperator.go
Labels: approved, lgtm, size/S

#502 Use access to Alertmanager CR to gate access to AM
  Documentation/user-guides/configuring-prometheus-alertmanager.md
  Makefile
  assets/alertmanager/alertmanager.yaml
  assets/alertmanager/role.yaml
  assets/prometheus-k8s/cluster-role.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/prometheus.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L

#508 Override honor_labels for user workload
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/prometheus-user-workload.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#503 thanos-querier: proxies initial commit
  assets/prometheus-k8s/service.yaml
  assets/prometheus-user-workload/cluster-role.yaml
  assets/prometheus-user-workload/service.yaml
  assets/thanos-querier/cluster-role-binding.yaml
  assets/thanos-querier/cluster-role.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-querier/kube-rbac-proxy-secret.yaml
  assets/thanos-querier/oauth-cookie-secret.yaml
  assets/thanos-querier/oauth-htpasswd-secret.yaml
  assets/thanos-querier/route.yaml
  assets/thanos-querier/service-account.yaml
  assets/thanos-querier/service.yaml
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-querier.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/tasks/thanos_querier.go
  test/e2e/framework/prometheus_client.go
Labels: approved, lgtm, size/XL

#511 pkg/tasks/configsharing: add thanos route
  pkg/manifests/manifests.go
  pkg/tasks/configsharing.go
Labels: approved, lgtm, size/S

#515 Bug 1763046: manifests: remove setting limits on CMO
  manifests/cluster-monitoring-operator.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#514 manifests: add missing thanos querier tests
  pkg/manifests/manifests_test.go
Labels: approved, lgtm, size/M

#491 Bug 1755242: jsonnet/rules: fix memory_usage_bytes recording rule
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS, ¯\_(ツ)_/¯

#497 Bug 1750283: Backport metric for core capacity by node role and operating system.
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/M

#505 Bug 1746711: fix client reload port
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#517 Enable honor timestamps overriding for user workload
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/prometheus-user-workload.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#520 [MON-808] add ignoreNamespaceSelectors field
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/prometheus-user-workload.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#507 Bug 1761887: tasks/prometheusoperator: Change deployment selector migration strategy
  pkg/tasks/prometheusoperator.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#523 Bug ????: improve CMO reconciliation alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#524 Bug 1750283: Bump telemeter-client
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#527 manifests/config: name user workload settings as tech preview
  pkg/manifests/config.go
Labels: approved, lgtm, size/XS

#521 Bug 1760393: Add metrics for collecting socket and hyperthreading enablement.
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/M

#522 pkg/tasks: setup GRPC TLS for thanos querier
  assets/cluster-monitoring-operator/grpc-tls-secret.yaml
  assets/prometheus-k8s/grpc-tls-secret.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/grpc-tls-secret.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-querier/grpc-tls-secret.yaml
  go.mod
  go.sum
  jsonnet/cluster-monitoring-operator.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-querier.jsonnet
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/tls.go
  pkg/manifests/tls_test.go
  pkg/operator/operator.go
  pkg/tasks/clustermonitoringoperator.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/thanos_querier.go
  vendor/github.com/openshift/library-go/LICENSE
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/crypto/rotation.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/authentication/user/doc.go
  vendor/k8s.io/apiserver/pkg/authentication/user/user.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#531 Bug 1760393: Bump telemeter-client
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS
