Repository openshift/cluster-monitoring-operator, pull requests merged in 2019-09, with the labels that each got.

#457 Bug 1745379: Fix many-to-many matching not allowed
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#463 Makefile: add go proxy support
  Makefile
Labels: approved, lgtm, size/XS

#464 hack: add script to run CMO locally
  hack/local-cmo.sh
Labels: approved, lgtm, size/S

#456 Update node_exporter mixin and kubernetes mixin
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  assets/prometheus-adapter/config-map.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XXL

#465 pkg/tasks/tasks.go: Return error only when its not nil
  pkg/tasks/tasks.go
Labels: approved, lgtm, size/XS

#467 Bump prometheus-operator release to 0.32
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#468 changes apiversion of the deployment to apps/v1
  manifests/0000_50_cluster_monitoring_operator_04-deployment.yaml
Labels: approved, lgtm, size/XS

#469 Bug 1745877: Fix typo in dashboard name
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#440 Bug 1741055: pkg/client: Set Reason in ClusterOperatorStatusCondition
  pkg/client/clusteroperator.go
  pkg/client/condition.go
  pkg/client/condition_test.go
  pkg/operator/operator.go
  pkg/strings/strings.go
  pkg/strings/strings_test.go
  pkg/tasks/tasks.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#475 Use DNS SRV to get prometheus port
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#466 Bug 1749451: Capture sum of cpu capacity cores by OS (RHCOS or RHEL) with version, arch, and role for the nodes.
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/M

#477 Bug 1751571: Bump prometheus-operator to 0.33 and node-mixin
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#478 Bug 1749451: Bump telemeter-client
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#481 Bump openshift-state-meterics libsonet file
  assets/openshift-state-metrics/cluster-role.yaml
  assets/openshift-state-metrics/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#476 Add test case: prometheus & alertmanager pods should use anti-affinity
  test/e2e/prometheus_test.go
Labels: approved, lgtm, size/M

#482 Bug 1753091: Inject http_proxy vars
  assets/alertmanager/alertmanager.yaml
  assets/grafana/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/grafana.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#484 jsonnet: Pin components to the 4.2 release
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
Labels: approved, lgtm, size/XS

#483 Bug 1753559: jsonnet: increase the 'for' clause for timestamp alerts
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#486 Add console_url metric
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#487 delete obsolete service monitors
  jsonnet/prometheus.jsonnet
  pkg/client/client.go
  pkg/tasks/prometheus.go
Labels: approved, lgtm, size/M

#490 Bug 1755240: jsonnet/rules: fix memory_usage_bytes recording rule
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#492 Pin dependencies to master
  README.md
  assets/grafana/deployment.yaml
  assets/node-exporter/service-monitor.yaml
  assets/prometheus-adapter/config-map.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L

#489 Bump master to 4.3 branch
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/service.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-querier/service.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/node-exporter.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-querier.jsonnet
  manifests/0000_50_cluster_monitoring_operator_04-deployment.yaml
  manifests/image-references
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/thanos_querier.go
  test/e2e/alertmanager_test.go
  test/e2e/prometheus_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
