Repository openshift/cluster-monitoring-operator, pull requests merged in 2019-11, with the labels that each got.

#528 Bug 1750283: Fix label as backport needs beta but 4.2 does not
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/XS

#533 jsonnet: Update deps
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-k8s/service-monitor-kubelet.yaml
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XXL

#513 Bug 1763057: pkg/client: Fix setting number of unavailable pods for DaemonSet
  pkg/client/client.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#537 jsonnet: bump telemeter-client to latest version for multus telemeter …
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#542 jsonnet/jsonnetfile.json: pin prometheus-operator
  assets/grafana/dashboard-definitions.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#546 grafana: Secure cookie true
  assets/grafana/config.yaml
  jsonnet/grafana.jsonnet
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/L

#543 Bug 1739375; drop remote write dashboard
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XXL

#538 jsonnet: node_exporter should run any available initial text exporters
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/node-exporter.jsonnet
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/M

#547 jsonnet: bump kubernetes-mixin to latest version
  jsonnet/jsonnetfile.lock.json
Labels: approved, lgtm, size/XS

#548 BUG 1772000: grafana: Set cookie_secure to true
  assets/grafana/config.yaml
  jsonnet/grafana.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#552 jsonnet: Report virt_platform_type via telemetry
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XS

#549 OWNERS: add new members
  OWNERS
Labels: approved, lgtm, size/XS

#545 test/e2e: add user workload monitoring
  go.mod
  test/e2e/framework/framework.go
  test/e2e/framework/prometheus_client.go
  test/e2e/main_test.go
  test/e2e/multi_namespace_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, lgtm, size/L

#544 Bug 1771389: Refactor cpu recording rules
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#553 Bug 1741685: pkg/client: add more relatedObjects to improve data from must-gather
  pkg/client/status_reporter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#529 Bug 1766984: trustedCA bundle support for alertmanager oauth proxy
  pkg/manifests/manifests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#558 Bug 1774060: create alertmanager-access role, add e2e tests for user workload monitoring
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/alertmanager.go
  test/e2e/framework/framework.go
  test/e2e/framework/route_client.go
  test/e2e/framework/route_client_test.go
  test/e2e/main_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#540 Bug 1770779: Fix filesystem alerts
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#560 test/e2e/prometheusadapter: disable rotation test
  test/e2e/prometheusadapter_test.go
Labels: approved, lgtm, size/XS

#556 jsonnet: Pod recording rules are incorrectly summing resources
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#559 Bug 1766181: trustedCA bundle support for prometheus and its sidecars
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/trusted-ca-bundle.yaml
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheus.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#562 jsonnet: pin dependencies for 4.3
  jsonnet/jsonnetfile.json
Labels: approved, lgtm, size/XS

#539 jsonnet/main.jsonnet: remove openshift control plane rbac deployment
  assets/prometheus-k8s/role-binding-specific-namespaces.yaml
  assets/prometheus-k8s/role-specific-namespaces.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#563 Bug 1774621: telemeter: bump dependencies
  assets/prometheus-k8s/rules.yaml
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#566 Bug 1776085: pkg/manifests: mount trustedCA bundle in grafana-proxy container
  pkg/manifests/manifests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#525 Bug 1776810: improve CMO reconciliation alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#568 Bug 1762657: pkg/tasks/thanos-querier: render dns discovery conditionally
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/thanos_querier.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
