Repository openshift/cluster-monitoring-operator, pull requests merged in 2020-06, with the labels that each got.

#798 Merge master-4.6 into master
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  assets/kube-state-metrics/service-monitor.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator-user-workload/0thanosruler-custom-resource-definition.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/operator-certs-ca-bundle.yaml
  assets/prometheus-operator/prometheus-rule-validating-webhook.yaml
  assets/prometheus-operator/service.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/alertmanagers-config-secret.yaml
  assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
  cmd/operator/main.go
  go.mod
  hack/cluster-monitoring-operator-role.yaml.in
  jsonnet/kube-state-metrics.jsonnet
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-operator.jsonnet
  jsonnet/rules.jsonnet
  jsonnet/thanos-ruler.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/tasks/prometheusoperator.go
  test/e2e/framework/framework.go
  test/e2e/validatingwebhook_test.go
Labels: approved, lgtm

#797 Bug 1800489: Patch kube pv storage alert release 3.11
  assets/prometheus-k8s/rules.yaml
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#799 MON-1142: Thanos Querier rules federation
  CHANGELOG.md
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  test/e2e/framework/client.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, lgtm

#795 Add RHMI metrics to telemeter
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
Labels: approved, lgtm

#807 Bug 1845446: KubeApiLatency alert firing even though not all conditions are matched
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#753 test/e2e/framework: log HTTP response body on non-OK status code
  test/e2e/framework/client.go
Labels: approved, lgtm

#813 pkg/client: improve error messages
  pkg/client/client.go
Labels: approved, lgtm

#800 Add metrics and rules for Thanos querier
  CHANGELOG.md
  assets/thanos-querier/cluster-role-binding.yaml
  assets/thanos-querier/cluster-role.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-querier/grpc-tls-secret.yaml
  assets/thanos-querier/kube-rbac-proxy-secret.yaml
  assets/thanos-querier/oauth-cookie-secret.yaml
  assets/thanos-querier/oauth-htpasswd-secret.yaml
  assets/thanos-querier/prometheus-rule.yaml
  assets/thanos-querier/route.yaml
  assets/thanos-querier/service-account.yaml
  assets/thanos-querier/service-monitor.yaml
  assets/thanos-querier/service.yaml
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/tasks/thanos_querier.go
Labels: approved, lgtm

#814 Bug 1845825: Cleanup thanos ruler route when user workload monitoring is disabled
  pkg/client/client.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#804 Allow user workload monitoring configuration ConfigMap to be created in UWM ns
  CHANGELOG.md
  cmd/operator/main.go
  examples/config/config.yaml
  examples/user-workload/cluster-monitoring-configmap.yaml
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/prometheusoperator_user_workload.go
  pkg/tasks/telemeter.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, lgtm

#820 Bug 1846397: Fix AlertmanagerConfigInconsistent alert
  assets/node-exporter/daemonset.yaml
  assets/node-exporter/service-monitor.yaml
  assets/node-exporter/service.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#822 Bug 1850466: fix AlertmanagerConfigInconsistent alert
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator-user-workload/0thanosruler-custom-resource-definition.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#825 Bug 1850717: Add namespace selector to CPUThrottlingHigh
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#823 Add edit Role for user workload configuration
  assets/cluster-monitoring-operator/user-workload-config-edit-role.yaml
  examples/user-workload/configmap.yaml
  jsonnet/cluster-monitoring-operator.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/clustermonitoringoperator.go
Labels: approved, lgtm

#787 Bug 1834913: bump kubernetes-monitoring/kubernetes-mixin
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#827 *: Bump etcd-mixin to 2b79442d8e9f
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster_monitoring_operator_01-dashboards.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#816 pkg/manifests: rotate grpc key material gracefully
  pkg/manifests/tls.go
  pkg/manifests/tls_test.go
  pkg/tasks/clustermonitoringoperator.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, lgtm

#832 Bug 1851873: Add namespace selector to CPUThrottlingHigh
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#831 hack, jsonnet: deploy CRDs using manifests payload
  assets/prometheus-operator/deployment.yaml
  hack/build-jsonnet.sh
  jsonnet/prometheus-operator.jsonnet
  manifests/0000_50_cluster_monitoring_operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0thanosruler-custom-resource-definition.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#811 *: cleanup OWNERS file
  OWNERS
Labels: approved, lgtm

#834 Disable grafana telemetry
  assets/grafana/config.yaml
  jsonnet/grafana.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm
