Repository openshift/cluster-monitoring-operator, pull requests merged in 2020-09, with the labels that each got.

#918 Bug 1867603: ds/node-exporter: Set maxUnavailable 10%
  assets/node-exporter/daemonset.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#920 Bug 1873353: bump Thanos to v0.15.0
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/jsonnetfile.json
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#919 Bug 1875470: Include OS, arch labels for node, core count
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#921 Bug 1862432: unmask prometheus-adapter service monitor
  assets/prometheus-adapter/service-monitor.yaml
  jsonnet/prometheus-adapter.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheusadapter.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#926 Bug 1858010: decrease alerts severity
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#922 Bug 1877256: disable grafana telemetry
  assets/grafana/config.yaml
  jsonnet/grafana.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test

#929 Bug 1822442: Note about telemeter config
  pkg/manifests/manifests.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#928 Bug 1879047: bump prometheus-operator 0.42
  CHANGELOG.md
  Makefile
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/prometheus-rule-validating-webhook.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  go.mod
  go.sum
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/prometheus-operator-user-workload.jsonnet
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/manifests/bindata.go
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#925 Bug 1877735: Adding CodeReady Workspaces metrics to the allowlist / config.yaml
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#934 Bug 1881061: Add UWM namespace to the operator's related objects
  pkg/client/client.go
  pkg/client/status_reporter.go
  pkg/client/status_reporter_test.go
  pkg/operator/operator.go
  test/e2e/framework/framework.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#923 Update readme to remove stale information
  README.md
Labels: approved, bugzilla/valid-bug, lgtm

#930 Rewrite merge_cluster_roles script in Go
  CONTRIBUTING.md
  Makefile
  hack/merge_cluster_roles.go
  hack/merge_cluster_roles.py
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test

#936 Bug 1881072: Bump dependencies including prometheus-operator to 0.42.1
  CHANGELOG.md
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/prometheus-rule-validating-webhook.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#927 Bug 1878155: Remove deprecated baseImage
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#939 Bug 1882428: add ThanosRuler, PodMonitor and Probe to operator group
  manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#938 Bug 1845561: disable (temporarily) resource requests for config reloaders
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#944 Bug 1882294: bump APIService to v1
  go.mod
  go.sum
  pkg/client/client.go
  pkg/manifests/manifests.go
  vendor/k8s.io/component-base/cli/flag/ciphersuites_flag.go
  vendor/k8s.io/component-base/cli/flag/ciphersuites_flag_114.go
  vendor/k8s.io/component-base/cli/flag/flags.go
  vendor/k8s.io/component-base/cli/flag/namedcertkey_flag.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#943 Bug 1845561: enable resource requests for config reloaders
  assets/alertmanager/alertmanager.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
