Repository openshift/cluster-monitoring-operator, pull requests merged in 2020-07, with the labels that each got.

#829 configure user workload monitoring cpu (and memory) requests
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm

#821 manifests/telemetry: replace apiserver_request_count with apiserver_request_total
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  Documentation/timeseries.txt
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
Labels: approved, lgtm, ok-to-test

#837 Bug 1848492: Enforce 24h cookie expiration time
  OWNERS
  assets/alertmanager/alertmanager.yaml
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/security-context-constraints.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/grafana.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#818 Bug 1813221: jsonnet: add missing resource requests for alertmanager sidecar
  assets/alertmanager/alertmanager.yaml
  jsonnet/alertmanager.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#833 Bug 1851920: Add namespace selector to CPUThrottlingHigh
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#826 Bug 1847318: set TLS min version to 1.2
  assets/prometheus-operator/deployment.yaml
  jsonnet/prometheus-operator.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#830 examples/user-workload/README.md: Detail user workload monitoring flow
  examples/user-workload/README.md
  examples/user-workload/configmap.yaml
Labels: approved, lgtm

#835 Bug 1843346: Removing CPUThrottlingHigh alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#843 Remove --manage-crds flag from prometheus-operator's arguments
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-operator.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm

#841 Bug 1813221: remove cpu limits for config reloader
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-operator.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#824 Bug 1850615: fix AlertmanagerConfigInconsistent alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#844 *: Bump mixins, including: Raise etcdHighNumberOfLeaderChanges threshold to 4
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/cluster-role-binding.yaml
  assets/kube-state-metrics/cluster-role.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/kube-state-metrics/service-account.yaml
  assets/kube-state-metrics/service.yaml
  assets/prometheus-k8s/rules.yaml
  assets/telemeter-client/deployment.yaml
  hack/jsonnet-lock-diff.py
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster_monitoring_operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0thanosruler-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  manifests/0000_90_cluster_monitoring_operator_01-dashboards.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#848 Bug 1818806: remove cpu limits for config reloader
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-operator.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#846 Update versions we are shipping
  assets/alertmanager/alertmanager.yaml
  assets/node-exporter/daemonset.yaml
  assets/node-exporter/service-monitor.yaml
  assets/node-exporter/service.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, ¯\_(ツ)_/¯

#838 Add scheduler feature usage metrics
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
Labels: approved, lgtm

#805 Bug 1845445: KubeApiLatency alert firing even though not all conditions are matched
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#850 Bump prometheus-operator to 0.40.0 version
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/prometheus-rule-validating-webhook.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-operator.jsonnet
  manifests/0000_50_cluster_monitoring_operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_00_0thanosruler-custom-resource-definition.yaml
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#809 Bug 1845444: KubeApiLatency alert firing even though not all conditions are matched
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#854 Bug 1846707: changing KubeQuotaExceeded to KubeQuotaFullyUsed
  CHANGELOG.md
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#849 Bash script to setup user workload monitoring OpenShift 4.6 test envs
  hack/uwm_setup.sh
  hack/uwm_setup_files/example-app-alerting-rule.yaml
  hack/uwm_setup_files/example-app-service-monitor.yaml
  hack/uwm_setup_files/prometheus-example-app.yaml
Labels: approved, lgtm

#859 pkg: remove 'hostport' configuration
  CHANGELOG.md
  pkg/manifests/config.go
  pkg/manifests/manifests.go
Labels: approved, lgtm

#858 jsonnet: avoid many-to-many errors for cluster:cpu_core_node_labels
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm

#862 pkg: delete deprecated configmap
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/configsharing.go
Labels: approved, lgtm

#870 Makefile: reset GOFLAGS when installing tooling
  Makefile
Labels: approved, lgtm

#856 test/e2e: check if prometheus is reachable before querying for prom rules
  test/e2e/multi_namespace_test.go
Labels: approved, lgtm

#866 Bug 1853250: pkg/manifests: update notBefore on cert renewal
  pkg/manifests/tls.go
  pkg/manifests/tls_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#873 Makefile: increase timeout of e2e tests to 30m
  Makefile
Labels: approved, lgtm

#865 pkg/manifests: Allow users to configure EnforcedSampleLimit for user
  CHANGELOG.md
  pkg/manifests/config.go
  pkg/manifests/manifests.go
Labels: approved, lgtm

#867 Bug 1855275: jsonnet: update prometheus-operator cluster role
  assets/prometheus-operator/cluster-role.yaml
  jsonnet/prometheus-operator.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#871 pkg/manifests: update containers consistently
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, lgtm

#852 Bug 1818806: jsonnet/*: adapt resource requests
  assets/alertmanager/alertmanager.yaml
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/openshift-state-metrics/deployment.yaml
  assets/prometheus-adapter/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator/deployment.yaml
  assets/telemeter-client/deployment.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/grafana.jsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/kube-state-metrics.jsonnet
  jsonnet/node-exporter.jsonnet
  jsonnet/prometheus-adapter.jsonnet
  jsonnet/prometheus-operator.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#876 test/e2e: wait until the token for e2e tests is ready
  test/e2e/framework/framework.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, lgtm

#877 BUG 1856719: manifests/telemetry: replace apiserver_request_count with apiserver_r…
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  Documentation/timeseries.txt
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#872 Bug 1859156: set listenLocal for Thanos ruler
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#884 pkg/operator: add informer on configmap in user-workload namespace
  pkg/client/client.go
  pkg/operator/operator.go
Labels: approved, lgtm

#875 Bug 1852846: pkg/manifests/manifests.go: Set logLevel for prometheus Operator
  pkg/manifests/manifests.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#881 Bump component versions
  assets/alertmanager/alertmanager.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/openshift-state-metrics/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/telemeter-client/deployment.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/main.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm

#880 BUG 1856767: manifests/telemetry: replace apiserver_request_count with apiserver_r…
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  Documentation/timeseries.txt
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#878 Bug 1853253: remove expired TLS secret for Thanos Ruler
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#883 readme: add contributing section
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm

#857 Bug 1857248: changing KubeQuotaExceeded to KubeQuotaFullyUsed
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#839 pkg/manifests/manifests.go: Fix setting retention
  pkg/manifests/config.go
  pkg/manifests/manifests.go
Labels: approved, lgtm
