Repository openshift/cluster-monitoring-operator, pull requests merged in 2020-11, with the labels that each got.

#976 Bug 1885244: fix cluster role for prometheus operator
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/prometheus-rule-validating-webhook.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml
  pkg/client/status_reporter.go
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#958 Fix admission reviews versions
  assets/prometheus-operator/prometheus-rule-validating-webhook.yaml
  jsonnet/prometheus-operator.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm

#977 Bug 1878772: jsonnet/thanos-querier: exec probes, use correct endpoint for readiness
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#974 jsonnet/prometheus-operator-user-workload.jsonnet: Remove as per TODO
  assets/prometheus-operator-user-workload/cluster-role.yaml
  jsonnet/prometheus-operator-user-workload.jsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#978 Bug 1892585: Client go 0.18.9
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#982 Add IBM Cloud managed annotations to CVO manifests
  Documentation/data-collection.md
  assets/grafana/dashboard-definitions.yaml
  hack/cluster-monitoring-operator-role.yaml.in
  jsonnet/add-release-annotation.libsonnet
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_01-namespace.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_50_cluster-monitoring-operator_03-role-binding.yaml
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
  manifests/0000_50_cluster-monitoring-operator_06-clusteroperator.yaml
  manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#971 enable hwmon for sensor collection for bare metal clusters
  CHANGELOG.md
  assets/node-exporter/daemonset.yaml
  jsonnet/node-exporter.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm

#979 test/rules: remove commented lines
  test/rules/bz1882730.yaml
Labels: approved, lgtm

#983 Remove deprecated user workload configuration
  CHANGELOG.md
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/configsharing.go
  test/e2e/config_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, lgtm

#984 pkg/operator/operator.go: Adjust log format of resyncPeriod
  pkg/operator/operator.go
Labels: approved, lgtm

#981 Bug 1868976: jsonnet: configure SCCs
  assets/alertmanager/alertmanager.yaml
  assets/alertmanager/cluster-role.yaml
  assets/prometheus-k8s/cluster-role.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/cluster-role.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/cluster-role.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-ruler.jsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/manifests/bindata.go
  test/e2e/alertmanager_test.go
  test/e2e/prometheus_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#987 Create pod priority class for user workload monitoring
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/thanos-ruler.jsonnet
  manifests/0000_50_cluster-monitoring-operator_00_0user-priority-class.yaml
  pkg/manifests/bindata.go
  test/e2e/framework/framework.go
  test/e2e/priority_class_test.go
Labels: approved, lgtm

#990 Bug 1900988: jsonnet: configure SCCs
  assets/alertmanager/alertmanager.yaml
  assets/alertmanager/cluster-role.yaml
  assets/prometheus-k8s/cluster-role.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/cluster-role.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/cluster-role.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-ruler.jsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/manifests/bindata.go
  test/e2e/alertmanager_test.go
  test/e2e/prometheus_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#995 Bug 1897252: Add Thanos query log level
  CHANGELOG.md
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
