Repository openshift/cluster-monitoring-operator, pull requests merged in 2020-08, with the labels that each got.

#894 Bump jsonnet
  CHANGELOG.md
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/cluster-role-binding.yaml
  assets/kube-state-metrics/cluster-role.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/kube-state-metrics/service-account.yaml
  assets/kube-state-metrics/service.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-k8s/service-monitor-kubelet.yaml
  assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/prometheus-adapter.jsonnet
  jsonnet/thanos-querier.jsonnet
  jsonnet/thanos-ruler.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#898 Bug 1846805: Remove kube-mixin direct dependancy
  CHANGELOG.md
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster_monitoring_operator_01-dashboards.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#889 Bug 1862996 : Add OLM Dependency Resolution Metric
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
Labels: approved, lgtm

#899 Bug 1857192: test/e2e: don't count central grpc-tls
  test/e2e/user_workload_monitoring_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#888 Bug 1857229: do not deploy leaf rules redundantly
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
  test/e2e/framework/client.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#887 Bug 1862896: Fix CamelCase to snake-case conversion
  assets/telemeter-client/serving-certs-ca-bundle.yaml
  hack/build-jsonnet.sh
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#900 Bug 1858198: Adjust kube-rbac-proxy cipher suites
  assets/alertmanager/alertmanager.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/openshift-state-metrics/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/telemeter-client/deployment.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm

#895 Bug 1862896: add requirements section and generate-in-docker target
  CONTRIBUTING.md
  Makefile
  go.mod
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#903 Bug 1867510: fix CVP issues due to incorrect labels set
  Dockerfile
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#892 Added rules and telemeter query for storage provisioners usage metrics
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#904 Bug 1858198: manifests: fix ciphers for CMO kube-rbac-proxy
  manifests/0000_50_cluster_monitoring_operator_05-deployment.yaml
Labels: approved, lgtm

#905 Bug 1866469: Adjust the prometheus-operator list and watch alerts
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#906 Adding more detailed user login output
  hack/uwm_setup.sh
Labels: approved, lgtm

#908 Bug 1854479: enforce permissions on Thanos querier endpoints
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#909 Bug 1868304: remove ValidatingWebhookConfiguration for downgrades
  hack/cluster-monitoring-operator-role.yaml.in
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/client/client.go
  pkg/tasks/prometheusoperator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#912 Bug 1870111: log warning when 'techPreviewUserWorkload' is enabled
  pkg/operator/operator.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#907 Bug 1819097: Removing 'Developer Preview' references from telemetry doc
  Documentation/data-collection.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#913 Bug 1860889: decrease CMO log verbosity from 3 to 2
  OWNERS
  cmd/operator/main.go
  manifests/0000_50_cluster_monitoring_operator_05-deployment.yaml
  pkg/client/client.go
  pkg/tasks/tasks.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#915 Bug 1871855: jsonnet/prometheus-operator-user-workload: omit kubelet-service argument
  assets/prometheus-operator-user-workload/deployment.yaml
  jsonnet/prometheus-operator-user-workload.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#910 Bug 1872309: Rename "cluster_monitoring_operator" -> "cluster-monitoring-operator"
  Documentation/data-collection.md
  Makefile
  README.md
  hack/build-jsonnet.sh
  hack/local-cmo.sh
  hack/telemeter_query.go
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_01-namespace.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_50_cluster-monitoring-operator_03-role-binding.yaml
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
  manifests/0000_50_cluster-monitoring-operator_06-clusteroperator.yaml
  manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
