Repository openshift/cluster-monitoring-operator, pull requests merged in 2020-05, with the labels that each got.

#692 [release-4.3] Bug 1807141: jsonnet/rules.jsonnet: Add MultipleContainersOOMKilled alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#777 Bug 1829974: wait for grafana datasource secret
  pkg/tasks/prometheus.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#778 Bug 1822097: pkg/client: delete and create clusterrolebindings instead of updating
  pkg/client/client.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#779 Bug 1829974: pkg/tasks: remove grafana secret from thanos ruler
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#769 Bug 1813221: set remaining cpu requests
  Makefile
  assets/openshift-state-metrics/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#781 Bug 1829244: update kubernetes-mixin to latest release-0.4 branch
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#785 Bug 1812006: avoid "many-to-many matching not allowed" errors
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#783 CHANGELOG.md,.github/: Add CHANGELOG process for monitoring stack
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: approved, bugzilla/valid-bug, lgtm

#784 Remove thanos ruler CRD
  assets/prometheus-operator-user-workload/0thanosruler-custom-resource-definition.yaml
  jsonnet/prometheus-operator-user-workload.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#773 Bug 1828702: wait for trusted CA bundle to be created
  pkg/manifests/manifests.go
  pkg/tasks/alertmanager.go
  pkg/tasks/grafana.go
  pkg/tasks/helpers.go
  pkg/tasks/prometheus.go
  pkg/tasks/telemeter.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/alertmanager_test.go
  test/e2e/thanos_querier_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#694 Bug 1812382: Enable discovery of Podmonitors Custom Resource across namespaces
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/L

#770 cmd/operator: add /debug/pprof/ endpoints
  cmd/operator/main.go
Labels: approved, bugzilla/valid-bug, lgtm

#763 Use Alertmanager's API v2 for Thanos ruler
  assets/thanos-ruler/alertmanagers-config-secret.yaml
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#788 Send data via telemetry for monitoring team
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#782 Bug 1821666: pkg/tasks: thanos ruler cleanup
  pkg/client/client.go
  pkg/tasks/helpers.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#789 jsonnet/kube-state-metrics.jsonnet: Increase scrape interval
  assets/kube-state-metrics/service-monitor.yaml
  jsonnet/kube-state-metrics.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#791 Bug 1832819: bump kubernetes-monitoring/kubernetes-mixin
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#714 prometheus rule validating webhook
  CHANGELOG.md
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/operator-certs-ca-bundle.yaml
  assets/prometheus-operator/prometheus-rule-validating-webhook.yaml
  assets/prometheus-operator/service.yaml
  go.mod
  hack/cluster-monitoring-operator-role.yaml.in
  jsonnet/prometheus-operator.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/tasks/prometheusoperator.go
  test/e2e/framework/framework.go
  test/e2e/validatingwebhook_test.go
Labels: approved, bugzilla/valid-bug, lgtm
