Repository openshift/cluster-monitoring-operator, pull requests merged in 2020-03, with the labels that each got.

#674 Bug 1804455: Better memory calculations
  Makefile
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/invalid-bug, size/M

#688 Adjust resource requests
  assets/node-exporter/daemonset.yaml
  assets/prometheus-adapter/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/node-exporter.jsonnet
  jsonnet/prometheus-adapter.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#684 [release 4.4] Bug 1807843: Fix more many to many errors
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#690 Bug 1807139: jsonnet/rules.jsonnet: Lower threshold for MultipleContainersOOMKilled alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#676 Bug 1807140: jsonnet/rules.jsonnet: Add MultipleContainersOOMKilled alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#683 Bug 1803957: Backport trusted ca support for prometheus
  assets/prometheus-k8s/trusted-ca-bundle.yaml
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheus.go
  test/e2e/prometheus_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#646 Bug 1799540: Node exporter init collectors must be privileged
  assets/node-exporter/daemonset.yaml
  assets/node-exporter/security-context-constraints.yaml
  jsonnet/node-exporter.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#691 Bug 1810424: jsonnet/jsonnetfile.json: Pin kubernetes-mixin to master
  assets/grafana/dashboard-definitions.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/kube-state-metrics.jsonnet
  manifests/0000_90_cluster_monitoring_operator_01-dashboards.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#632 Bug 1746716: grafana: Set default admin user to impossible openshift user
  .travis.yml
  Makefile
  assets/alertmanager/secret.yaml
  assets/grafana/config.yaml
  assets/prometheus-k8s/kube-rbac-proxy-secret.yaml
  hack/shellcheck.sh
  jsonnet/grafana.jsonnet
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#669 Bug 1772564: Bring in new alert via dependency
  assets/prometheus-k8s/rules.yaml
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#664 Bug 1805116: Use aggregated up metrics
  assets/prometheus-k8s/rules.yaml
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#667 Bug 1805317: pkg/manifests/telemeter: bump size limit to 5mb
  pkg/manifests/manifests.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#614 Bug 1791211: Add alert for no routes configured in alertmanager
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#673 Pin dependencies to master not the release branches
  assets/alertmanager/alertmanager.yaml
  assets/alertmanager/secret.yaml
  assets/grafana/dashboard-sources.yaml
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/cluster-role-binding.yaml
  assets/kube-state-metrics/cluster-role.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/kube-state-metrics/role-binding.yaml
  assets/kube-state-metrics/role.yaml
  assets/kube-state-metrics/service-account.yaml
  assets/kube-state-metrics/service-monitor.yaml
  assets/kube-state-metrics/service.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator-user-workload/0thanosruler-custom-resource-definition.yaml
  assets/prometheus-operator/0thanosruler-custom-resource-definition.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/kube-state-metrics.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, lgtm, size/XL

#681 Bug 1807775: Backport setting resource requests
  assets/alertmanager/alertmanager.yaml
  assets/grafana/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/grafana.jsonnet
  jsonnet/node-exporter.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#679 Add thanos ruler deployment
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/thanos-ruler/cluster-role-binding.yaml
  assets/thanos-ruler/cluster-role.yaml
  assets/thanos-ruler/grpc-tls-secret.yaml
  assets/thanos-ruler/kube-rbac-proxy-secret.yaml
  assets/thanos-ruler/oauth-cookie-secret.yaml
  assets/thanos-ruler/oauth-htpasswd-secret.yaml
  assets/thanos-ruler/route.yaml
  assets/thanos-ruler/service-account.yaml
  assets/thanos-ruler/service-monitor.yaml
  assets/thanos-ruler/service.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  assets/thanos-ruler/trusted-ca-bundle.yaml
  jsonnet/main.jsonnet
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/thanos-ruler.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/operator/operator.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, lgtm, size/XXL

#686 Expose CMO metrics over TLS
  assets/cluster-monitoring-operator/service-monitor.yaml
  assets/cluster-monitoring-operator/service.yaml
  jsonnet/cluster-monitoring-operator.jsonnet
  manifests/0000_50_cluster_monitoring_operator_05-deployment.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/M

#695 expose /metrics only on localhost
  cmd/operator/main.go
Labels: approved, lgtm, size/XS

#696 Connect thanos ruler with thanos querier
  assets/prometheus-operator-user-workload/0thanosruler-custom-resource-definition.yaml
  assets/prometheus-operator/0thanosruler-custom-resource-definition.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  go.mod
  go.sum
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/thanos-querier.jsonnet
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/tls.go
  pkg/tasks/thanos_ruler_user_workload.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/bindata.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/statefulset.go
  vendor/github.com/coreos/prometheus-operator/pkg/thanos/operator.go
  vendor/github.com/coreos/prometheus-operator/pkg/thanos/statefulset.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#702 Bug 1812565: Remove cpu limits for config reloader
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-operator.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#699 Bug 1812719: jsonnet/*: adapt resource requests
  assets/alertmanager/alertmanager.yaml
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-adapter/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator/deployment.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/grafana.jsonnet
  jsonnet/kube-state-metrics.jsonnet
  jsonnet/node-exporter.jsonnet
  jsonnet/prometheus-adapter.jsonnet
  jsonnet/prometheus-operator.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-querier.jsonnet
  manifests/0000_50_cluster_monitoring_operator_05-deployment.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#707 Remove thanos ruler CRD
  assets/prometheus-operator/0thanosruler-custom-resource-definition.yaml
  jsonnet/prometheus-operator.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XXL

#708 pkg: Remove thanos ruler server TLS cert
  pkg/manifests/tls.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: approved, lgtm, size/S

#703 Update jsonnet bundler v0.3.1
  go.mod
  go.sum
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/init.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/install.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/rewrite.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/update.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/git.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/jsonnetfile/jsonnetfile.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/local.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/pkg/packages.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/spec/v0/spec.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/spec/v1/deps/dependencies.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/spec/v1/deps/git.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/spec/v1/spec.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/spec/v1/v0.go
  vendor/github.com/jsonnet-bundler/jsonnet-bundler/tool/rewrite/rewrite.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#700 Cleanup thanos ruler
  assets/thanos-ruler/kube-rbac-proxy-secret.yaml
  assets/thanos-ruler/service-monitor.yaml
  assets/thanos-ruler/service.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: approved, lgtm, size/L

#709 Bug 1812834: schedule Thanos Querier on worker nodes, make resources configurable
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#705 Bug 1809353: Exclude Kubernetes control plane rules when running on IBM Cloud
  pkg/client/client.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#716 Bug 1809353: Add infrastructures.config.openshift.io to cluster-monitoring-operator role
  hack/cluster-monitoring-operator-role.yaml.in
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#711 Bug 1812719: address missing resource requests
  assets/prometheus-k8s/prometheus.yaml
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#712 [release-4.4] Bug 1814729: Exclude Kubernetes control plane rules when running on IBM Cloud
  hack/cluster-monitoring-operator-role.yaml.in
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/client/client.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#720 update prometheus-operator to v0.38.0
  assets/prometheus-adapter/config-map.yaml
  assets/prometheus-operator-user-workload/0thanosruler-custom-resource-definition.yaml
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm

#612 Bug 1791194: Removing KubeVersionMismatch alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#719 Bug 1803957: Specify grafana-proxy container by name
  assets/grafana/dashboard-definitions.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#724 hack/merge_cluster_roles.py: fix deprecation warnings
  hack/merge_cluster_roles.py
Labels: approved, lgtm

#717 Configure thanos ruler configurations for query and alertmanager
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/alertmanagers-config-secret.yaml
  assets/thanos-ruler/cluster-role-binding-monitoring.yaml
  assets/thanos-ruler/query-config-secret.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  go.mod
  go.sum
  jsonnet/prometheus-operator.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/user_workload_monitoring_test.go
  vendor/github.com/coreos/prometheus-operator/pkg/alertmanager/statefulset.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/bindata.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/coreos/prometheus-operator/pkg/operator/defaults.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/promcfg.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/statefulset.go
  vendor/github.com/coreos/prometheus-operator/pkg/thanos/operator.go
  vendor/github.com/coreos/prometheus-operator/pkg/thanos/statefulset.go
  vendor/github.com/coreos/prometheus-operator/pkg/version/version.go
  vendor/github.com/coreos/prometheus-operator/test/framework/prometheus.go
  vendor/modules.txt
Labels: approved, lgtm

#726 Bug 1817938: Do not report 'all' in relatedObjects
  pkg/client/status_reporter.go
Labels: approved, bugzilla/valid-bug, lgtm

#722 Bug 1811834: Sync jsonnet dependencies
  assets/grafana/dashboard-definitions.yaml
  assets/node-exporter/daemonset.yaml
  assets/node-exporter/service-monitor.yaml
  assets/node-exporter/service.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-operator.jsonnet
  manifests/0000_90_cluster_monitoring_operator_01-dashboards.yaml
  pkg/client/client.go
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
Labels: approved, bugzilla/valid-bug, lgtm

#701 Add kube-rbac-proxy and prom-label-proxy to Alertmanager
  assets/alertmanager/alertmanager.yaml
  assets/alertmanager/kube-rbac-proxy-secret.yaml
  assets/alertmanager/service.yaml
  assets/cluster-monitoring-operator/monitoring-rules-edit-cluster-role.yaml
  assets/cluster-monitoring-operator/monitoring-rules-view-cluster-role.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/cluster-monitoring-operator.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/operator/operator.go
  pkg/tasks/alertmanager.go
  pkg/tasks/clustermonitoringoperator.go
  test/e2e/alertmanager_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/route_client.go
Labels: approved, lgtm, size/L

#727 Bug 1817597: Fix alert duplicates
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm
