Repository openshift/cluster-monitoring-operator, pull requests merged in 2020-10, with the labels that each got.

#948 pkg/operator: fix log msg about reconciliation interval
  pkg/operator/operator.go
Labels: approved, lgtm

#951 jsonnet: Collect all resource counts for telemetry
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm

#950 Updating cluster-monitoring-operator builder & base images to be consistent with ART
  Dockerfile
Labels: approved, lgtm

#942 Bug 1879930: Preserve labels and annotations during reconciliation
  pkg/client/client.go
  pkg/client/client_test.go
  test/e2e/multi_namespace_test.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/fake/clientset_generated.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/fake/doc.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/fake/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/fake/doc.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/fake/fake_alertmanager.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/fake/fake_monitoring_client.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/fake/fake_podmonitor.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/fake/fake_prometheus.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/fake/fake_prometheusrule.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/fake/fake_servicemonitor.go
  vendor/github.com/coreos/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/fake/fake_thanosruler.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/fake/fake_securitycontextconstraints.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#924 update go-jsonnet to faster version
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm

#957 jsonnet: Cap total resources:sum series
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm

#962 Bug 1812085: restore pod networking dashboards
  CHANGELOG.md
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  jsonnet/main.jsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#947 Allowlist cco_credentials_mode metric from cloud credential operator.
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: approved, lgtm

#963 Bug 1890808: bump mixins to include new etcd alerts
  CHANGELOG.md
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#968 Bug 1885246: pkg/*: use k8s.io/klog/v2
  cmd/operator/main.go
  go.mod
  go.sum
  pkg/client/client.go
  pkg/manifests/tls.go
  pkg/operator/operator.go
  pkg/tasks/clustermonitoringoperator.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/tasks.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_authentication.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_oauth.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#967 add current profile annotations to CVO manifests
  Documentation/data-collection.md
  assets/grafana/dashboard-definitions.yaml
  hack/cluster-monitoring-operator-role.yaml.in
  jsonnet/add-release-annotation.libsonnet
  jsonnet/main.jsonnet
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_01-namespace.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_50_cluster-monitoring-operator_03-role-binding.yaml
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
  manifests/0000_50_cluster-monitoring-operator_06-clusteroperator.yaml
  manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#953 Bug 1882730: fix cluster:cpu_core_hyperthreading rule for s390x
  Makefile
  assets/prometheus-k8s/rules.yaml
  hack/build-jsonnet.sh
  hack/test-rules.sh
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
  test/rules/README.md
  test/rules/bz1882730.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#972 OWNERS: add dgrisonnet
  OWNERS
Labels: approved, lgtm

#960 jsonnet/jsonnetfile.json: Switch to master
  CONTRIBUTING.md
  Makefile
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/cluster-role-binding.yaml
  assets/kube-state-metrics/cluster-role.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/kube-state-metrics/service-account.yaml
  assets/kube-state-metrics/service-monitor.yaml
  assets/kube-state-metrics/service.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/role-specific-namespaces.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-k8s/service-monitor-kubelet.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/prometheus-user-workload/role-specific-namespaces.yaml
  hack/merge_cluster_roles.go
  hack/merge_cluster_roles.py
  jsonnet/cmo.jsonnet
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#969 Bug 1883765: Bump Thanos v0.16.0
  CHANGELOG.md
  assets/thanos-querier/prometheus-rule.yaml
  assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#973 make role manifest sort stable
  Makefile
  hack/merge_cluster_roles.py
Labels: approved, lgtm

#970 Bug 1885244: bump prometheus operator to v0.43.0
  CHANGELOG.md
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/prometheus-operator-user-workload.jsonnet
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  pkg/manifests/bindata.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#961 Bug 1888542: decrease CMO log verbosity from 3 to 2
  OWNERS
  cmd/operator/main.go
  manifests/0000_50_cluster_monitoring_operator_05-deployment.yaml
  pkg/client/client.go
  pkg/tasks/tasks.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#952 Bug 1858010: Backport fix for KubePodCrashLooping alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm
