Repository openshift/cluster-monitoring-operator, pull requests merged in 2020-02, with the labels that each got.

#640 BUG 1796927: Documentation: Transfer telemetry comments
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  Documentation/timeseries.txt
  Makefile
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XL

#643 Bug 1799057: Send apiserver_current_inflight_requests in telemeter.
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#644 Bug 1794934: Bump kubernetes-mixin to support DASD device metric reporting
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#645 Bug 1799539: Node exporter init collectors must be privileged
  assets/node-exporter/daemonset.yaml
  assets/node-exporter/security-context-constraints.yaml
  jsonnet/node-exporter.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#649 Bug 1800513: assets,jsonnet,pkg: Fix generate check
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#650 Bug 1794616: replace up with count:up[0,1], remove node_uname_info
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#651 Bug 1801358: update prometheus-operator v0.35.1
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  go.mod
  go.sum
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/operator.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#652 Bug 1787520: fix query showing metrics collected by telemetry
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  Makefile
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#654 Bug 1803192: *: duplicate shared configmap in openshift-config-managed namespace
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/configsharing.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#655 Bug 1794616: pkg/manifests: set modified telemeter-client command line arguments
  pkg/manifests/manifests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#653 Bug 1803827: pkg: Generate recording rule to measure total number of series we are
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
  pkg/manifests/manifests.go
  pkg/promqlgen/promqlgen.go
  pkg/promqlgen/promqlgen_test.go
  pkg/tasks/telemeter.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#657 Bug 1804179: pkg/client: set CreationTimestamp at create time, not only at update time
  pkg/client/client.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#630 pkg/manifests: Configure remote write more conservatively
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/S

#619 *: use API v2 of Alertmanager
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  go.sum
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#656 Bug 1804012: Report system manufacturer via telemetry
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#659 Bug 1787520: replace ad-hoc script generating telemeter doc
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  Makefile
  hack/telemeter_query.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#641 rebuild docker image when the operator binary changes
  Makefile
Labels: approved, lgtm, size/XS

#662 update to prometheus-operator-v0.36.0
  assets/prometheus-operator-user-workload/0thanosruler-custom-resource-definition.yaml
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/0thanosruler-custom-resource-definition.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/XXL

#660 pkg/manifests/telemeter: bump size limit to 5mb
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/XS

#666 Merge master-4.5
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  go.sum
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/M

#670 Bug 1802941: fix many-to-many errors
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#658 Bug 1796040: pkg/manifests: change location of trustedCA bundle; add trustedCA to …
  pkg/manifests/manifests.go
  test/e2e/alertmanager_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S

#668 jsonnet/rules.jsonnet: Add MultipleContainersOOMKilled alert
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm, size/S

#671 override prometheus-operator args only when not empty
  pkg/manifests/manifests.go
Labels: approved, lgtm, size/S

#677 Bug 1807100: pkg/manifests: rename shared config's keys to include 'Public'
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#675 Bug 1802941: Fix more many to many errors
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#613 Bug 1791200: Add alert for no routes configured in alertmanager
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S
