Repository openshift/cluster-monitoring-operator, pull requests merged in 2020-04, with the labels that each got.

#730 Bug 1819565: pkg/manifests: set correct server name for UWM prom-op service monitor
  pkg/manifests/manifests.go
Labels: approved, bugzilla/valid-bug, lgtm

#732 test/e2e/framework: remove unused code
  test/e2e/framework/custom_resource_definition.go
  test/e2e/framework/framework.go
Labels: approved, lgtm

#729 Bug 1819612: jsonnet/thanos-querier.jsonnet: Configure thanos querier replica-label
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#731 Bug 1807430: don't sync on invalid configuration
  pkg/client/status_reporter.go
  pkg/operator/operator.go
  test/e2e/config_test.go
  test/e2e/framework/framework.go
Labels: approved, bugzilla/valid-bug, lgtm

#733 thanos-ruler: Add thanos ruler alerts
  assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: approved, lgtm

#728 test: add e2e test for Thanos Querier's kube-rbac-proxy
  test/e2e/alertmanager_test.go
  test/e2e/framework/client.go
  test/e2e/framework/client_test.go
  test/e2e/framework/framework.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, lgtm

#706 Bug 1813221: jsonnet/*: adapt resource requests
  assets/alertmanager/alertmanager.yaml
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-adapter/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator/deployment.yaml
  assets/telemeter-client/deployment.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/grafana.jsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/kube-state-metrics.jsonnet
  jsonnet/node-exporter.jsonnet
  jsonnet/prometheus-adapter.jsonnet
  jsonnet/prometheus-operator.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L, ¯\_(ツ)_/¯

#734 pkg/manifests: remove Hostport from Thanos ruler config
  pkg/manifests/config.go
Labels: approved, lgtm

#744 Bug 1821146: pkg/manifests: remove thanos ruler rbac proxy secret
  pkg/manifests/manifests.go
Labels: approved, bugzilla/valid-bug, lgtm

#739 Bug 1814723: Bump dependencies
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator-user-workload/0thanosruler-custom-resource-definition.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#743 test/e2e: log errors from port forwarding
  test/e2e/alertmanager_test.go
  test/e2e/framework/framework.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, lgtm

#741 Update kube-thanos
  assets/thanos-querier/cluster-role-binding.yaml
  assets/thanos-querier/cluster-role.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-querier/grpc-tls-secret.yaml
  assets/thanos-querier/kube-rbac-proxy-secret.yaml
  assets/thanos-querier/oauth-cookie-secret.yaml
  assets/thanos-querier/oauth-htpasswd-secret.yaml
  assets/thanos-querier/route.yaml
  assets/thanos-querier/service-account.yaml
  assets/thanos-querier/service.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/thanos-querier.jsonnet
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, lgtm

#740 Add Operator Lifecycle Manager (OLM) team
  Documentation/data-collection.md
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
Labels: approved, lgtm

#738 OCM: Add OpenShift Cluster Manager team
  Documentation/data-collection.md
  manifests/0000_50_cluster_monitoring_operator_04-config.yaml
Labels: approved, lgtm

#747 Update tls service annotation
  assets/alertmanager/service.yaml
  assets/cluster-monitoring-operator/service.yaml
  assets/grafana/service.yaml
  assets/kube-state-metrics/service.yaml
  assets/node-exporter/service.yaml
  assets/prometheus-adapter/service.yaml
  assets/prometheus-k8s/service.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/service.yaml
  assets/prometheus-user-workload/service.yaml
  assets/thanos-querier/service.yaml
  assets/thanos-ruler/service.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/cluster-monitoring-operator.jsonnet
  jsonnet/grafana.jsonnet
  jsonnet/kube-state-metrics.jsonnet
  jsonnet/node-exporter.jsonnet
  jsonnet/prometheus-adapter.jsonnet
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-operator.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-querier.jsonnet
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm

#748 pkg/operator/operator.go: Bump resync interval to 15 minutes
  pkg/operator/operator.go
Labels: approved, lgtm

#749 jsonnet: Bump thanos mixin lib
  assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, lgtm

#752 OWNERS: add component
  OWNERS
Labels: approved, lgtm

#751 test/e2e: forward port for every query
  test/e2e/user_workload_monitoring_test.go
Labels: approved, lgtm

#750 Create versions-check.sh
  hack/versions-check.sh
Labels: approved, lgtm

#755 Bug 1812719: jsonnet/alertmanager,openshift-state-metrics: set cpu requests
  assets/alertmanager/alertmanager.yaml
  assets/openshift-state-metrics/deployment.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#754 Add monitoring-edit role
  assets/cluster-monitoring-operator/monitoring-edit-cluster-role.yaml
  jsonnet/cluster-monitoring-operator.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/clustermonitoringoperator.go
Labels: approved, lgtm

#757 .github: remove mention of cutting upstream prometheus-operator release
  .github/ISSUE_TEMPLATE/release.md
Labels: approved, lgtm

#759 Generate alerts for user workload monitoring prometheus
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, lgtm

#760 Pin dependencies for 4.5 release
  assets/kube-state-metrics/cluster-role-binding.yaml
  assets/kube-state-metrics/cluster-role.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/kube-state-metrics/service-account.yaml
  assets/kube-state-metrics/service.yaml
  assets/prometheus-adapter/config-map.yaml
  assets/prometheus-k8s/rules.yaml
  assets/prometheus-operator-user-workload/0thanosruler-custom-resource-definition.yaml
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
Labels: approved, lgtm

#745 Bug 1821268: fix Alertmanager address for Thanos Ruler
  assets/thanos-ruler/alertmanagers-config-secret.yaml
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm

#746 Bug 1819765: fix alert links in Thanos Ruler UI
  go.mod
  go.sum
  pkg/manifests/manifests.go
  pkg/tasks/thanos_ruler_user_workload.go
  vendor/github.com/brancz/gojsontoyaml/main.go
  vendor/github.com/coreos/prometheus-operator/pkg/alertmanager/statefulset.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/bindata.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/coreos/prometheus-operator/pkg/prometheus/rules.go
  vendor/github.com/coreos/prometheus-operator/pkg/thanos/rules.go
  vendor/github.com/coreos/prometheus-operator/pkg/thanos/statefulset.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm

#762 Bug 1821666: cleanup thanos ruler resources
  pkg/client/client.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: approved, bugzilla/low, bugzilla/valid-bug, lgtm

#766 Bug 1827489: pkg/tasks: do not remove GRPC secret as it is used by querier
  pkg/tasks/thanos_ruler_user_workload.go
Labels: approved, bugzilla/high, bugzilla/valid-bug, lgtm

#767 Bug 1827648: fix monitoring-rules-edit and monitoring-edit roles
  assets/cluster-monitoring-operator/monitoring-edit-cluster-role.yaml
  assets/cluster-monitoring-operator/monitoring-rules-edit-cluster-role.yaml
  jsonnet/cluster-monitoring-operator.jsonnet
  manifests/0000_50_cluster_monitoring_operator_02-role.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#765 Bug 1821666: thanos ruler secret cleanup
  Makefile
  pkg/tasks/thanos_ruler_user_workload.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
