Repository openshift/cluster-monitoring-operator, pull requests merged in 2021-07, with the labels that each got.

#1227 Improve monitoring telemetry rules
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
Labels: approved, lgtm

#1259 Revert "Bug 1974830: Update KubeDeploymentReplicasMismatch alert"
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1242 Bug 1974832: Add HighlyAvailableWorkloadIncorrectlySpread alert
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/cluster-monitoring-operator.libsonnet
  jsonnet/main.jsonnet
  jsonnet/remove-runbook-urls.libsonnet
  jsonnet/rules.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1229 Bug 1972076: jsonnet: Disable cpufreq collector in node_exporter
  assets/node-exporter/daemonset.yaml
  jsonnet/node-exporter.libsonnet
Labels: approved, lgtm

#1241 operator: Allow disabling Grafana deployment
  CHANGELOG.md
  assets/prometheus-k8s/prometheus.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/prometheus.libsonnet
  jsonnet/thanos-querier.libsonnet
  pkg/client/client.go
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/operator/operator.go
  pkg/tasks/configsharing.go
  pkg/tasks/grafana.go
  pkg/tasks/prometheus.go
  pkg/tasks/thanos_querier.go
  test/e2e/config_test.go
Labels: approved, lgtm

#1261 Bug 1974830: Update KubeDeploymentReplicasMismatch alert
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
  test/rules/bz1974830.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1267 Bug 1977435: jsonnet: bump prometheus-operator to v0.49.0
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/prometheus-rule.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  jsonnet/versions.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1266 Remove logging from the mixins namespace selectors
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  assets/control-plane/prometheus-rule.yaml
  jsonnet/main.jsonnet
  jsonnet/rules.libsonnet
Labels: approved, lgtm

#1268 Bug 1978829: alert: ClusterMonitoringOperatorReconciliationErrors: reduce range du…
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1269 jsonnet: pull latest deps
  assets/control-plane/prometheus-rule.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-adapter/config-map.yaml
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: approved, lgtm

#1193 Bug 1949840: Improve update and status reporting
  pkg/operator/operator.go
  pkg/tasks/tasks.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1262 Bug 1974832: Improve HighlyAvailableWorkloadIncorrectlySpread to detect single point of failure
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
  test/rules/workload_incorrectly_spread.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1217 Bug 1947005 : changing alert manager access rules
  assets/alertmanager/alertmanager.yaml
  assets/cluster-monitoring-operator/monitoring-alertmanager-edit-role.yaml
  assets/prometheus-k8s/alertmanager-role-binding.yaml
  assets/prometheus-user-workload/alertmanager-role-binding.yaml
  assets/thanos-ruler/alertmanager-role-binding.yaml
  jsonnet/alertmanager.libsonnet
  jsonnet/cluster-monitoring-operator.libsonnet
  jsonnet/prometheus-user-workload.libsonnet
  jsonnet/prometheus.libsonnet
  jsonnet/thanos-ruler.libsonnet
  pkg/manifests/manifests.go
  pkg/tasks/clustermonitoringoperator.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheusoperator_user_workload.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/framework/framework.go
Labels: approved, lgtm

#1274 jsonnet: Enable federated targets in thanos-querier
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.libsonnet
  pkg/manifests/manifests.go
Labels: approved, lgtm

#1275 client: Always set OperatorUpgradeable reason to AsExpected
  pkg/client/status_reporter.go
Labels: approved, lgtm

#1257 Bug 1956308: Fix deployment update with retry option
  pkg/client/client.go
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1278 pkg/manifests: Add EnforcedTargetLimit for user-workload monitoring
  CHANGELOG.md
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, lgtm

#1254 Remove context.TODO() and propagate real context
  cmd/operator/main.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/status_reporter.go
  pkg/client/status_reporter_test.go
  pkg/operator/operator.go
  pkg/tasks/prometheusadapter.go
  test/e2e/framework/framework.go
Labels: approved, lgtm

#1277 BUG 1980888: jsonnet: Favour http probes for thanos querier
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.libsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1273 Cleanup telemetry owners
  Documentation/data-collection.md
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: approved, lgtm

#1284 Fix shellcheck errors
  hack/generate-versions.sh
Labels: approved, lgtm

#1270 Bug 1978662: Set a degraded message when persistent storage is not configured
  CHANGELOG.md
  pkg/client/status_reporter.go
  pkg/client/status_reporter_test.go
  pkg/manifests/config.go
  pkg/operator/operator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1291 jsonnet: Sync with kube-prometheus
  CHANGELOG.md
  assets/control-plane/prometheus-rule.yaml
  assets/control-plane/service-monitor-kubelet.yaml
  assets/grafana/dashboard-definitions.yaml
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: approved, lgtm

#1281 Send etcd telemetry rules
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: approved, lgtm

#1292 No apiserver rules
  assets/control-plane/prometheus-rule.yaml
  jsonnet/patch-rules.libsonnet
Labels: approved, lgtm

#1294 Add new label to show grafana dashboards in ODC
  jsonnet/grafana.libsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: approved, lgtm

#1295 Documentation: fix a typo
  Documentation/cluster-monitoring.md
Labels: approved, lgtm

#1271 Allow configuring additional alertmanagers for UWM Prometheus and Thanos
  CHANGELOG.md
  pkg/manifests/amcfg.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/framework/framework.go
  test/e2e/thanos_ruler_test.go
  test/e2e/user_workload_monitoring_test.go
  vendor/k8s.io/client-go/tools/portforward/doc.go
  vendor/k8s.io/client-go/tools/portforward/portforward.go
  vendor/modules.txt
Labels: approved, lgtm

#1287 Remove manual CRI-O metrics modification
  assets/control-plane/service-monitor-kubelet.yaml
  jsonnet/control-plane.libsonnet
Labels: approved, lgtm

#1296 Bug 1978091: fix node_exporter recording rules for cluster network dashboards
  assets/grafana/dashboard-definitions.yaml
  assets/node-exporter/prometheus-rule.yaml
  jsonnet/main.jsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1290 Remove context field from structs
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/status_reporter.go
  pkg/client/status_reporter_test.go
  pkg/operator/operator.go
  pkg/tasks/alertmanager.go
  pkg/tasks/clustermonitoringoperator.go
  pkg/tasks/configsharing.go
  pkg/tasks/controlplane.go
  pkg/tasks/grafana.go
  pkg/tasks/helpers.go
  pkg/tasks/kubestatemetrics.go
  pkg/tasks/metrics_client_ca.go
  pkg/tasks/nodeexporter.go
  pkg/tasks/openshiftstatemetrics.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/prometheusadapter.go
  pkg/tasks/prometheusoperator.go
  pkg/tasks/prometheusoperator_user_workload.go
  pkg/tasks/tasks.go
  pkg/tasks/telemeter.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/alertmanager_test.go
  test/e2e/config_test.go
  test/e2e/framework/client.go
  test/e2e/framework/framework.go
  test/e2e/main_test.go
  test/e2e/multi_namespace_test.go
  test/e2e/priority_class_test.go
  test/e2e/prometheus_test.go
  test/e2e/prometheusadapter_test.go
  test/e2e/thanos_querier_test.go
  test/e2e/thanos_ruler_test.go
  test/e2e/user_workload_monitoring_test.go
  test/e2e/validatingwebhook_test.go
Labels: approved, lgtm

#1207 Bug 1969964: Recording rule for builds by strategy
  CHANGELOG.md
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#1297 Bug 1973576: Bump thanos to v0.22.0
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-querier/cluster-role-binding.yaml
  assets/thanos-querier/cluster-role.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-querier/grpc-tls-secret.yaml
  assets/thanos-querier/kube-rbac-proxy-rules-secret.yaml
  assets/thanos-querier/kube-rbac-proxy-secret.yaml
  assets/thanos-querier/oauth-cookie-secret.yaml
  assets/thanos-querier/oauth-htpasswd-secret.yaml
  assets/thanos-querier/pod-disruption-budget.yaml
  assets/thanos-querier/prometheus-rule.yaml
  assets/thanos-querier/route.yaml
  assets/thanos-querier/service-account.yaml
  assets/thanos-querier/service-monitor.yaml
  assets/thanos-querier/service.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/versions.json
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1279 Bug 1986375: adding check for node exporter daemon set
  pkg/client/client.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1209 Bug 1986840: track number of active alertmanager receivers via telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1300 [release-4.7] Bug 1986591: node exporter calls /proc/cpuinfo multiple times causing the node to freeze
  assets/node-exporter/daemonset.yaml
  jsonnet/node-exporter.jsonnet
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1265 Bug 1943565: ThanosSidecarUnhealthy will never fire if the sidecar is never healthy
  assets/prometheus-k8s/prometheus-rule.yaml
  jsonnet/patch-rules.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1276 Bug 1981246: [4.8]: Add HighlyAvailableWorkloadIncorrectlySpread alert
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/cluster-monitoring-operator.libsonnet
  jsonnet/main.jsonnet
  jsonnet/remove-runbook-urls.libsonnet
  jsonnet/rules.libsonnet
  test/rules/workload_incorrectly_spread.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1303 Bug 1987143: Update prometheus resources label to 2.28.1
  assets/prometheus-k8s/cluster-role-binding.yaml
  assets/prometheus-k8s/cluster-role.yaml
  assets/prometheus-k8s/prometheus-rule.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/role-binding-config.yaml
  assets/prometheus-k8s/role-binding-specific-namespaces.yaml
  assets/prometheus-k8s/role-config.yaml
  assets/prometheus-k8s/role-specific-namespaces.yaml
  assets/prometheus-k8s/service-account.yaml
  assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
  assets/prometheus-k8s/service-monitor.yaml
  assets/prometheus-k8s/service-thanos-sidecar.yaml
  assets/prometheus-k8s/service.yaml
  assets/prometheus-user-workload/cluster-role-binding.yaml
  assets/prometheus-user-workload/cluster-role.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/prometheus-user-workload/role-binding-config.yaml
  assets/prometheus-user-workload/role-binding-specific-namespaces.yaml
  assets/prometheus-user-workload/role-config.yaml
  assets/prometheus-user-workload/role-specific-namespaces.yaml
  assets/prometheus-user-workload/service-account.yaml
  assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
  assets/prometheus-user-workload/service-monitor.yaml
  assets/prometheus-user-workload/service-thanos-sidecar.yaml
  assets/prometheus-user-workload/service.yaml
  jsonnet/versions.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1302 Bug 1973491: jsonnet: update deps
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  assets/control-plane/prometheus-rule.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/node-exporter/daemonset.yaml
  assets/node-exporter/prometheus-rule.yaml
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1307 Bug 1988291: pkg/client/client.go: Add retry logic for daemonset create
  pkg/client/client.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
