Repository openshift/cluster-monitoring-operator, pull requests merged in 2021-02, with the labels that each got.

#1029 Bug 1913006: Removing etcd v2 specific alerts
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1046 Bug 1913386: allow only /metrics for kube-rbac-proxy in front of UWM prometheu
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/prometheus-user-workload.jsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1031 docs(data-collection): add newlines for visibility
  Documentation/data-collection.md
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: approved, lgtm

#1047 Bug 1920901: pkg/manifests: fix prometheus-proxy trustedCA
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1063 Bug 1929277: [master] jsonnet/prometheus.jsonnet: Apply openshift-user-critical class to cluster Prometheus
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/prometheus.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1062 Bug 1929278: [4.7]: jsonnet/prometheus.jsonnet: Apply openshift-user-critical class to cluster Prometheus
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/prometheus.jsonnet
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, group-lead-approved, lgtm

#1064 Bug 1929944: etcdInsufficientMembers is wrong when etcd is in a pod
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  jsonnet/rules.jsonnet
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1065 jsonnet/rules: Mask KubeDeploymentReplicasMismatch alert for upgrade
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  jsonnet/rules.jsonnet
Labels: approved, lgtm

#1054 pkg/manifests: fix data race when accessing assets
  pkg/manifests/assets.go
Labels: approved, lgtm

#1068 Bug 1929056: Remove kube-apiserver-availability.rules
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
