Repository openshift/cluster-monitoring-operator, pull requests merged in 2021-11, with the labels that each got.

#1461 Bug 2018455: Keep container_fs_usage_bytes metric
  assets/control-plane/service-monitor-kubelet.yaml
  jsonnet/components/control-plane.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#1454 pkg: add tlsSecurityProfile to kube-rbac-proxy in KSM
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/kubestatemetrics.go
  test/e2e/tls_security_profile_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1439 Bug 2015386: jsonnet: Add PodDisruptionBudget to KSM metric allow list
  CHANGELOG.md
  assets/kube-state-metrics/deployment.yaml
  jsonnet/components/kube-state-metrics.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1464 pkg: add tlsSecurityProfile to kube-rbac-proxy in OSM
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/e2e/tls_security_profile_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1465 run-local: harden -images switch retrieval
  hack/local-cmo.sh
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1459 Bug 2018431: [4.8] add kube_persistentvolumeclaim_labels and kube_persistentvolume_labels
  assets/kube-state-metrics/deployment.yaml
  jsonnet/kube-state-metrics.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#1466 pkg: add tlsSecurityProfile to kube-rbac-proxy in prometheus-operator
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1470 pkg: add tlsSecurityProfile to kube-rbac-proxy in node-exporter
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/e2e/tls_security_profile_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1377 [MON-1786] Enable audit logs by default for Prometheus Adapter
  CHANGELOG.md
  Makefile
  assets/prometheus-adapter/configmap-audit-profiles.yaml
  assets/prometheus-adapter/deployment.yaml
  jsonnet/components/prometheus-adapter-audit.libsonnet
  jsonnet/main.jsonnet
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheusadapter.go
  vendor/k8s.io/apiserver/pkg/apis/audit/OWNERS
  vendor/k8s.io/apiserver/pkg/apis/audit/doc.go
  vendor/k8s.io/apiserver/pkg/apis/audit/helpers.go
  vendor/k8s.io/apiserver/pkg/apis/audit/register.go
  vendor/k8s.io/apiserver/pkg/apis/audit/types.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/doc.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/generated.pb.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/generated.proto
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/register.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/types.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/zz_generated.conversion.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/zz_generated.defaults.go
  vendor/k8s.io/apiserver/pkg/apis/audit/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1455 Bug 2019992: Bump jsonnet dependencies to latest
  assets/alertmanager/alertmanager.yaml
  assets/alertmanager/service-monitor.yaml
  assets/control-plane/prometheus-rule.yaml
  assets/control-plane/service-monitor-kubelet.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/deployment.yaml
  assets/grafana/service-account.yaml
  assets/node-exporter/cluster-role-binding.yaml
  assets/node-exporter/cluster-role.yaml
  assets/node-exporter/daemonset.yaml
  assets/node-exporter/prometheus-rule.yaml
  assets/prometheus-adapter/cluster-role-aggregated-metrics-reader.yaml
  assets/prometheus-adapter/cluster-role-binding-delegator.yaml
  assets/prometheus-adapter/cluster-role-binding.yaml
  assets/prometheus-adapter/cluster-role-server-resources.yaml
  assets/prometheus-adapter/cluster-role.yaml
  assets/prometheus-k8s/cluster-role-binding.yaml
  assets/prometheus-k8s/cluster-role.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/cluster-role-binding.yaml
  assets/prometheus-user-workload/cluster-role.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/telemeter-client/serving-certs-ca-bundle.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/utils/sanitize-rules.libsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
  pkg/manifests/manifests.go
  pkg/tasks/alertmanager.go
  test/e2e/alertmanager_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low, qe-approved

#1474 pkg: Implements tlsSecurityProfile to remaining components using kube-rbac-proxy
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/e2e/tls_security_profile_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1481 Bug 2016435: Removing one of the AlertmanagerClusterFailedToSendAlerts alerts
  CHANGELOG.md
  assets/alertmanager/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1482 Update make target name for Documentation/telemetry/telemeter_query
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  Makefile
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1479 Fix TestUserWorkloadMonitoringAlerting for Prometheus Operator v0.52
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1480 test/e2e: fix assertTenancyForLabels test
  test/e2e/alertmanager_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1483 MON-1659: adding relatedObjects to cluster operator manifest
  manifests/0000_50_cluster-monitoring-operator_06-clusteroperator.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1484 Add metrics for Node Tuning Operator to telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1341 Bug 1933847: enable hard affinity + PodDisruptionBudget for Prometheus and Thanos Ruler pods
  assets/prometheus-k8s/pod-disruption-budget.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/pod-disruption-budget.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/pod-disruption-budget.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/components/thanos-ruler.libsonnet
  jsonnet/utils/anti-affinity.libsonnet
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/prometheus_test.go
  test/e2e/rebalance_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#1478 MON-1872: Use kube-thanos jsonnet libs for thanos ruler
  assets/thanos-ruler/service-account.yaml
  assets/thanos-ruler/service-monitor.yaml
  assets/thanos-ruler/service.yaml
  jsonnet/components/thanos-ruler.libsonnet
  jsonnet/main.jsonnet
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1487 Update list of metrics used by openshift-team-cluster-manager
  Documentation/data-collection.md
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1373 Support enabling the `query_log_file` config for Prometheus
  CHANGELOG.md
  Documentation/user-guides/configuring-cluster-monitoring.md
  examples/user-workload/README.md
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/e2e/config_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1492 MON-1656: adding new target to makefile for verification
  Makefile
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1494 pkg/operator: move config sharing task at the end
  pkg/operator/operator.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1495 Bug 1953264: client: don't update resource fields that are managed externally
  pkg/client/client.go
  pkg/client/client_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1490 [MON-1786] Document Prometheus Adapter audit log configuration
  pkg/manifests/config.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1496 client: check all OwnerRefs on a service
  pkg/client/client.go
  pkg/client/client_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1498 hack/local-cmo.sh: fix CVO override
  hack/local-cmo.sh
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
