Repository openshift/cluster-monitoring-operator, pull requests merged in 2021-05, with the labels that each got.

#1133 Bug 1955445: fix dropped crio metrics
  assets/control-plane/service-monitor-kubelet.yaml
  jsonnet/control-plane.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1120 Bug 1940933: Revert "jsonnet: make AggregatedAPIDown more resilient"
  CHANGELOG.md
  assets/control-plane/prometheus-rule.yaml
  jsonnet/patch-rules.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1139 Bug 1955467: remove node_mountstats_nfs_* metrics
  assets/node-exporter/daemonset.yaml
  jsonnet/node-exporter.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1140 Bug 1955051: Update kube node status capacity metric
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1142 Bug 1955478: drop high-cardinality metrics from kube-state-metrics which aren't used
  assets/kube-state-metrics/deployment.yaml
  jsonnet/main.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1145 Bug 1950908: Allow all pod labels in metric labels
  assets/kube-state-metrics/deployment.yaml
  jsonnet/kube-state-metrics.libsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1143 Bug 1957832: remove dependency of e2e tests on AWS
  test/e2e/alertmanager_test.go
  test/e2e/prometheus_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1148 Bug 1955445: drop more CRI-O metrics
  assets/control-plane/service-monitor-kubelet.yaml
  jsonnet/control-plane.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1152 Bug 1958015: jsonnet: fix setting resource limits on config-reloader containers
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  jsonnet/prometheus-operator-user-workload.libsonnet
  jsonnet/prometheus-operator.libsonnet
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1149 Bug 1953647: Add prometheus-adapter PodDisruptionBudget
  assets/prometheus-adapter/pod-disruption-budget.yaml
  hack/cluster-monitoring-operator-role.yaml.in
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/client/client.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheusadapter.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1157 [release-3.11]: Fix make generate
  Makefile
Labels: approved, lgtm

#1134 [4.7] Bug 1955449: drop crio image metrics
  assets/prometheus-k8s/service-monitor-kubelet.yaml
  jsonnet/prometheus.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#1130 Bug 1952149: oc adm top reporting unknown status for Windows node
  assets/prometheus-adapter/config-map.yaml
  jsonnet/main.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1160 Bug 1955462: drop container_memory_failures_total metric backport
  assets/prometheus-k8s/service-monitor-kubelet.yaml
  jsonnet/prometheus.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1154 Bug 1955469: remove node_mountstats_nfs_* metrics
  assets/node-exporter/daemonset.yaml
  jsonnet/node-exporter.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#1141 [4.7] Bug 1955482: Drop high-cardinality metrics from kube-state-metrics which aren't used
  assets/kube-state-metrics/deployment.yaml
  jsonnet/kube-state-metrics.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1170 Bug 1949519: Add DELETECOLLECTION to long-running apiserver verbs
  Makefile
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1166 Bug 1959278: Remove obsolete user-workload ServiceMonitor
  pkg/client/client.go
  pkg/tasks/prometheus_user_workload.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1156 Bug 1949123: assets: fix instance:node_filesystem_usage:sum
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1151 Bug 1933847: Manage PodDisruptionBudget objects
  Makefile
  hack/check-assets.sh
  hack/cluster-monitoring-operator-role.yaml.in
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/client/client.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/alertmanager.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1173 Bug 1955478: fix regex patterns in kube-state-metrics deny list
  assets/kube-state-metrics/deployment.yaml
  jsonnet/jsonnetfile.lock.json
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1147 Bug 1955471: [4.6] Disable collection of node_mountstats_nfs metrics in node_exporter
  assets/node-exporter/daemonset.yaml
  jsonnet/node-exporter.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1172 Bug 1962261: further adjust memory usage
  assets/alertmanager/alertmanager.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-adapter/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator/deployment.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/alertmanager.libsonnet
  jsonnet/kube-state-metrics.libsonnet
  jsonnet/node-exporter.libsonnet
  jsonnet/prometheus-adapter.libsonnet
  jsonnet/prometheus-operator.libsonnet
  jsonnet/prometheus.libsonnet
  jsonnet/thanos-querier.libsonnet
  manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1165 Bug 1960767: Protect Grafana metrics endpoint
  assets/grafana/deployment.yaml
  jsonnet/grafana.libsonnet
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1161 Bug 1960465: [release-4.6] Bring new etcd alerts
  assets/grafana/dashboard-definitions.yaml
  assets/prometheus-k8s/rules.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1159 Bug 1955454: [release-4.6] removing crio metric
  assets/prometheus-k8s/service-monitor-kubelet.yaml
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, qe-approved

#1176 Bug 1963833: don't attempt to delete nil PodDisruptionBudget object
  pkg/tasks/prometheus_user_workload.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#1164 Bug 1953798: Remove the upstream KubeAPIErrorBudgetBurn alerts
  assets/control-plane/prometheus-rule.yaml
  jsonnet/patch-rules.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1179 Bug 1961081: update PodDisruptionBudget api version to policy/v1
  assets/alertmanager/pod-disruption-budget.yaml
  assets/prometheus-adapter/pod-disruption-budget.yaml
  assets/prometheus-k8s/pod-disruption-budget.yaml
  assets/prometheus-user-workload/pod-disruption-budget.yaml
  jsonnet/alertmanager.libsonnet
  jsonnet/prometheus-adapter.libsonnet
  jsonnet/prometheus-user-workload.libsonnet
  jsonnet/prometheus.libsonnet
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1180 Bug 1955464: drop container_memory_failures_total metric backport
  assets/prometheus-k8s/service-monitor-kubelet.yaml
  jsonnet/prometheus.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1163 Bug 1955482: fix kube-state-metrics regexp patterns
  assets/kube-state-metrics/deployment.yaml
  jsonnet/kube-state-metrics.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1184 Bug 1961081: update pdb apiversion to v1
  pkg/client/client.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1182 Bug 1958016: should update to 0.47.1 for prometheus-operator resources label
  OWNERS
  assets/prometheus-operator-user-workload/cluster-role-binding.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator-user-workload/service-account.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/cluster-role-binding.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/prometheus-rule.yaml
  assets/prometheus-operator/service-account.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-operator/service.yaml
  go.mod
  go.sum
  jsonnet/main.jsonnet
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/alertmanager/operator.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/alertmanager/statefulset.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1171 Bug 1950290: remove KubeClientCertificateExpiration alert rule
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#1150 Bug 1957703: [4.7]: Add hard anti-affinity constraints to Prometheuses
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#1185 Bug 1965367: pkg/operator: Fix typo in etcd-metric-serving-ca resource name
  pkg/operator/operator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1144 Bug 1956565: manifest allowlist: add acm_managed_cluster_info in 4.7
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#1168 Bug 1957190: use NamespaceSelector instead of explicit allow/deny list
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  cmd/operator/main.go
  jsonnet/main.jsonnet
  jsonnet/prometheus-operator-user-workload.libsonnet
  jsonnet/prometheus-operator.libsonnet
  jsonnet/prometheus-user-workload.libsonnet
  jsonnet/prometheus.libsonnet
  jsonnet/thanos-ruler.libsonnet
  pkg/client/client.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/prometheusoperator.go
  pkg/tasks/prometheusoperator_user_workload.go
  test/e2e/framework/framework.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm
