Repository openshift/cluster-monitoring-operator, pull requests merged in 2021-01, with the labels that each got.

#1019 Bug 1907475: Add recording rules for ingress traffic and error rate
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1030 Bug 1913554: Ingress recording rule for error fraction is incorrect
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1033 Bug 1905393: manifests: use rbac.authorization.k8s.io/v1
  hack/cluster-monitoring-operator-role.yaml.in
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_50_cluster-monitoring-operator_03-role-binding.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1003 Bug 1915473: Annotate manifests for single-node-developer cluster profile
  Documentation/data-collection.md
  assets/grafana/dashboard-definitions.yaml
  hack/cluster-monitoring-operator-role.yaml.in
  jsonnet/add-release-annotation.libsonnet
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0user-priority-class.yaml
  manifests/0000_50_cluster-monitoring-operator_01-namespace.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_50_cluster-monitoring-operator_03-role-binding.yaml
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
  manifests/0000_50_cluster-monitoring-operator_06-clusteroperator.yaml
  manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#1035 Bug 1916056: manifest allowlist: add ACM metric
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#1032 Bug 1915003: Add a rule for calculating rolling node readiness
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1039 Bug 1914090: jsonnet: remove Ceph block devices in rules
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1037 Bug 1905141: Add vsphere-problem-detector to telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1041 Bug 1905330: Add missing CPU and memory requests
  assets/node-exporter/daemonset.yaml
  assets/telemeter-client/deployment.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/node-exporter.jsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1042 jsonnet: remove ksonnet
  assets/prometheus-k8s/kube-rbac-proxy-secret.yaml
  jsonnet/alertmanager.jsonnet
  jsonnet/cluster-monitoring-operator.jsonnet
  jsonnet/grafana.jsonnet
  jsonnet/kube-state-metrics.jsonnet
  jsonnet/main.jsonnet
  jsonnet/node-exporter.jsonnet
  jsonnet/prometheus-adapter.jsonnet
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-operator.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/rules.jsonnet
  jsonnet/thanos-querier.jsonnet
  jsonnet/thanos-ruler.jsonnet
Labels: approved, bugzilla/valid-bug, lgtm

#1022 Bug 1907830: Backporting #965
  assets/prometheus-k8s/rules.yaml
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
  test/rules/bz1879520.yaml
  test/rules/bz1903464.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1028 Bug 1912430: [Backport 4.6] Set resources to the native spec field
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/thanos-ruler.jsonnet
  pkg/manifests/bindata.go
  test/e2e/user_workload_monitoring_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1002 [release-4.6] Bug 1904091: Exporting registry v1 protocol usage metric
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1040 Bug 1918202: jsonnet: remove Ceph block devices in rules
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
