Repository openshift/cluster-monitoring-operator, pull requests merged in 2021-08, with the labels that each got.

#1309 Bug 1988991: pkg/client/client.go: Add retry logic for daemonset create
  pkg/client/client.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1298 Bug 1987197: hack,jsonnet: Better version checker
  Makefile
  hack/generate-rules-configmap.sh
  hack/generate-versions.sh
  hack/image.sh
  hack/logs.sh
  hack/reset-appversion.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/trigger-reconcile.sh
  hack/versions-check.sh
  jsonnet/main.jsonnet
  jsonnet/versions.json
  jsonnet/versions.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1311 Bug 1990258: cleaning up Makefile
  Makefile
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1283 Bug 1976765:Update AlertmanagerMembersInconsistent rule
  assets/alertmanager/prometheus-rule.yaml
  jsonnet/patch-rules.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#1293 MON-1749: Allow users to disable the local Alertmanager
  CHANGELOG.md
  pkg/client/client.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/alertmanager.go
  pkg/tasks/clustermonitoringoperator.go
  pkg/tasks/configsharing.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheusoperator_user_workload.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/alertmanager_test.go
  test/e2e/framework/assertions.go
  test/e2e/framework/framework.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1289 Bug 1982778: jsonnet: thanosquery: Use HTTP probes as opposed to exec
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#1310 Bug 1986981: Update Alert Configs
  CHANGELOG.md
  assets/alertmanager/prometheus-rule.yaml
  assets/control-plane/prometheus-rule.yaml
  assets/kube-state-metrics/prometheus-rule.yaml
  assets/node-exporter/prometheus-rule.yaml
  assets/prometheus-k8s/prometheus-rule.yaml
  assets/thanos-querier/prometheus-rule.yaml
  assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
  jsonnet/patch-rules.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1238 MON-1099 Improving error reporting to show all task failures
  pkg/client/status_reporter.go
  pkg/operator/operator.go
  pkg/tasks/tasks.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1315 Bug 1992567: jsonnet: cleanup jsonnet codebase and align with kube-prometheus
  jsonnet/add-workload-annotation.libsonnet
  jsonnet/components/alertmanager.libsonnet
  jsonnet/components/cluster-monitoring-operator.libsonnet
  jsonnet/components/control-plane.libsonnet
  jsonnet/components/grafana.libsonnet
  jsonnet/components/kube-state-metrics.libsonnet
  jsonnet/components/node-exporter.libsonnet
  jsonnet/components/openshift-state-metrics.libsonnet
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/components/prometheus-operator-user-workload.libsonnet
  jsonnet/components/prometheus-operator.libsonnet
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/components/telemeter-client.libsonnet
  jsonnet/components/thanos-querier.libsonnet
  jsonnet/components/thanos-ruler.libsonnet
  jsonnet/main.jsonnet
  jsonnet/remove-runbook-urls.libsonnet
  jsonnet/utils/add-annotations.libsonnet
  jsonnet/utils/anti-affinity.libsonnet
  jsonnet/utils/ibm-cloud-managed-profile.libsonnet
  jsonnet/utils/remove-limits.libsonnet
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1264 Bug 1978208: Sync dependencies for 4.8 release backports
  assets/control-plane/prometheus-rule.yaml
  assets/control-plane/service-monitor-kubelet.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/node-exporter/daemonset.yaml
  assets/prometheus-k8s/prometheus-rule.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
  hack/check-assets.sh
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/thanos-querier.libsonnet
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#1321 Bug 1993055: Fix node_exporter task error message
  pkg/tasks/nodeexporter.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1306 Bug 1994222: Add metrics for jaeger-operator
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1304 [release-4.6] Bug 1987246: node exporter calls /proc/cpuinfo multiple times causing the node to freeze
  assets/node-exporter/daemonset.yaml
  jsonnet/node-exporter.jsonnet
  pkg/manifests/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, qe-approved

#1327 Bug 1992493: jsonnet:rules: Adds missing summary and description to rules.
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1325 Bug 1956830: Update prometheus-adapter to v0.9.0
  assets/prometheus-adapter/api-service.yaml
  assets/prometheus-adapter/cluster-role-aggregated-metrics-reader.yaml
  assets/prometheus-adapter/cluster-role-binding-delegator.yaml
  assets/prometheus-adapter/cluster-role-binding.yaml
  assets/prometheus-adapter/cluster-role-server-resources.yaml
  assets/prometheus-adapter/cluster-role.yaml
  assets/prometheus-adapter/config-map.yaml
  assets/prometheus-adapter/deployment.yaml
  assets/prometheus-adapter/pod-disruption-budget.yaml
  assets/prometheus-adapter/role-binding-auth-reader.yaml
  assets/prometheus-adapter/service-account.yaml
  assets/prometheus-adapter/service-monitor.yaml
  assets/prometheus-adapter/service.yaml
  jsonnet/versions.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1324 Bug 1984365: Dashboard Prometheus/Overview can't filter instance by job
  CHANGELOG.md
  assets/grafana/dashboard-definitions.yaml
  jsonnet/jsonnetfile.lock.json
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1317 Bug 1986981: Alert Config update - Patch to PR#1310
  assets/control-plane/prometheus-rule.yaml
  assets/node-exporter/prometheus-rule.yaml
  assets/prometheus-k8s/prometheus-rule.yaml
  assets/thanos-querier/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1312 jsonnet: Support exluding namespaces from user-workload monitoring
  CHANGELOG.md
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/main.jsonnet
  test/e2e/framework/client.go
  test/e2e/user_workload_monitoring_test.go
  test/e2e/utils.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1337 Bug 1996718: Fix ksm metric label allowlist flag
  assets/kube-state-metrics/deployment.yaml
  jsonnet/components/kube-state-metrics.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1319 jsonnet: Add missing namespace labels to alerting rules
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  assets/control-plane/prometheus-rule.yaml
  assets/thanos-querier/prometheus-rule.yaml
  jsonnet/components/thanos-querier.libsonnet
  jsonnet/rules.libsonnet
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1348 Bug 1995614: Fix beta.kubernetes.io/os deprecated warning
  assets/thanos-querier/deployment.yaml
  jsonnet/components/thanos-querier.libsonnet
  manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1336 Bug 1991504: changes for moving from sha1 to bcrypt
  go.mod
  go.sum
  pkg/manifests/manifests.go
  pkg/tasks/clustermonitoringoperator.go
  vendor/golang.org/x/crypto/AUTHORS
  vendor/golang.org/x/crypto/CONTRIBUTORS
  vendor/golang.org/x/crypto/LICENSE
  vendor/golang.org/x/crypto/PATENTS
  vendor/golang.org/x/crypto/bcrypt/base64.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low
