Repository openshift/cluster-monitoring-operator, pull requests merged in 2021-03, with the labels that each got.

#1051 Bug 1926876: pkg/manifests: fix prometheus-proxy trustedCA
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#1079 Run jsonnet-fmt
  jsonnet/control-plane.libsonnet
  jsonnet/remove-runbook-urls.libsonnet
Labels: approved, lgtm

#1081 *: include all groups when testing prometheus rules
  Makefile
Labels: approved, lgtm

#1072 Bug 1933805: TargetDown should exclude unschedulable nodes
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/exclude-rules.libsonnet
  jsonnet/rules.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1080 Bug 1937907: etcdInsufficientMembers is wrong when etcd is in a pod
  assets/prometheus-k8s/rules.yaml
  jsonnet/grafana.jsonnet
  jsonnet/main.jsonnet
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/rules.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1083 Bug 1920898: [4.6] pkg/manifests: fix prometheus-proxy trustedCA
  pkg/manifests/manifests.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1071 Bug 1929354: [4.6] jsonnet/prometheus.jsonnet: Apply openshift-user-critical class to cluster Prometheus
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/prometheus-operator-user-workload.jsonnet
  jsonnet/prometheus-user-workload.jsonnet
  jsonnet/prometheus.jsonnet
  jsonnet/thanos-ruler.jsonnet
  manifests/0000_50_cluster-monitoring-operator_00_0user-priority-class.yaml
  pkg/manifests/bindata.go
  test/e2e/framework/framework.go
  test/e2e/priority_class_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1084 jsonnet: fix etcd mixin import
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
Labels: approved, lgtm

#1073 Add jsonnet function to patch upstream rules
  jsonnet/exclude-rules.libsonnet
  jsonnet/main.jsonnet
  jsonnet/patch-rules.libsonnet
Labels: approved, lgtm

#1082 hack: add check script for unused rules
  Makefile
  hack/check-rec-rule-usage.sh
  hack/find-rules.sh
Labels: approved, lgtm

#1090 Bug 1921335: Fix and adjust ThanosSidecarUnhealthy alert
  assets/prometheus-k8s/prometheus-rule.yaml
  assets/thanos-querier/prometheus-rule.yaml
  assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/patch-rules.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1089 OWNERS: add Jan
  OWNERS
Labels: approved, lgtm

#1087 Bug 1934163: adjust Thanos querier alerting rules
  CHANGELOG.md
  assets/thanos-querier/prometheus-rule.yaml
  jsonnet/patch-rules.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1078 Bug 1932624: jsonnet/rules,pkg/operator: use gauge based reconcilation state metrics and alerting
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
  pkg/operator/operator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1095 Remove kube-state-metrics flag temporary
  assets/kube-state-metrics/deployment.yaml
  jsonnet/kube-state-metrics.libsonnet
Labels: approved, lgtm

#1094 Bug 1943667: increase for duration of KubeDaemonSetRolloutStuck
  assets/control-plane/prometheus-rule.yaml
  jsonnet/patch-rules.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
