Repository openshift/cluster-monitoring-operator, pull requests merged in 2021-04, with the labels that each got.

#1099 Bump kube-state-metrics to v2.0.0-rc.1
  CHANGELOG.md
  assets/alertmanager/pod-disruption-budget.yaml
  assets/control-plane/prometheus-rule.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/kube-state-metrics/cluster-role-binding.yaml
  assets/kube-state-metrics/cluster-role.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/kube-state-metrics/prometheus-rule.yaml
  assets/kube-state-metrics/service-account.yaml
  assets/kube-state-metrics/service-monitor.yaml
  assets/kube-state-metrics/service.yaml
  assets/prometheus-adapter/config-map.yaml
  assets/prometheus-k8s/pod-disruption-budget.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/role-specific-namespaces.yaml
  assets/prometheus-user-workload/pod-disruption-budget.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/prometheus-user-workload/role-specific-namespaces.yaml
  jsonnet/jsonnetfile.lock.json
  jsonnet/kube-state-metrics.libsonnet
  jsonnet/main.jsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: approved, lgtm

#1098 Bug 1944974: remove KubeControllerManagerDown and KubeSchedulerDown alerts
  assets/control-plane/prometheus-rule.yaml
  jsonnet/patch-rules.libsonnet
  pkg/manifests/manifests_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1100 Bug 1943667: fix alert description
  assets/control-plane/prometheus-rule.yaml
  jsonnet/patch-rules.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1106 Bug 1938465: increase CPU requests for Thanos querier
  assets/thanos-querier/deployment.yaml
  jsonnet/thanos-querier.libsonnet
Labels: approved, lgtm

#1110 Bug 1934516: Change prometheus priority class to system-cluster-critical again
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/prometheus.libsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#986 IBM Cloud manifest profile patch
  Makefile
  hack/build-jsonnet.sh
  jsonnet/ibm-cloud-managed-profile.libsonnet
  jsonnet/main.jsonnet
  manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
Labels: approved, lgtm

#1101 Bug 1945851: Backport Remove the "instance" and "pod" labels for kube-state-metrics metrics
  assets/kube-state-metrics/service-monitor.yaml
  jsonnet/kube-state-metrics.jsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1104 Update denied metrics for kube-state-metrics
  assets/kube-state-metrics/cluster-role.yaml
  assets/kube-state-metrics/deployment.yaml
  jsonnet/kube-state-metrics.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
Labels: approved, lgtm

#1108 Refactor proxy config
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/tls_test.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  test/e2e/alertmanager_test.go
  test/e2e/prometheusadapter_test.go
  test/e2e/thanos_querier_test.go
Labels: approved, lgtm

#1113 Bug 1920700: Bump prometheus-adapter to v0.8.4
  assets/prometheus-adapter/api-service.yaml
  assets/prometheus-adapter/cluster-role-aggregated-metrics-reader.yaml
  assets/prometheus-adapter/cluster-role-binding-delegator.yaml
  assets/prometheus-adapter/cluster-role-binding.yaml
  assets/prometheus-adapter/cluster-role-server-resources.yaml
  assets/prometheus-adapter/cluster-role.yaml
  assets/prometheus-adapter/config-map.yaml
  assets/prometheus-adapter/deployment.yaml
  assets/prometheus-adapter/role-binding-auth-reader.yaml
  assets/prometheus-adapter/service-account.yaml
  assets/prometheus-adapter/service-monitor.yaml
  assets/prometheus-adapter/service.yaml
  jsonnet/main.jsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1117 Bug 1940933: jsonnet: make AggregatedAPIDown more resilient to OCP upgrades
  CHANGELOG.md
  assets/control-plane/prometheus-rule.yaml
  jsonnet/patch-rules.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1109 Add management workload annotations
  assets/alertmanager/alertmanager.yaml
  assets/grafana/deployment.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/openshift-state-metrics/deployment.yaml
  assets/prometheus-adapter/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/telemeter-client/deployment.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/add-workload-annotation.libsonnet
  jsonnet/main.jsonnet
  manifests/0000_50_cluster-monitoring-operator_01-namespace.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#1105 Bug 1946597: Backport Remove the "instance" and "pod" labels for kube-state-metrics metrics
  assets/kube-state-metrics/service-monitor.yaml
  jsonnet/kube-state-metrics.jsonnet
  pkg/manifests/bindata.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#1112 Bug 1948082: Set unavailable message
  pkg/client/status_reporter.go
  pkg/client/status_reporter_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1119 Bug 1948711: jsonnet: apply HA conventions
  assets/prometheus-adapter/deployment.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/prometheus-adapter.libsonnet
  jsonnet/thanos-querier.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1115 BUG 1949145: Delete 0000_50_cluster-monitoring-operator_00_0user-priority-class.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0user-priority-class.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1102 Bug 1945677: manifest allowlist: add acm_managed_cluster_info
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1122 Bug 1950761: Revert: jsonnet: apply HA conventions
  assets/prometheus-adapter/deployment.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/prometheus-adapter.libsonnet
  jsonnet/thanos-querier.libsonnet
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1126 Bug 1951505: Remove deprecated techPreviewUserWorkload
  CHANGELOG.md
  pkg/manifests/config.go
  pkg/operator/operator.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/prometheusoperator_user_workload.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1125 Bug 1951052: drop CRI-O image metrics
  assets/control-plane/service-monitor-kubelet.yaml
  jsonnet/control-plane.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1129 Bug 1952032: jsonnet: add format changes made by make jsonnet-fmt
  jsonnet/ibm-cloud-managed-profile.libsonnet
  jsonnet/main.jsonnet
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1124 Bug 1948711: Apply HA conventions to prometheus-adapter and thanos-ruler
  assets/prometheus-adapter/deployment.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/prometheus-adapter.libsonnet
  jsonnet/thanos-querier.libsonnet
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1103 Bug 1945856: Revert "Bug 1934516: [4.7]: jsonnet/prometheus.jsonnet: Apply system-cluster-critical class to cluster Prometheus "
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/prometheus.jsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#1135 Bug 1949262: jsonnet: add hard anti-affinity to Prometheuses
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/anti-affinity.libsonnet
  jsonnet/main.jsonnet
  jsonnet/prometheus-adapter.libsonnet
  jsonnet/thanos-querier.libsonnet
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1131 Bug 1955457: drop container_memory_failures_total metric
  assets/control-plane/service-monitor-kubelet.yaml
  jsonnet/control-plane.libsonnet
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
