Repository openshift/cluster-monitoring-operator, pull requests merged in 2022-06, with the labels that each got.

#1681 Bug 2090838: ignore flapping host interface 'tunbr'
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/main.jsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1546 whitelist cluster-logging-operator metrics for telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1652 MON-2480: Double the ServiceMonitor intervals for SNO
  CHANGELOG.md
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1684 Bug 2094704: remove verbose output from kube-rbac-proxy in Prometheus-k8s pod
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/components/prometheus.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1646 Bug 2057832: Updates recording rule cluster:telemetry_selected_series:count
  assets/telemeter-client/prometheus-rule.yaml
  jsonnet/components/telemeter-client.libsonnet
  jsonnet/jsonnetfile.lock.json
  pkg/manifests/manifests.go
  pkg/tasks/telemeter.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1604 Bug 2096315: Create a patch im CMO for NodeClockNotSynchronising
  assets/node-exporter/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1682 MON-2567: enable AlertmanagerConfig v1beta1
  CHANGELOG.md
  assets/admission-webhook/service.yaml
  assets/prometheus-operator/prometheus-rule.yaml
  jsonnet/components/prometheus-operator.libsonnet
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
  test/e2e/alertmanager_test.go
  test/e2e/framework/framework.go
  test/e2e/validatingwebhook_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1662 Adding a usage metric for Openshift Sandboxed Containers
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, ok-to-test, px-approved, docs-approved, qe-approved

#1692 Bug 2091902: Improve performance of Prometheus Adapter
  assets/prometheus-adapter/configmap-prometheus.yaml
  assets/prometheus-adapter/deployment.yaml
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/main.jsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1675 MON-2552: Add support for user-defined alerting rules
  examples/alerting-rule.yaml
  go.mod
  hack/build-jsonnet.sh
  jsonnet/components/cluster-monitoring-operator.libsonnet
  jsonnet/crds/alertingrules-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertingrules-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_02-techpreview-role.yaml
  manifests/0000_50_cluster-monitoring-operator_03-role-binding.yaml
  pkg/alert/rule_controller.go
  pkg/client/client.go
  pkg/operator/operator.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/0000_50_monitoring_01_alertingrules.crd.yaml
  vendor/github.com/openshift/api/monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
  vendor/github.com/openshift/api/monitoring/v1alpha1/doc.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/register.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/types.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/monitoring/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/monitoring/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/monitoring/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/monitoring/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/monitoring/clientset/versioned/typed/monitoring/v1alpha1/alertingrule.go
  vendor/github.com/openshift/client-go/monitoring/clientset/versioned/typed/monitoring/v1alpha1/alertrelabelconfig.go
  vendor/github.com/openshift/client-go/monitoring/clientset/versioned/typed/monitoring/v1alpha1/doc.go
  vendor/github.com/openshift/client-go/monitoring/clientset/versioned/typed/monitoring/v1alpha1/generated_expansion.go
  vendor/github.com/openshift/client-go/monitoring/clientset/versioned/typed/monitoring/v1alpha1/monitoring_client.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1694 Bug 2083242: IR-254: Collecting registry and image stream usage
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#1554 Bug 2037513: Fix dashboards having container_fs* metrices in queries
  assets/grafana/dashboard-definitions.yaml
  jsonnet/main.jsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1695 Bug 2098505: Backport PR#1692 to release-4.10
  assets/prometheus-adapter/configmap-prometheus.yaml
  assets/prometheus-adapter/deployment.yaml
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/main.jsonnet
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#1676 MON-2091: Add support for user-defined alert relabel configs
  Makefile
  assets/prometheus-k8s/additional-alert-manager-relabelling-secret.yaml
  assets/prometheus-k8s/prometheus.yaml
  examples/alert-relabel-config.yaml
  go.mod
  jsonnet/components/cluster-monitoring-operator.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/crds/alertingrules-custom-resource-definition.json
  jsonnet/crds/alertingrules-custom-resource-definition.yaml
  jsonnet/crds/alertrelabelconfigs-custom-resource-definition.json
  jsonnet/main.jsonnet
  manifests/0000_50_cluster-monitoring-operator_00_0alertrelabelconfigs-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_02-techpreview-role.yaml
  pkg/alert/relabel_controller.go
  pkg/client/client.go
  pkg/manifests/manifests.go
  pkg/operator/operator.go
  pkg/tasks/prometheus.go
  test/e2e/alert_relabel_config_test.go
  test/e2e/framework/framework.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
