Repository openshift/cluster-monitoring-operator, pull requests merged in 2022-05, with the labels that each got.

#1640 *: add standalone admission webhook
  CHANGELOG.md
  assets/admission-webhook/alertmanager-config-validating-webhook.yaml
  assets/admission-webhook/deployment.yaml
  assets/admission-webhook/pod-disruption-budget.yaml
  assets/admission-webhook/prometheus-rule-validating-webhook.yaml
  assets/admission-webhook/service-account.yaml
  assets/admission-webhook/service.yaml
  jsonnet/components/admission-webhook.libsonnet
  jsonnet/components/prometheus-operator.libsonnet
  jsonnet/main.jsonnet
  jsonnet/utils/generate-certificate-injection.libsonnet
  manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
  manifests/image-references
  pkg/manifests/apiserver_config.go
  pkg/manifests/apiserver_config_test.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheusoperator.go
  test/e2e/tls_security_profile_test.go
  test/e2e/validatingwebhook_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1651 MON-1913: pkg/manifest: Allow retention to be configurable for Thanos-Ruler in UWM
  CHANGELOG.md
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/e2e/config_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1649 Bug 2078667: Fix prometheus not ingesting samples
  assets/prometheus-k8s/rules.yaml
  jsonnet/main.jsonnet
  pkg/manifests/bindata.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, backport-risk-assessed

#1663 Add runbook for kube persistent volume inodes filling up
  assets/control-plane/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1635 Expose ovnkube_master_egress_routing_via_host via telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1665 Bug 2077722: Adjust NodeFilesystemSpaceFillingUp thresholds according default kubelet GC behavior
  assets/node-exporter/prometheus-rule.yaml
  jsonnet/jsonnetfile.lock.json
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, qe-approved, backport-risk-assessed

#1670 OWNERS: move @fpetkovski, @PhilipGough and @bison to emeritus section
  OWNERS
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1467 Add bodysize limit for metric scraping.
  CHANGELOG.md
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  test/e2e/prometheus_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1654 Bug 2083460: Set timeout across Grafana components
  assets/grafana/config.yaml
  assets/grafana/deployment.yaml
  assets/grafana/route.yaml
  jsonnet/components/grafana.libsonnet
  jsonnet/main.jsonnet
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, qe-approved, backport-risk-assessed

#1671 Bug 2084079: Refactors CreateRouteIfNotExists to CreateOrUpdateRoute
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/tasks/alertmanager.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/alertmanager_helpers.go
  test/e2e/prometheus_test.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/fake_route.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/fake_route_client.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1559 eo metrics for Telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1660 Bug 2079292: Adds necessary SecurityContext settings to UWM deployments
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-user-workload/cluster-role.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/cluster-role.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/components/prometheus-operator-user-workload.libsonnet
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/thanos-querier.libsonnet
  jsonnet/components/thanos-ruler.libsonnet
  manifests/0000_50_cluster-monitoring-operator_01-namespace.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1657 Bug 2090602: Federation for UWM metrics
  CHANGELOG.md
  assets/prometheus-user-workload/federate-route.yaml
  assets/prometheus-user-workload/kube-rbac-proxy-federate-secret.yaml
  assets/prometheus-user-workload/kube-rbac-proxy-metrics-secret.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/prometheus-user-workload/service.yaml
  jsonnet/components/prometheus-user-workload.libsonnet
  pkg/manifests/manifests.go
  pkg/tasks/prometheus_user_workload.go
  test/e2e/alertmanager_test.go
  test/e2e/framework/framework.go
  test/e2e/thanos_ruler_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#1668 Bug 2009352: IR-254: Collecting registry and image stream usage
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1678 Bug 2090422: pkg/manifest: Allow retention to be configurable for Thanos-Ruler in UWM
  CHANGELOG.md
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/e2e/config_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, qe-approved, backport-risk-assessed

#1677 Bug 2089806: Refactors CreateRouteIfNotExists to CreateOrUpdateRoute
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/tasks/alertmanager.go
  pkg/tasks/grafana.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/alertmanager_helpers.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/fake_route.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/fake/fake_route_client.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, qe-approved, backport-risk-assessed
