Repository openshift/cluster-monitoring-operator, pull requests merged in 2022-08, with the labels that each got.

#1624 MON-1261: exposing topology spread constraints through config
  CHANGELOG.md
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1734 Bug 2115527: reverts #1704
  jsonnet/components/cluster-monitoring-operator.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-namespaced-cluster-role.yaml
  pkg/client/client.go
  pkg/client/client_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1740 Bug 2100312: go.mod: update openshift-api to current release-4.12 tip
  go.mod
  go.sum
  jsonnet/crds/alertrelabelconfigs-custom-resource-definition.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertrelabelconfigs-custom-resource-definition.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
  vendor/github.com/openshift/api/monitoring/v1alpha1/types.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.proto
  vendor/github.com/openshift/api/route/v1/route.crd.yaml
  vendor/github.com/openshift/api/route/v1/route.crd.yaml-patch
  vendor/github.com/openshift/api/route/v1/test-route-validation.sh
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low, px-approved, docs-approved

#1739 OWNERS: Add myself, and move former team members to emeritus
  OWNERS
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1737 Bug 2116382: Give precedence to CMO config map proxy config
  pkg/operator/operator.go
  pkg/operator/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1721 Whitelist metrics for MCG addon
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1724 Bug 2099939: Sets status when UserAlertmanagerConfig is missconfigured
  pkg/client/status_reporter.go
  pkg/manifests/config.go
  pkg/operator/operator.go
  test/e2e/config_test.go
  test/e2e/framework/assertions.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1753 OCPBUGS-641: grafana: bump to 7.5.11
  assets/grafana/config.yaml
  assets/grafana/dashboard-datasources.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/dashboard-sources.yaml
  assets/grafana/deployment.yaml
  assets/grafana/service-monitor.yaml
  assets/grafana/service.yaml
  jsonnet/versions.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#1754 OCPBUGS-644: grafana: bump to 7.5.11
  assets/grafana/config.yaml
  assets/grafana/dashboard-datasources.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/dashboard-sources.yaml
  assets/grafana/deployment.yaml
  assets/grafana/service-monitor.yaml
  assets/grafana/service.yaml
  jsonnet/main.jsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate
