Repository openshift/cluster-monitoring-operator, pull requests merged in 2022-09, with the labels that each got.

#1731 MON-2646: Remove grafana related code
  .github/ISSUE_TEMPLATE/release.md
  Documentation/cluster-monitoring.md
  assets/grafana/cluster-role-binding.yaml
  assets/grafana/cluster-role.yaml
  assets/grafana/config.yaml
  assets/grafana/dashboard-datasources.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/dashboard-sources.yaml
  assets/grafana/deployment.yaml
  assets/grafana/kube-rbac-proxy-metric-secret.yaml
  assets/grafana/prometheus-rule.yaml
  assets/grafana/proxy-secret.yaml
  assets/grafana/route.yaml
  assets/grafana/service-account.yaml
  assets/grafana/service-monitor.yaml
  assets/grafana/service.yaml
  assets/grafana/trusted-ca-bundle.yaml
  assets/prometheus-k8s/htpasswd-secret.yaml
  assets/thanos-querier/oauth-htpasswd-secret.yaml
  assets/thanos-ruler/oauth-htpasswd-secret.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  go.mod
  hack/build-jsonnet.sh
  hack/check-rec-rule-usage.sh
  hack/generate-versions.sh
  hack/ocp-images.sh
  jsonnet/components/dashboards.libsonnet
  jsonnet/components/grafana.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/components/thanos-querier.libsonnet
  jsonnet/components/thanos-ruler.libsonnet
  jsonnet/main.jsonnet
  jsonnet/versions.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/grafana.go
  pkg/tasks/prometheus.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/config_test.go
  vendor/golang.org/x/crypto/AUTHORS
  vendor/golang.org/x/crypto/CONTRIBUTORS
  vendor/golang.org/x/crypto/LICENSE
  vendor/golang.org/x/crypto/PATENTS
  vendor/golang.org/x/crypto/bcrypt/base64.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
  vendor/modules.txt
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1746 OCPBUGS-864: sorted condition and update on change
  pkg/client/condition.go
  pkg/client/condition_test.go
  pkg/client/status_reporter.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#1760 OCPBUGS-924: increase alertmanager's startupProbe failure threshold
  pkg/manifests/manifests.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#1762 [release-4.9] OCPBUGS-937: Give precedence to CMO config map proxy config
  pkg/operator/operator.go
  pkg/operator/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low

#1755 Bug 2111345: go.mod: update openshift-api to current release-4.11 tip
  go.mod
  go.sum
  jsonnet/crds/alertrelabelconfigs-custom-resource-definition.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertrelabelconfigs-custom-resource-definition.yaml
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
  vendor/github.com/openshift/api/monitoring/v1alpha1/types.go
  vendor/github.com/openshift/api/monitoring/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-low, qe-approved, backport-risk-assessed

#1750 MON-2654: Add a cluster advance feature usage metric
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1763 Add odf_system_objects_total and odf_system_bucket_count
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, ok-to-test, px-approved, docs-approved, qe-approved

#1738 Add client certificate and key to service monitor
  assets/kube-state-metrics/service-monitor.yaml
  assets/prometheus-adapter/service-monitor.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  jsonnet/components/kube-state-metrics.libsonnet
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/components/prometheus-operator-user-workload.libsonnet
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1765 [release-4.8] OCPBUGS-1098: Give precedence to CMO config map proxy config
  pkg/operator/operator.go
  pkg/operator/operator_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low

#1718 Use odf metrics instead of ceph
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, ok-to-test, px-approved, docs-approved, qe-approved

#1769 go.{mod,sum}: require Go 1.18
  go.mod
  go.sum
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1756 Rename kube_pv to odf_system_pvs
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, ok-to-test, px-approved, docs-approved, qe-approved

#1639 Bug 1933144: Extend KubeAggregatedAPIDown alert "for" to 15m
  assets/control-plane/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1752 OCPBUGS-1364: Dedicated kubelet ServiceMonitor for prometheus-adapter
  CHANGELOG.md
  Documentation/api.md
  Documentation/openshiftdocs/index.adoc
  Documentation/openshiftdocs/modules/dedicatedservicemonitors.adoc
  Documentation/openshiftdocs/modules/k8sprometheusadapter.adoc
  assets/control-plane/service-monitor-kubelet-resource-metrics.yaml
  assets/prometheus-adapter/config-map-dedicated-service-monitors.yaml
  assets/prometheus-adapter/deployment.yaml
  jsonnet/components/control-plane.libsonnet
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/main.jsonnet
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
  pkg/operator/operator.go
  pkg/tasks/controlplane.go
  pkg/tasks/prometheusadapter.go
  test/e2e/prometheusadapter_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug

#1690 Bug 2100860: Pass user-defined Alertmanager service in shared configmap
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/configsharing.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, px-approved, docs-approved

#1747 Bug 2114721: Adds telemeter token hash to Deployment annotation
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/telemeter.go
  test/e2e/config_test.go
  test/e2e/framework/assertions.go
  test/e2e/framework/helpers.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1774 OCPBUGS-1551: Dedicated kubelet ServiceMonitor for prometheus-adapter
  CHANGELOG.md
  assets/control-plane/service-monitor-kubelet-resource-metrics.yaml
  assets/prometheus-adapter/config-map-dedicated-service-monitors.yaml
  assets/prometheus-adapter/deployment.yaml
  jsonnet/components/control-plane.libsonnet
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/main.jsonnet
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/controlplane.go
  pkg/tasks/prometheusadapter.go
  test/e2e/prometheusadapter_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug

#1777 OCPBUGS-1676: Dedicated kubelet ServiceMonitor for prometheus-adapter
  CHANGELOG.md
  assets/control-plane/service-monitor-kubelet-resource-metrics.yaml
  assets/prometheus-adapter/config-map-dedicated-service-monitors.yaml
  assets/prometheus-adapter/deployment.yaml
  jsonnet/components/control-plane.libsonnet
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/main.jsonnet
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/controlplane.go
  pkg/tasks/prometheusadapter.go
  test/e2e/prometheusadapter_test.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug
