Repository openshift/cluster-monitoring-operator, pull requests merged in 2022-01, with the labels that each got.

#1477 BUILD-345: Added csi shared resource metrics to telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1531 Bug 2037073: pkg/manifests: account for slow DNS resolutions
  pkg/manifests/manifests.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1513 manifests: Support thanos query requst logging via CM
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1527 Reconcile AlertManagerConfig in UWM from platform Prometheus
  CHANGELOG.md
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/e2e/alertmanager_helpers.go
  test/e2e/alertmanager_test.go
  test/e2e/framework/framework.go
  test/e2e/uwm_helpers.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1539 Bug 2037891: Reverting the secureJsonData change for the grafana password
  assets/grafana/dashboard-datasources.yaml
  assets/grafana/deployment.yaml
  jsonnet/main.jsonnet
  pkg/manifests/manifests.go
  pkg/tasks/grafana.go
  pkg/tasks/prometheus.go
  pkg/tasks/thanos_querier.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1542 Bug 2026489: Add runbook url for ThanosRuleRuleEvaluationLatencyHigh alert
  assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#1544 Bug 2030347: kube-state-metrics exposes metrics about resource annotations
  assets/kube-state-metrics/deployment.yaml
  jsonnet/components/kube-state-metrics.libsonnet
  test/e2e/kube_state_metrics_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1543 Bug 2038419: Bump Grafana to 8.3.4 and handle datasource migration
  CHANGELOG.md
  assets/grafana/config.yaml
  assets/grafana/dashboard-datasources.yaml
  assets/grafana/dashboard-definitions.yaml
  assets/grafana/dashboard-sources.yaml
  assets/grafana/deployment.yaml
  assets/grafana/service-account.yaml
  assets/grafana/service-monitor.yaml
  assets/grafana/service.yaml
  jsonnet/components/grafana.libsonnet
  jsonnet/main.jsonnet
  jsonnet/versions.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
  pkg/manifests/manifests.go
  pkg/tasks/grafana.go
  pkg/tasks/prometheus.go
  pkg/tasks/thanos_querier.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1512 [MON-1950] Remove UI access from the Thanos routes
  assets/thanos-querier/route.yaml
  assets/thanos-ruler/route.yaml
  jsonnet/components/thanos-querier.libsonnet
  jsonnet/components/thanos-ruler.libsonnet
  test/e2e/thanos_ruler_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1529 [MON-1630] Remove UI access to AlertManager
  assets/alertmanager/route.yaml
  jsonnet/components/alertmanager.libsonnet
  jsonnet/components/cluster-monitoring-operator.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/client/client.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/tls_test.go
  pkg/operator/operator.go
  pkg/tasks/alertmanager.go
  test/e2e/alertmanager_test.go
  test/e2e/prometheusadapter_test.go
  test/e2e/thanos_querier_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1545 Mon 2172: Add clusterrole for editing alertmanagerconfigs
  CHANGELOG.md
  assets/cluster-monitoring-operator/alerting-edit-cluster-role.yaml
  jsonnet/components/cluster-monitoring-operator.libsonnet
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/clustermonitoringoperator.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
