Repository openshift/cluster-monitoring-operator, pull requests merged in 2022-10, with the labels that each got.

#1788 Revert "[bot] Update jsonnet dependencies"
  assets/control-plane/prometheus-rule.yaml
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
Labels: lgtm, approved, bugzilla/valid-bug

#1787 Updating cluster-monitoring-operator images to be consistent with ART
  .ci-operator.yaml
  Dockerfile
  pkg/manifests/manifests.go
  pkg/manifests/tls.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1558 Bug 2043518: set degraded and available status based on Prometheus resource status
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/state_error.go
  pkg/client/status_reporter.go
  pkg/client/status_reporter_test.go
  pkg/manifests/manifests.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_validation.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#1784 OCPBUGS-2138: Add os_image_url_override metric from MCO to telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, bugzilla/valid-bug, px-approved, docs-approved, qe-approved, jira/valid-bug, jira/severity-moderate

#1794 update to release.openshift.io/feature-set to match OCP 4.12
  jsonnet/components/cluster-monitoring-operator.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-techpreview-role.yaml
Labels: lgtm, approved, bugzilla/valid-bug

#1776 CFE-551: Allowlist metrics related to Routes to be sent via telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1780 OCPBUGS-1321: Node Exporter - ignore virtual NICs from OVNK cluster
  assets/node-exporter/daemonset.yaml
  jsonnet/components/node-exporter.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-low

#1799 jsonnet/components: remove PDB patches
  jsonnet/components/admission-webhook.libsonnet
  jsonnet/components/alertmanager.libsonnet
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1802 OCPBUGS-450: jsonnet: bump dependencies
  assets/control-plane/prometheus-rule.yaml
  jsonnet/jsonnetfile.lock.json
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug

#1801 Documentation: fix TelemeterClientConfig
  Documentation/api.md
  Documentation/openshiftdocs/modules/telemeterclientconfig.adoc
  pkg/manifests/types.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1806 *: don't expose Prometheus operator's port
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-operator/operator-certs-ca-bundle.yaml
  assets/prometheus-operator/service.yaml
  jsonnet/components/prometheus-operator-user-workload.libsonnet
  jsonnet/components/prometheus-operator.libsonnet
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheusoperator.go
  test/e2e/tls_security_profile_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1803 MON-2727: Adds telemeter alert TelemeterClientFailures
  CHANGELOG.md
  assets/telemeter-client/prometheus-rule.yaml
  jsonnet/jsonnetfile.lock.json
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
