Repository openshift/cluster-monitoring-operator, pull requests merged in 2022-07, with the labels that each got.

#1701 Bug 2100472: start alert controllers only when techpreview
  jsonnet/components/cluster-monitoring-operator.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/alert/relabel_controller.go
  pkg/alert/rule_controller.go
  pkg/client/client.go
  pkg/operator/operator.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1706 Revert "Bug 2100472: start alert controllers only when techpreview"
  jsonnet/components/cluster-monitoring-operator.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/alert/relabel_controller.go
  pkg/alert/rule_controller.go
  pkg/client/client.go
  pkg/operator/operator.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1707 Bug 2100472: fix alert controllers when not in techpreview
  Makefile
  jsonnet/components/cluster-monitoring-operator.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/alert/relabel_controller.go
  pkg/alert/rule_controller.go
  pkg/client/client.go
  pkg/operator/operator.go
  test/e2e/alert_relabel_config_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1704 Bug 2095719: Updates CreateOrUpdateServiceAccounts
  jsonnet/components/cluster-monitoring-operator.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-namespaced-cluster-role.yaml
  pkg/client/client.go
  pkg/client/client_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1710 Add telemetry metrics for HyperShift
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1716 Bug 2090988: Set HA convention on admission-webhook
  assets/admission-webhook/deployment.yaml
  jsonnet/components/admission-webhook.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#1674 Bug 2089199: Removes etcd related dashboards from CMO
  jsonnet/components/grafana.libsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1714 MON-2658: Add security context to additional containers in e2e tests
  test/e2e/alertmanager_helpers.go
  test/e2e/utils.go
  test/e2e/uwm_helpers.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1715 Bug 2099526: Updates jsonnet dependencies, prom-adapter
  assets/prometheus-adapter/deployment.yaml
  jsonnet/jsonnetfile.lock.json
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#1720 Bug 2083226: increase alertmanager startupProbe failure threshold
  pkg/manifests/manifests.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1725 [MON-2695] Unpin Jsonnet dependencies.
  assets/grafana/dashboard-definitions.yaml
  assets/kube-state-metrics/cluster-role.yaml
  assets/node-exporter/prometheus-rule.yaml
  assets/prometheus-k8s/prometheus-rule.yaml
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1728 pkg/manifests/amcfg.go: reorder declarations
  pkg/manifests/amcfg.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
