Repository openshift/cluster-monitoring-operator, pull requests merged in 2023-03, with the labels that each got.

#1894 MON-2895: toggle netlink implementation of netclass collector
  CHANGELOG.md
  Documentation/api.md
  Documentation/openshiftdocs/modules/nodeexportercollectornetclassconfig.adoc
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-reference

#1891 MON-2904: add nodeExporter.collectors.buddyinfo settings.
  CHANGELOG.md
  Documentation/api.md
  Documentation/openshiftdocs/index.adoc
  Documentation/openshiftdocs/modules/nodeexportercollectorbuddyinfoconfig.adoc
  Documentation/openshiftdocs/modules/nodeexportercollectorconfig.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
  test/e2e/node_exporter_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-reference

#1899 MON-2959: test/e2e: Add test for alertmanager secret platform
  pkg/manifests/manifests.go
  test/e2e/alertmanager_test.go
  test/e2e/validators.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-reference

#1907 MON-2973: test/e2e: Add cleanup func for alertmanager uwm secret test
  test/e2e/alertmanager_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-reference

#1912 OCPBUGS-8282: turn off netlink mode of netclass collector in Node Exporter.
  Documentation/api.md
  Documentation/openshiftdocs/modules/nodeexportercollectornetclassconfig.adoc
  pkg/manifests/config.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1905 OCPBUGS-7282: Node Exporter ignores network interface under name "cali[a-f0-9]*"
  assets/node-exporter/daemonset.yaml
  jsonnet/main.jsonnet
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/valid-reference

#1800 OCPBUGS-2439: set the argument path.udev.data in node exporter
  assets/node-exporter/daemonset.yaml
  jsonnet/components/node-exporter.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#1909 OCPBUGS-8215: bugfix in Node Exporter argument setting
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/e2e/node_exporter_test.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#1917 OCPBUGS-7694: add startup probe for prometheus-adapter
  assets/prometheus-adapter/deployment.yaml
  jsonnet/jsonnetfile.lock.json
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference
