Repository openshift/cluster-monitoring-operator, pull requests merged in 2023-07, with the labels that each got.

#2028 e2e-tests: ensure pod assertions find at least one pod
  test/e2e/config_test.go
  test/e2e/framework/assertions.go
Labels: lgtm, approved

#2021 OCPBUGS-15469: Limit the value of GOMAXPROCS on node-exporter to 4.
  assets/node-exporter/daemonset.yaml
  jsonnet/components/node-exporter.libsonnet
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1963 MON-3222: Make netdev/netclass interfaces configurable
  CHANGELOG.md
  Documentation/api.md
  Documentation/openshiftdocs/modules/nodeexporterconfig.adoc
  assets/node-exporter/daemonset.yaml
  jsonnet/main.jsonnet
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
  test/e2e/node_exporter_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-reference

#2023 OCPBUGS-15473: Limit the value of GOMAXPROCS on node-exporter to 4
  assets/node-exporter/daemonset.yaml
  jsonnet/components/node-exporter.libsonnet
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2032 MON-3269: add nodeExporter.collectors.processes settings.
  Documentation/api.md
  Documentation/openshiftdocs/index.adoc
  Documentation/openshiftdocs/modules/nodeexportercollectorconfig.adoc
  Documentation/openshiftdocs/modules/nodeexportercollectorprocessesconfig.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
  test/e2e/node_exporter_test.go
Labels: lgtm, approved, jira/valid-reference

#2030 MON-3231: add metric for the configured profile
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  cmd/operator/main.go
  jsonnet/rules.libsonnet
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
  pkg/manifests/config.go
  pkg/metrics/metrics.go
  pkg/operator/operator.go
Labels: lgtm, approved, jira/valid-reference

#2035 MON-3181: Expose and propagate TopologySpreadConstraints for thanos-querier
  Documentation/api.md
  Documentation/openshiftdocs/modules/thanosquerierconfig.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-reference

#2038 MON-3183: Expose and propagate TopologySpreadConstraints for UWM prometheus
  Documentation/api.md
  Documentation/openshiftdocs/modules/prometheusrestrictedconfig.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-reference

#2017 MON-3180: Expose and propagate TopologySpreadConstraints for telemeter-client
  Documentation/api.md
  Documentation/openshiftdocs/modules/telemeterclientconfig.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-reference

#2037 MON-3182: Expose and propagate TopologySpreadConstraints for UWM alertmanager
  Documentation/api.md
  Documentation/openshiftdocs/modules/alertmanageruserworkloadconfig.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-reference

#2012 OCPBUGS-9835: Add Content-Security-Policy headers to prometheus and alertmanager
  assets/alertmanager/alertmanager.yaml
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/components/alertmanager.libsonnet
  jsonnet/components/prometheus.libsonnet
  test/e2e/framework/framework.go
  test/e2e/security_headers_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2025 MON-3176: Expose and propagate TopologySpreadConstraints for prometheus-adapter
  Documentation/api.md
  Documentation/openshiftdocs/modules/k8sprometheusadapter.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-reference

#2034 MON-3179: Expose and propagate TopologySpreadConstraints for openshift state metrics
  Documentation/api.md
  Documentation/openshiftdocs/modules/openshiftstatemetricsconfig.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-reference

#1892 MON-2903: add nodeExporter.collectors.systemd settings.
  Documentation/api.md
  Documentation/openshiftdocs/index.adoc
  Documentation/openshiftdocs/modules/nodeexportercollectorconfig.adoc
  Documentation/openshiftdocs/modules/nodeexportercollectorsystemdconfig.adoc
  assets/node-exporter/daemonset.yaml
  jsonnet/components/node-exporter.libsonnet
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
  test/e2e/node_exporter_test.go
Labels: lgtm, approved, docs-approved, qe-approved, jira/valid-reference

#2044 MON-3274: collect the number of LIST and WATCH requests to the apiserver from telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  assets/kube-state-metrics/cluster-role-binding.yaml
  assets/kube-state-metrics/cluster-role.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/kube-state-metrics/minimal-service-monitor.yaml
  assets/kube-state-metrics/prometheus-rule.yaml
  assets/kube-state-metrics/service-account.yaml
  assets/kube-state-metrics/service-monitor.yaml
  assets/kube-state-metrics/service.yaml
  jsonnet/rules.libsonnet
  jsonnet/versions.yaml
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-reference

#2033 MON-3178: Expose and propagate TopologySpreadConstraints for prometheus-operator
  Documentation/api.md
  Documentation/openshiftdocs/modules/prometheusoperatorconfig.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-reference

#2045 OCPBUGS-16203: correct docs for metric node_systemd_timer_last_trigger_seconds.
  Documentation/api.md
  Documentation/openshiftdocs/modules/nodeexportercollectorsystemdconfig.adoc
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2026 MON-3177: Expose and propagate TopologySpreadConstraints for kube state metrics
  Documentation/api.md
  Documentation/openshiftdocs/modules/kubestatemetricsconfig.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-reference

#2040 Remove OADP metrics from the Telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved

#2049 OCPBUGS-10699: remove Kube*QuotaOvercommit alerts
  CHANGELOG.md
  assets/control-plane/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, jira/valid-bug, jira/severity-low, jira/valid-reference
