Repository openshift/cluster-monitoring-operator, pull requests merged in 2023-09, with the labels that each got.

#2080 MON-2642: Improve e2e tests for alertrelabelconfigs CRD
  examples/alert-relabel-config.yaml
  examples/alerting-rule.yaml
  test/e2e/alert_relabel_config_test.go
  test/e2e/framework/prometheus.go
  test/e2e/prometheus_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2072 OCPBUGS-17682: add topologySpreadConstraints to UWM prometheus operator
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#2073 OCPBUGS-19356: Topology spread constraints admission webhook
  Documentation/api.md
  Documentation/openshiftdocs/modules/prometheusoperatoradmissionwebhookconfig.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#2077 MON-3376: Remove deprecated --logtostderr argument
  assets/alertmanager-user-workload/alertmanager.yaml
  assets/alertmanager/alertmanager.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/components/alertmanager-user-workload.libsonnet
  jsonnet/components/alertmanager.libsonnet
  jsonnet/components/prometheus-operator.libsonnet
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/components/thanos-querier.libsonnet
  jsonnet/components/thanos-ruler.libsonnet
Labels: lgtm, approved, jira/valid-reference

#2090 OCPBUGS-19059: Enable ipv6 on monitoring-plugin nginx
  assets/monitoring-plugin/config-map.yaml
  jsonnet/components/monitoring-plugin.libsonnet
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2081 OCPBUGS-18390: jsonnet/rules: exclude -1 from etcd objects count
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2086 MON-3383: Remove weak cryptograhic primitive usage
  pkg/alert/rule_controller.go
  pkg/manifests/manifests.go
Labels: lgtm, approved, jira/valid-reference

#2094 Set Thanos version in the Thanos Ruler spec
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/components/thanos-ruler.libsonnet
Labels: lgtm, approved

#2098 chore: fix imports order
  .golangci.yaml
  cmd/operator/main.go
  pkg/alert/relabel_controller.go
  pkg/alert/rule_controller.go
  pkg/client/client.go
  pkg/client/status_reporter.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/tls.go
  pkg/operator/operator.go
  pkg/strings/strings.go
  pkg/tasks/configsharing.go
  pkg/tasks/controlplane.go
  pkg/tasks/helpers.go
  pkg/tasks/metrics_client_ca.go
  pkg/tasks/openshiftstatemetrics.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/prometheusadapter.go
  pkg/tasks/prometheusoperator_user_workload.go
  pkg/tasks/telemeter.go
  test/e2e/alertmanager_helpers.go
  test/e2e/framework/assertions.go
  test/e2e/framework/framework.go
  test/e2e/framework/prometheus.go
Labels: lgtm, approved
