Repository openshift/cluster-monitoring-operator, pull requests merged in 2023-01, with the labels that each got.

#1812 OCPBUGS-1998: pkg/client: Update daemonset degrade condition
  pkg/client/client.go
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-moderate

#1733 MON-2807: Use bearer token file for remote write authentication with telemeter
  assets/prometheus-k8s/telemetry-secret.yaml
  jsonnet/components/prometheus.libsonnet
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheus.go
  test/e2e/framework/client.go
  test/e2e/main_test.go
  test/e2e/prometheus_test.go
  test/e2e/telemeter_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1860 OCPBUGS-4219: Adds runbook link to PrometheusRuleFailures
  CHANGELOG.md
  assets/prometheus-k8s/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-low

#1848 OCPBUGS-4521: check that all targets are up after certificate recreation
  test/e2e/alertmanager_test.go
  test/e2e/framework/framework.go
  test/e2e/main_test.go
  test/e2e/prometheusadapter_test.go
  test/e2e/thanos_querier_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important

#1866 OCPBUGS-5864: grafana: add the Content-Security-Policy header to requests
  assets/grafana/config.yaml
  assets/grafana/deployment.yaml
  jsonnet/main.jsonnet
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#1868 OCPBUGS-5353: unstack dashboards with limit markers.
  CHANGELOG.md
  jsonnet/components/dashboards.libsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1871 OCPBUGS-2729: unify ignored network device list of Node Exporter.
  assets/node-exporter/daemonset.yaml
  jsonnet/components/node-exporter.libsonnet
  jsonnet/main.jsonnet
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1874 Fix 'make run-local' target
  cmd/operator/main.go
  pkg/metrics/server.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
