Repository openshift/cluster-monitoring-operator, pull requests merged in 2023-05, with the labels that each got.

#1929 4.13: OCPBUGS-11294: Add vSphere CSI migration to telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#1960 OCPBUGS-13095: Uncomment cluster:vsphere_infrastructure_failure_domains:max
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1955 OCPBUGS-12727: backport OCPBUGS-5353 to 4.12
  CHANGELOG.md
  jsonnet/components/dashboards.libsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#1972 OCPBUGS-14007: test/e2e: don't fail on telemeter remote write failed samples
  test/e2e/telemeter_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1971 OCPBUGS-13939: Extend remote write test timeout
  test/e2e/prometheus_test.go
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1964 OCPBUGS-13007: Add build number to rules
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1910 OCPBUGS-12903: Add new web console usage metrics
  CHANGELOG.md
  CONTRIBUTING.md
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1961 OCPBUGS-1626: update jsonnet dependencies
  assets/control-plane/minimal-service-monitor-kubelet.yaml
  assets/control-plane/prometheus-rule.yaml
  assets/control-plane/service-monitor-kubelet-resource-metrics.yaml
  assets/control-plane/service-monitor-kubelet.yaml
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/thanos-querier/deployment.yaml
  jsonnet/components/node-exporter.libsonnet
  jsonnet/components/prometheus-operator-user-workload.libsonnet
  jsonnet/components/prometheus-operator.libsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/utils/rbac.libsonnet
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1949 OCPBUGS-13147: Add golangci-lint linters
  .golangci.yaml
  .yamllint
  Makefile
  go.mod
  hack/docgen/model/field.go
  hack/promql_rule/main.go
  hack/tools/tools.go
  pkg/manifests/assets.go
  pkg/operator/operator.go
  pkg/strings/strings.go
  vendor/golang.org/x/text/cases/cases.go
  vendor/golang.org/x/text/cases/context.go
  vendor/golang.org/x/text/cases/fold.go
  vendor/golang.org/x/text/cases/icu.go
  vendor/golang.org/x/text/cases/info.go
  vendor/golang.org/x/text/cases/map.go
  vendor/golang.org/x/text/cases/tables10.0.0.go
  vendor/golang.org/x/text/cases/tables11.0.0.go
  vendor/golang.org/x/text/cases/tables12.0.0.go
  vendor/golang.org/x/text/cases/tables13.0.0.go
  vendor/golang.org/x/text/cases/tables9.0.0.go
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/language/common.go
  vendor/golang.org/x/text/internal/language/compact.go
  vendor/golang.org/x/text/internal/language/compact/compact.go
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/compact/parents.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/compact/tags.go
  vendor/golang.org/x/text/internal/language/compose.go
  vendor/golang.org/x/text/internal/language/coverage.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/match.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/language/tags.go
  vendor/golang.org/x/text/internal/match.go
  vendor/golang.org/x/text/internal/tag/tag.go
  vendor/golang.org/x/text/language/coverage.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/language/tags.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, px-approved, docs-approved, qe-approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#1965 OCPBUGS-13008: Add build number to vcenter version information
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1980 OCPBUGS-14376: Fix golangci-lint ineffassign violations
  pkg/tasks/prometheus.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#1981 OCPBUGS-14377: Fix golangci-int wastedassign violations
  pkg/manifests/manifests.go
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-bug, jira/severity-low, jira/valid-reference
