Repository openshift/cluster-monitoring-operator, pull requests merged in 2023-04, with the labels that each got.

#1930 OCPBUGS-10690: jsonnet: Add prometheus container in UWM
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/components/prometheus-user-workload.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1908 Speedup jsonnet generation by running in parallel
  hack/build-jsonnet.sh
Labels: lgtm, approved, px-approved, docs-approved, qe-approved

#1933 4.14: OCPBUGS-11269: Add CSI migration for vSphere to telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  assets/kube-state-metrics/cluster-role-binding.yaml
  assets/kube-state-metrics/cluster-role.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/kube-state-metrics/minimal-service-monitor.yaml
  assets/kube-state-metrics/prometheus-rule.yaml
  assets/kube-state-metrics/service-account.yaml
  assets/kube-state-metrics/service-monitor.yaml
  assets/kube-state-metrics/service.yaml
  assets/prometheus-k8s/cluster-role-binding.yaml
  assets/prometheus-k8s/cluster-role.yaml
  assets/prometheus-k8s/pod-disruption-budget.yaml
  assets/prometheus-k8s/prometheus-rule-thanos-sidecar.yaml
  assets/prometheus-k8s/prometheus-rule.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/role-binding-config.yaml
  assets/prometheus-k8s/role-binding-specific-namespaces.yaml
  assets/prometheus-k8s/role-config.yaml
  assets/prometheus-k8s/role-specific-namespaces.yaml
  assets/prometheus-k8s/service-account.yaml
  assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
  assets/prometheus-k8s/service-monitor.yaml
  assets/prometheus-k8s/service-thanos-sidecar.yaml
  assets/prometheus-k8s/service.yaml
  assets/prometheus-user-workload/cluster-role-binding.yaml
  assets/prometheus-user-workload/cluster-role.yaml
  assets/prometheus-user-workload/pod-disruption-budget.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/prometheus-user-workload/role-binding-config.yaml
  assets/prometheus-user-workload/role-binding-specific-namespaces.yaml
  assets/prometheus-user-workload/role-config.yaml
  assets/prometheus-user-workload/role-specific-namespaces.yaml
  assets/prometheus-user-workload/service-account.yaml
  assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
  assets/prometheus-user-workload/service-monitor.yaml
  assets/prometheus-user-workload/service-thanos-sidecar.yaml
  assets/prometheus-user-workload/service.yaml
  assets/thanos-querier/cluster-role-binding.yaml
  assets/thanos-querier/cluster-role.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-querier/grpc-tls-secret.yaml
  assets/thanos-querier/kube-rbac-proxy-rules-secret.yaml
  assets/thanos-querier/kube-rbac-proxy-secret.yaml
  assets/thanos-querier/oauth-cookie-secret.yaml
  assets/thanos-querier/pod-disruption-budget.yaml
  assets/thanos-querier/prometheus-rule.yaml
  assets/thanos-querier/route.yaml
  assets/thanos-querier/service-account.yaml
  assets/thanos-querier/service-monitor.yaml
  assets/thanos-querier/service.yaml
  assets/thanos-ruler/service-account.yaml
  assets/thanos-ruler/service-monitor.yaml
  assets/thanos-ruler/service.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/rules.libsonnet
  jsonnet/versions.yaml
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-important, jira/valid-reference

#1923 OCPBUGS-10895: add startup probe for prometheus-adapter
  assets/prometheus-adapter/deployment.yaml
  jsonnet/components/prometheus-adapter.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1937 OCPBUGS-11434: node-exporter: disable btrfs collector
  CHANGELOG.md
  assets/node-exporter/daemonset.yaml
  jsonnet/components/node-exporter.libsonnet
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1943 jsonnet: add comment why empty prometheus container needed
  jsonnet/components/prometheus-user-workload.libsonnet
Labels: lgtm, approved, px-approved, docs-approved, qe-approved
