Repository openshift/cluster-monitoring-operator, pull requests merged in 2023-10, with the labels that each got.

#2095 OCPVE-711: feat: add olm capability annotation
  manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml
Labels: lgtm, approved, jira/valid-reference

#2102 MON-3270: Add kube-metrics-server to image-references
  hack/generate-versions.sh
  jsonnet/versions.yaml
  manifests/image-references
Labels: lgtm, approved, jira/valid-reference

#2103 Revert "feat: add olm capability annotation"
  manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml
Labels: lgtm, approved

#2104 Remove bparees from approvers
  OWNERS
Labels: lgtm, approved

#2083 add `machine424` and `rexagod` to OWNERS
  OWNERS
Labels: lgtm, approved

#2062 MON-3302: add RHACS telemetry metrics
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-reference

#2101 OCPBUGS-18326: add console capability annotation to dashboards and monitoring-plugin.
  jsonnet/components/dashboards.libsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2108 Remove deprecated ioutil
  test/e2e/alertmanager_test.go
  test/e2e/framework/client.go
  test/e2e/thanos_ruler_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved

#2111 OCPBUGS-11344: alertmanager: use alertmanager CRD's automountServiceAccountToken option
  assets/alertmanager/alertmanager.yaml
  assets/alertmanager/service-account.yaml
  jsonnet/components/alertmanager.libsonnet
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2113 [OCPBUGS-20221] Change kube-rbac-proxy-thanos port
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/components/prometheus.libsonnet
Labels: lgtm, approved

#2112 build: add `-e` to `go list` command to install tools
  Makefile
Labels: lgtm, approved

#2099 OCPBUGS-17850: replace nonResourceURLs permissions by subresource
  assets/alertmanager-user-workload/alertmanager.yaml
  assets/alertmanager-user-workload/kube-rbac-proxy-secret.yaml
  assets/cluster-monitoring-operator/user-workload-alertmanager-api-reader.yaml
  assets/cluster-monitoring-operator/user-workload-alertmanager-api-writer.yaml
  assets/prometheus-user-workload/alertmanager-user-workload-role-binding.yaml
  assets/prometheus-user-workload/cluster-role.yaml
  assets/thanos-ruler/alertmanager-user-workload-role-binding.yaml
  assets/thanos-ruler/cluster-role.yaml
  jsonnet/components/alertmanager-user-workload.libsonnet
  jsonnet/components/cluster-monitoring-operator.libsonnet
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/thanos-ruler.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-namespaced-cluster-role.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/alertmanager_user_workload.go
  pkg/tasks/clustermonitoringoperator.go
  pkg/tasks/prometheus_user_workload.go
  pkg/tasks/thanos_ruler_user_workload.go
  test/e2e/alertmanager_user_workload_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2116 MON-3286: Remove no longer needed code.
  pkg/client/client.go
  pkg/tasks/controlplane.go
Labels: lgtm, approved, jira/valid-reference

#2118 OCPBUGS-18326: revert previous fix to avoid activating console capability during update
  jsonnet/components/dashboards.libsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2110 OCPBUGS-20073: Limit the value of GOMAXPROCS on node-exporter to 4
  assets/node-exporter/daemonset.yaml
  jsonnet/components/node-exporter.libsonnet
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2105 OCPVE-711: feat: add olm capability annotation
  manifests/0000_90_cluster-monitoring-operator_00-operatorgroup.yaml
Labels: lgtm, approved, jira/valid-reference

#2128 fix: force HTTP/1.1 connections
  pkg/metrics/server.go
Labels: lgtm, approved

#2132 MON-3422: Remove temporary no more needed code
  assets/prometheus-operator/operator-certs-ca-bundle.yaml
  jsonnet/components/prometheus-operator.libsonnet
  pkg/manifests/manifests.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheusoperator.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: lgtm, approved, jira/valid-reference

#2117 OCPBUGS-4069: Prometheus Adatper takes metrics from kubelet job only.
  assets/prometheus-adapter/config-map-dedicated-service-monitors.yaml
  assets/prometheus-adapter/config-map.yaml
  assets/prometheus-adapter/deployment.yaml
  jsonnet/main.jsonnet
Labels: lgtm, approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#2131 Fix UWM alert access permissions
  assets/prometheus-user-workload/alertmanager-user-workload-role-binding.yaml
  jsonnet/components/prometheus-user-workload.libsonnet
  test/e2e/alertmanager_user_workload_test.go
Labels: lgtm, approved, px-approved, docs-approved
