Repository openshift/cluster-monitoring-operator, pull requests merged in 2024-05, with the labels that each got.

#2335 AUTH-482: set required-scc for openshift workloads
  assets/admission-webhook/deployment.yaml
  assets/alertmanager/alertmanager.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/monitoring-plugin/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/openshift-state-metrics/deployment.yaml
  assets/prometheus-adapter/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/telemeter-client/deployment.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/components/admission-webhook.libsonnet
  jsonnet/components/alertmanager.libsonnet
  jsonnet/components/kube-state-metrics.libsonnet
  jsonnet/components/monitoring-plugin.libsonnet
  jsonnet/components/node-exporter.libsonnet
  jsonnet/components/openshift-state-metrics.libsonnet
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/components/prometheus-operator-user-workload.libsonnet
  jsonnet/components/prometheus-operator.libsonnet
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/components/telemeter-client.libsonnet
  jsonnet/components/thanos-querier.libsonnet
  jsonnet/components/thanos-ruler.libsonnet
  manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
Labels: lgtm, approved, jira/valid-reference

#2334 OCPBUGS-32510: tweak Prometheus RBAC setup as a temp fix.
  assets/metrics-server/deployment.yaml
  jsonnet/components/metrics-server.libsonnet
  pkg/tasks/metricsserver.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2343 OCPBUGS-33512: fix Thanos ruler alert generator url
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2337 OCPBUGS-32510: change metrics-server probes for SNO
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2348 MON-3861: Bump go tools 1.21
  hack/tools/go.mod
  hack/tools/go.sum
Labels: lgtm, approved, docs-approved, jira/valid-reference, acknowledge-critical-fixes-only

#2353 : NO-JIRA: Fix formatting in the resources documentation
  Documentation/resources.adoc
  Documentation/resources.md
  assets/thanos-querier/service.yaml
  jsonnet/components/thanos-querier.libsonnet
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2291 MON-3763: Add cnv_abnormal
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2346 OCPBUGS-23000: node-exporter: Prevent cluster-autoscaler from evicting
  assets/node-exporter/daemonset.yaml
  jsonnet/components/node-exporter.libsonnet
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2355 OCPBUGS-33955: remove deprecated logtostderr argument
  assets/alertmanager-user-workload/alertmanager.yaml
  assets/openshift-state-metrics/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  hack/local-cmo.sh
  hack/ocp-images.sh
  jsonnet/components/alertmanager-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#2360 MON-3701: clean-up tests
  manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, jira/valid-reference

#2356 MON-3874: chore: poll immediately in the e2e tests
  test/e2e/alertmanager_test.go
  test/e2e/alertmanager_user_workload_test.go
  test/e2e/framework/assertions.go
  test/e2e/framework/framework.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, jira/valid-reference

#2362 MON-3701: clean-up injection of CA bundle for user Prometheus
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/components/prometheus-user-workload.libsonnet
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheus_user_workload.go
Labels: lgtm, approved, jira/valid-reference

#2359 MON-3801: clean-up unused OAuth proxy references
  assets/alertmanager/service-account.yaml
  assets/cluster-monitoring-operator/monitoring-alertmanager-edit-role.yaml
  assets/prometheus-k8s/service-account.yaml
  assets/thanos-querier/service-account.yaml
  jsonnet/components/alertmanager.libsonnet
  jsonnet/components/cluster-monitoring-operator.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/components/thanos-querier.libsonnet
  pkg/tasks/alertmanager.go
  pkg/tasks/prometheus.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: lgtm, approved, jira/valid-reference

#2366 MON-3881: chore: remove hack/ocp-images.sh
  hack/ocp-images.sh
Labels: lgtm, approved, jira/valid-reference

#2349 OCPBUGS-33645: inject trusted CA bundle into UWM Alertmanager
  assets/alertmanager-user-workload/alertmanager.yaml
  jsonnet/components/alertmanager-user-workload.libsonnet
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2374 [release-4.14] OCPBUGS-34023: fix KRP permissions for Thanos Querier
  assets/thanos-querier/kube-rbac-proxy-secret.yaml
  jsonnet/components/thanos-querier.libsonnet
  test/e2e/framework/framework.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2361 MON-3701: clean-up injection of CA bundle for user Alertmanager
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/alertmanager_user_workload.go
Labels: lgtm, approved, jira/valid-reference

#2375 MON-3888: bump go tools 1.22
  hack/tools/go.mod
Labels: lgtm, approved, qe-approved, jira/valid-reference
