Repository openshift/cluster-monitoring-operator, pull requests merged in 2024-08, with the labels that each got.

#2403 MON-3921: Revert "Revert "Merge pull request #2392 from machine424/f-…
  assets/prometheus-k8s/prometheus-rule.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
Labels: lgtm, approved, jira/valid-reference

#2426 NO-JIRA: fix: fix a small typo
  jsonnet/components/prometheus.libsonnet
Labels: lgtm, approved, jira/valid-reference

#2425 MON-3900: follow-up: clean up operator logic and some tests now that metrics-server is the default Metrics API backend
  pkg/operator/operator.go
  pkg/tasks/metricsserver.go
  test/e2e/framework/helpers.go
  test/e2e/metrics_adapter_test.go
  test/e2e/tls_security_profile_test.go
Labels: lgtm, approved, jira/valid-reference

#2424 MON-3961: inject proxy env variables in Alertmanager
  assets/alertmanager-user-workload/alertmanager.yaml
  assets/alertmanager/alertmanager.yaml
  jsonnet/components/alertmanager-user-workload.libsonnet
  jsonnet/components/alertmanager.libsonnet
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, jira/valid-reference

#2429 MON-3964: set scrape timestamp tolerance for user workload monitoring
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
Labels: lgtm, approved, jira/valid-reference

#2417 OCPBUGS-17506: Make error messages clearer on poll timeouts
  pkg/client/client.go
  pkg/client/client_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2420 [release-4.15] OCPBUGS-37608: set required-scc for openshift workloads
  assets/admission-webhook/deployment.yaml
  assets/alertmanager/alertmanager.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/monitoring-plugin/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/openshift-state-metrics/deployment.yaml
  assets/prometheus-adapter/deployment.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/telemeter-client/deployment.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/components/admission-webhook.libsonnet
  jsonnet/components/alertmanager.libsonnet
  jsonnet/components/kube-state-metrics.libsonnet
  jsonnet/components/monitoring-plugin.libsonnet
  jsonnet/components/node-exporter.libsonnet
  jsonnet/components/openshift-state-metrics.libsonnet
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/components/prometheus-operator-user-workload.libsonnet
  jsonnet/components/prometheus-operator.libsonnet
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/components/telemeter-client.libsonnet
  jsonnet/components/thanos-querier.libsonnet
  jsonnet/components/thanos-ruler.libsonnet
  manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2433 [release-4.14] OCPBUGS-37468: Backport of PR #2384
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2265 HOSTEDCP-1044: Add nodepools telemetry metrics for HyperShift
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-reference

#2436 OCPBUGS-33863: use UserWorkloadInvalidConfiguration reason when UWM config only is invalid
  pkg/operator/operator.go
  test/e2e/config_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2431 MON-3962: set proxy_from_environment to true
  assets/alertmanager-user-workload/secret.yaml
  assets/alertmanager/secret.yaml
  jsonnet/main.jsonnet
Labels: lgtm, approved, jira/valid-reference

#2441 OCPBUGS-38289: fix(prometheus): avoid passing the cluster-wide proxy config to a remote endpoint when noProxy will prevent the proxuying anyway
  Documentation/api.md
  Documentation/openshiftdocs/modules/remotewritespec.adoc
  go.mod
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#2442 OCPBUGS-38780: update links to OpenShift documentation
  Documentation/data-collection.md
  README.md
  pkg/operator/operator.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2421 MON-3895: Add tempo operator metrics
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-reference

#2445 OCPBUGS-39029: Backport #2441 for 4.17
  Documentation/api.md
  Documentation/openshiftdocs/modules/remotewritespec.adoc
  go.mod
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2444 MON-3990: make TestClusterMonitorConsolePlugin check that one of the pods can serve /plugin-manifest.json
  test/e2e/config_test.go
Labels: lgtm, approved, jira/valid-reference
