Repository openshift/cluster-monitoring-operator, pull requests merged in 2024-11, with the labels that each got.

#2512 MON-4051: Add new metrics for OpenShift logging telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-reference

#2514 OCPBUGS-27250: bump prometheus-operator to v0.78.1
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#2494 OCPBUGS-43690: chore: introduce a config parsing check via a strict unmarshaller for…
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests_test.go
  pkg/manifests/testdata/cluster-monitoring-config.yaml
  pkg/manifests/testdata/cluster-monitoring-configmap.yaml
  pkg/manifests/testdata/user-workload-configmap.yaml
  pkg/manifests/testdata/user-workload-monitoring-config.yaml
  pkg/operator/operator.go
  test/e2e/config_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2503 MON-4057: Expose `scrapeInterval` setting for UWM Prometheus
  CHANGELOG.md
  Documentation/api.md
  Documentation/openshiftdocs/modules/prometheusrestrictedconfig.adoc
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
  pkg/operator/operator.go
  test/e2e/config_test.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2515 MON-4078: report vendor_model:node_accelerator_cards:sum to Telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  assets/node-exporter/prometheus-rule.yaml
  jsonnet/components/node-exporter.libsonnet
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-reference

#2517 MON-4058: Expose evaluationInterval setting for UWM Prometheus and ThanosRuler
  CHANGELOG.md
  Documentation/api.md
  Documentation/openshiftdocs/modules/prometheusrestrictedconfig.adoc
  Documentation/openshiftdocs/modules/thanosrulerconfig.adoc
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
  test/e2e/config_test.go
Labels: lgtm, approved, jira/valid-reference

#2468 MON-3934: make TestImageRegistryPods more robust and split it into Pl…
  test/e2e/framework/helpers.go
  test/e2e/image_registry_test.go
  test/e2e/prometheus_test.go
  test/e2e/thanos_ruler_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, jira/valid-reference

#2511 OCPBUGS-44003: fix(monitoring-plugin): disable emitting nginx version on error pages
  assets/monitoring-plugin/config-map.yaml
  jsonnet/components/monitoring-plugin.libsonnet
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2518 MON-4058: Fix api-docs for ThanosRuler EvaluationInterval
  Documentation/api.md
  Documentation/openshiftdocs/modules/thanosrulerconfig.adoc
  pkg/manifests/types.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2523 OCPBUGS-38655: take cluster proxy into account for UWM Prometheus rem…
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#2498 AUTH-482: set required-scc for openshift workloads
  assets/metrics-server/deployment.yaml
  jsonnet/components/metrics-server.libsonnet
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2492 NO-JIRA: use scrape class to avoid TLS config repetitions
  assets/alertmanager-user-workload/service-monitor.yaml
  assets/alertmanager/service-monitor.yaml
  assets/cluster-monitoring-operator/service-monitor.yaml
  assets/control-plane/minimal-service-monitor-kubelet.yaml
  assets/control-plane/service-monitor-kubelet.yaml
  assets/kube-state-metrics/minimal-service-monitor.yaml
  assets/kube-state-metrics/service-monitor.yaml
  assets/metrics-server/service-monitor.yaml
  assets/node-exporter/minimal-service-monitor.yaml
  assets/node-exporter/service-monitor.yaml
  assets/openshift-state-metrics/service-monitor.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/service-monitor-thanos-sidecar.yaml
  assets/prometheus-k8s/service-monitor.yaml
  assets/prometheus-operator-user-workload/service-monitor.yaml
  assets/prometheus-operator/service-monitor.yaml
  assets/prometheus-user-workload/service-monitor-thanos-sidecar.yaml
  assets/prometheus-user-workload/service-monitor.yaml
  assets/telemeter-client/service-monitor.yaml
  assets/thanos-querier/service-monitor.yaml
  assets/thanos-ruler/service-monitor.yaml
  jsonnet/components/alertmanager-user-workload.libsonnet
  jsonnet/components/alertmanager.libsonnet
  jsonnet/components/cluster-monitoring-operator.libsonnet
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/utils/configure-authentication-for-monitors.libsonnet
Labels: lgtm, approved, jira/valid-reference

#2522 OCPBUGS-44831: disable token automount for alertmanager-user-workload SA
  assets/alertmanager-user-workload/alertmanager.yaml
  assets/alertmanager-user-workload/service-account.yaml
  jsonnet/components/alertmanager-user-workload.libsonnet
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference
