Repository openshift/cluster-monitoring-operator, pull requests merged in 2024-10, with the labels that each got.

#2480 OCPBUGS-30122: chore: Bump to prometheus-operator 0.77.1
  assets/prometheus-operator-user-workload/cluster-role.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/cluster-role.yaml
  assets/prometheus-operator/deployment.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2453 MON-3991: set noProxy for Prometheus remote-write via the CR.
  Documentation/api.md
  Documentation/openshiftdocs/modules/remotewritespec.adoc
  go.mod
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-reference

#2307 MON-3802: implement cross-namespace rules for UWM
  CONTRIBUTING.md
  Documentation/api.md
  Documentation/openshiftdocs/index.adoc
  Documentation/openshiftdocs/modules/clustermonitoringconfiguration.adoc
  Documentation/openshiftdocs/modules/userworkloadconfig.adoc
  Documentation/openshiftdocs/modules/userworkloadconfiguration.adoc
  assets/thanos-querier/deployment.yaml
  jsonnet/components/thanos-querier.libsonnet
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/types.go
  test/e2e/alertmanager_helpers.go
  test/e2e/alertmanager_test.go
  test/e2e/image_registry_test.go
  test/e2e/user_workload_monitoring_test.go
  test/e2e/uwm_helpers.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2485 MON-3523: Disable http2 in metrics-server by default
  assets/metrics-server/deployment.yaml
  jsonnet/components/metrics-server.libsonnet
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2486 NO-JIRA: [bot] Update jsonnet dependencies
  assets/control-plane/service-monitor-kubelet.yaml
  assets/prometheus-k8s/cluster-role.yaml
  assets/prometheus-user-workload/cluster-role.yaml
  assets/thanos-querier/prometheus-rule.yaml
  jsonnet/components/control-plane.libsonnet
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, jira/valid-reference

#2489 [release-4.14] OCPBUGS-42603: Exclude windows nodes from kubelet servicemonitor
  assets/control-plane/minimal-service-monitor-kubelet.yaml
  assets/control-plane/service-monitor-kubelet-resource-metrics.yaml
  assets/control-plane/service-monitor-kubelet.yaml
  assets/prometheus-k8s/cluster-role.yaml
  jsonnet/components/control-plane.libsonnet
  jsonnet/components/prometheus.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2495 NO-JIRA: fix CMO config for Alertmanager e2e tests
  test/e2e/alertmanager_test.go
Labels: lgtm, approved, jira/valid-reference

#2443 MON-4021: feat: add the required utils for automated tests and integration with the docs
  Documentation/resources.adoc
  Documentation/resources.md
  assets/alertmanager/service.yaml
  go.mod
  go.sum
  hack/docgen/managed_resources.go
  jsonnet/components/alertmanager.libsonnet
  jsonnet/utils/add-annotations.libsonnet
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/e2e/doc_examples_test.go
  test/e2e/framework/framework.go
  test/e2e/test_command/scripts/openshift-monitoring_alertmanager-main_service_port_9094.yaml
  test/e2e/test_command/test_command.go
  vendor/github.com/mattn/go-shellwords/.travis.yml
  vendor/github.com/mattn/go-shellwords/LICENSE
  vendor/github.com/mattn/go-shellwords/README.md
  vendor/github.com/mattn/go-shellwords/go.test.sh
  vendor/github.com/mattn/go-shellwords/shellwords.go
  vendor/github.com/mattn/go-shellwords/util_posix.go
  vendor/github.com/mattn/go-shellwords/util_windows.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2292 MON-3850: Lint CMO tests
  .golangci.yaml
  pkg/client/client_test.go
Labels: lgtm, approved, jira/valid-reference

#2500 OCPBUGS-42148: Fix api doc on Thanos Ruler default retention
  Documentation/api.md
  Documentation/openshiftdocs/modules/thanosrulerconfig.adoc
  pkg/manifests/types.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#2493 OCPBUGS-42671: make config unmarshalling more strict to help detect
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests_test.go
  pkg/manifests/testdata/cluster-monitoring-config.yaml
  pkg/manifests/testdata/cluster-monitoring-configmap.yaml
  pkg/manifests/testdata/user-workload-configmap.yaml
  pkg/manifests/testdata/user-workload-monitoring-config.yaml
  pkg/operator/operator.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#2501 [release-4.17] OCPBUGS-43545: Fix api doc on Thanos Ruler default retention
  Documentation/api.md
  Documentation/openshiftdocs/modules/thanosrulerconfig.adoc
  pkg/manifests/types.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-low, jira/valid-reference

#2496 OCPBUGS-43678: Remove temporary no more needed code
  assets/prometheus-operator/operator-certs-ca-bundle.yaml
  jsonnet/components/prometheus-operator.libsonnet
  pkg/manifests/manifests.go
  pkg/tasks/prometheus.go
  pkg/tasks/prometheusoperator.go
  pkg/tasks/thanos_querier.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2502 MON-4060: Bump prometheus-operator to v0.77.2
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, jira/valid-reference

#2506 OCPBUGS-18007: Add runbook url for TelemeterClientFailures
  assets/telemeter-client/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2509 [release-4.15] OCPBUGS-43876: Add runbook url for TelemeterClientFail…
  assets/telemeter-client/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
