Repository openshift/cluster-monitoring-operator, pull requests merged in 2024-07, with the labels that each got.

#2393 MON-3914: add a regression test for gogc based on the go_gc_gogc_percent metric
  test/e2e/prometheus_test.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2400 [release-4.15] OCPBUGS-36312: inject trusted CA bundle into UWM Alertmanager
  assets/alertmanager-user-workload/alertmanager.yaml
  jsonnet/components/alertmanager-user-workload.libsonnet
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2401 OCPBUGS-36406: add runbook_url annotations
  assets/prometheus-k8s/prometheus-rule.yaml
  assets/prometheus-operator/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2402 [release-4.14] OCPBUGS-36416: inject trusted CA bundle into UWM Alertmanager
  assets/alertmanager-user-workload/alertmanager.yaml
  jsonnet/components/alertmanager-user-workload.libsonnet
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2368 OCPBUGS-31250: Exclude windows nodes from kubelet servicemonitor
  assets/control-plane/minimal-service-monitor-kubelet.yaml
  assets/control-plane/service-monitor-kubelet.yaml
  assets/prometheus-k8s/cluster-role.yaml
  jsonnet/components/control-plane.libsonnet
  jsonnet/components/prometheus.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2410 OCPBUGS-36495: Add deprecated config runbook
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2377 MON-2065: jsonnet: exclude `kubernetes-storage` rules
  assets/control-plane/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, jira/valid-reference

#2416 MON-3947: Bump prometheus-operator to 0.75.1
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2406 [release-4.15] OCPBUGS-36563: add runbook_url annotations
  assets/prometheus-k8s/prometheus-rule.yaml
  assets/prometheus-operator/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2409 MON-3900: Remove prometheus-adapter code
  .github/ISSUE_TEMPLATE/release.md
  CHANGELOG.md
  Documentation/api.md
  Documentation/deps-versions.md
  Documentation/openshiftdocs/modules/clustermonitoringconfiguration.adoc
  Documentation/openshiftdocs/modules/k8sprometheusadapter.adoc
  Documentation/resources.adoc
  Documentation/resources.md
  README.md
  assets/prometheus-adapter/api-service.yaml
  assets/prometheus-adapter/cluster-role-binding-delegator.yaml
  assets/prometheus-adapter/cluster-role-binding-view.yaml
  assets/prometheus-adapter/cluster-role-binding.yaml
  assets/prometheus-adapter/cluster-role-server-resources.yaml
  assets/prometheus-adapter/cluster-role.yaml
  assets/prometheus-adapter/config-map.yaml
  assets/prometheus-adapter/configmap-audit-profiles.yaml
  assets/prometheus-adapter/configmap-prometheus.yaml
  assets/prometheus-adapter/deployment.yaml
  assets/prometheus-adapter/minimal-service-monitor.yaml
  assets/prometheus-adapter/pod-disruption-budget.yaml
  assets/prometheus-adapter/role-binding-auth-reader.yaml
  assets/prometheus-adapter/service-account.yaml
  assets/prometheus-adapter/service-monitor.yaml
  assets/prometheus-adapter/service.yaml
  jsonnet/components/prometheus-adapter-audit.libsonnet
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/main.jsonnet
  jsonnet/versions.yaml
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment-ibm-cloud-managed.yaml
  manifests/0000_50_cluster-monitoring-operator_05-deployment.yaml
  manifests/image-references
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
  pkg/operator/operator.go
  pkg/tasks/metricsserver.go
  pkg/tasks/prometheusadapter.go
  test/e2e/config_test.go
  test/e2e/metrics_adapter_test.go
  test/e2e/prometheus_test.go
  test/e2e/tls_security_profile_test.go
Labels: lgtm, approved, jira/valid-reference

#2407 [release-4.14] OCPBUGS-36565: add runbook_url annotations
  assets/prometheus-k8s/prometheus-rule.yaml
  assets/prometheus-operator/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
