Repository openshift/cluster-monitoring-operator, pull requests merged in 2024-09, with the labels that each got.

#2447 OCPBUGS-39170: Backport #2441 for 4.16
  Documentation/api.md
  Documentation/openshiftdocs/modules/remotewritespec.adoc
  go.mod
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2448 OCPBUGS-39172: Backport #2441 for 4.15
  Documentation/api.md
  Documentation/openshiftdocs/modules/remotewritespec.adoc
  go.mod
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2449 OCPBUGS-39176: Backport #2441 for 4.14
  Documentation/api.md
  Documentation/openshiftdocs/modules/remotewritespec.adoc
  go.mod
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#2456 NO-JIRA: Update README.md
  README.md
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2412 OU-450: Migrate Monitoring Plugin Deployment from nginx to Go server
  assets/monitoring-plugin/config-map.yaml
  assets/monitoring-plugin/deployment.yaml
  jsonnet/components/monitoring-plugin.libsonnet
  pkg/manifests/manifests.go
  pkg/tasks/monitoring_plugin.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2452 OCPBUGS-39126: disable user-defined monitoring per object
  assets/prometheus-user-workload/prometheus.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/thanos-ruler.libsonnet
  jsonnet/main.jsonnet
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  test/e2e/user_workload_monitoring_test.go
  test/e2e/uwm_helpers.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2460 OCPBUGS-39133: Configure graceful shutdown for metrics-server
  assets/metrics-server/deployment.yaml
  jsonnet/components/metrics-server.libsonnet
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2463 OCPBUGS-41580: Configure graceful shutdown for metrics-server (4.17 backport)
  assets/metrics-server/deployment.yaml
  jsonnet/components/metrics-server.libsonnet
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2466 OCPBUGS-39246: filter alerts sent to Telemeter
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2470 [release-4.17] OCPBUGS-41908: filter alerts sent to Telemeter
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2469 MON-3367: chore: enable delayed-compaction feature flag on Platform and UWM Prometheuses
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
  test/e2e/config_test.go
Labels: lgtm, approved, jira/valid-reference

#2471 [release-4.16] OCPBUGS-41910: filter alerts sent to Telemeter
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2472 [release-4.15] OCPBUGS-41913: filter alerts sent to Telemeter
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2473 [release-4.14] OCPBUGS-41916: filter alerts sent to Telemeter
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2478 NO-JIRA: remove 4.17 TODOs
  pkg/operator/operator.go
  pkg/tasks/alertmanager_user_workload.go
  pkg/tasks/prometheus_user_workload.go
Labels: lgtm, approved, jira/valid-reference

#2479 NO-JIRA: clean-up generated dashboards
  jsonnet/components/dashboards.libsonnet
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, jira/valid-reference

#2476 OCPBUGS-42067: Reapply "chore: poll immediately in the e2e tests"
  test/e2e/alertmanager_test.go
  test/e2e/alertmanager_user_workload_test.go
  test/e2e/framework/assertions.go
  test/e2e/framework/framework.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2450 MON-3896: Add OpenTelemetry operator metrics
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-reference

#2475 OCPBUGS-41158: add pod-metrics-reader cluster role
  assets/cluster-monitoring-operator/cluster-role-pod-metrics-reader.yaml
  jsonnet/components/cluster-monitoring-operator.libsonnet
  jsonnet/main.jsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/manifests/manifests.go
  pkg/tasks/clustermonitoringoperator.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2482 NO-JIRA: vendor Kubernetes dashboards
  jsonnet/main.jsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
  manifests/0000_90_cluster-monitoring-operator_02-dashboards.yaml
Labels: lgtm, approved, jira/valid-reference
