Repository openshift/cluster-monitoring-operator, pull requests merged in 2024-02, with the labels that each got.

#2251 MON-3697: use `maximumStartupDurationSeconds` instead of container patch
  assets/prometheus-k8s/prometheus.yaml
  jsonnet/components/prometheus.libsonnet
  pkg/manifests/manifests.go
Labels: lgtm, approved, jira/valid-reference

#2247 MON-3699: chore: merge OmitFromDoc with HideFromDoc introduced in https://github.com/https://github.com/openshift/cluster-monitoring-operator/pull/2210 to hide fields from the doc
  hack/docgen/format/asciidocs/api.go
  hack/docgen/format/markdown/api.go
  hack/docgen/model/parser.go
  pkg/manifests/types.go
Labels: lgtm, approved, jira/valid-reference

#2149 OCPBUGS-21423: Set the new --disable-http2 flag for prometheus-adapter to disable HTTP2
  assets/prometheus-adapter/deployment.yaml
  jsonnet/components/prometheus-adapter.libsonnet
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2229 OCPNODE-2022: jsonnet: update crio port to TLS port 9637
  assets/control-plane/minimal-service-monitor-kubelet.yaml
  assets/control-plane/service-monitor-kubelet.yaml
  jsonnet/components/control-plane.libsonnet
  jsonnet/utils/configure-authentication-for-monitors.libsonnet
Labels: lgtm, approved, jira/valid-reference

#2249 [release-4.15] OCPBUGS-28703: rollout metrics-server on cert rotations
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/metricsserver.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2255 TRT-1489: Revert "jsonnet: update crio port to TLS port 9637"
  assets/control-plane/minimal-service-monitor-kubelet.yaml
  assets/control-plane/service-monitor-kubelet.yaml
  jsonnet/components/control-plane.libsonnet
  jsonnet/utils/configure-authentication-for-monitors.libsonnet
Labels: lgtm, approved, jira/valid-reference

#2254 OCPBUGS-18326: add Console cap annotation to dashboards
  jsonnet/components/dashboards.libsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-low, jira/valid-reference

#2246 MON-3380: replace OAuth proxy for prometheus-k8s
  assets/cluster-monitoring-operator/cluster-role-view.yaml
  assets/prometheus-k8s/kube-rbac-proxy-secret.yaml
  assets/prometheus-k8s/kube-rbac-proxy-web-secret.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-k8s/proxy-secret.yaml
  assets/prometheus-k8s/service-account.yaml
  assets/prometheus-k8s/service-monitor.yaml
  assets/prometheus-k8s/service.yaml
  assets/telemeter-client/deployment.yaml
  assets/thanos-querier/kube-rbac-proxy-metric-secret.yaml
  assets/thanos-querier/kube-rbac-proxy-web-secret.yaml
  jsonnet/components/cluster-monitoring-operator.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/components/telemeter-client.libsonnet
  jsonnet/components/thanos-querier.libsonnet
  jsonnet/utils/generate-secret.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/prometheus.go
  pkg/tasks/thanos_querier.go
  test/e2e/security_headers_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, jira/valid-reference

#2258 MON-3706: chore: poll immediately in the e2e tests
  test/e2e/alertmanager_test.go
  test/e2e/alertmanager_user_workload_test.go
  test/e2e/framework/assertions.go
  test/e2e/framework/framework.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, jira/valid-reference

#2188 MON-3172: describe monitoring services
  Documentation/resources.adoc
  Documentation/resources.md
  Makefile
  assets/admission-webhook/service.yaml
  assets/alertmanager-user-workload/service.yaml
  assets/alertmanager/route.yaml
  assets/alertmanager/service.yaml
  assets/kube-state-metrics/service.yaml
  assets/metrics-server/service.yaml
  assets/monitoring-plugin/service.yaml
  assets/node-exporter/service.yaml
  assets/openshift-state-metrics/service.yaml
  assets/prometheus-adapter/service.yaml
  assets/prometheus-k8s/api-route.yaml
  assets/prometheus-k8s/federate-route.yaml
  assets/prometheus-k8s/service.yaml
  assets/prometheus-operator-user-workload/service.yaml
  assets/prometheus-operator/service.yaml
  assets/prometheus-user-workload/federate-route.yaml
  assets/prometheus-user-workload/service.yaml
  assets/telemeter-client/service.yaml
  assets/thanos-querier/route.yaml
  assets/thanos-querier/service.yaml
  assets/thanos-ruler/route.yaml
  assets/thanos-ruler/service.yaml
  hack/docgen/README.md
  hack/docgen/main.go
  hack/docgen/managed_resources.go
  jsonnet/components/admission-webhook.libsonnet
  jsonnet/components/alertmanager-user-workload.libsonnet
  jsonnet/components/alertmanager.libsonnet
  jsonnet/components/kube-state-metrics.libsonnet
  jsonnet/components/metrics-server.libsonnet
  jsonnet/components/monitoring-plugin.libsonnet
  jsonnet/components/node-exporter.libsonnet
  jsonnet/components/openshift-state-metrics.libsonnet
  jsonnet/components/prometheus-adapter.libsonnet
  jsonnet/components/prometheus-operator-user-workload.libsonnet
  jsonnet/components/prometheus-operator.libsonnet
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
  jsonnet/components/telemeter-client.libsonnet
  jsonnet/components/thanos-querier.libsonnet
  jsonnet/components/thanos-ruler.libsonnet
  jsonnet/utils/add-annotations.libsonnet
  manifests/0000_50_cluster-monitoring-operator_03-service.yaml
Labels: lgtm, approved, docs-approved, jira/valid-reference

#2226 MON-3717: pkg/client.go: make some CreateOrUpdateXXX functions use library-go’s resourceapply utils.
  Documentation/development.md
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/manifests/tls.go
  test/e2e/framework/framework.go
Labels: lgtm, approved, jira/valid-reference
