Repository openshift/cluster-monitoring-operator, pull requests merged in 2024-12, with the labels that each got.

#2529 OCPBUGS-45179: Use explicit name label for logging telemetry metrics
  Documentation/data-collection.md
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#2524 OCPBUGS-35726: remove certificate hash annotation for monitoring-plugin
  pkg/manifests/manifests.go
  pkg/tasks/monitoring_plugin.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2528 OCPBUGS-44724: Use explicit name label for logging telemetry metrics
  Documentation/data-collection.md
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2526 OCPBUGS-44971: Add new metrics for OpenShift logging telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2533 OCPBUGS-45389: update image to be consistent with ART for 4.19
  .ci-operator.yaml
  Dockerfile
  Makefile
  hack/docgen/model/parser.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2422 OCPBUGS-35095: unpin `kubernetes-mixin`
  Documentation/deps-versions.md
  assets/alertmanager-user-workload/alertmanager.yaml
  assets/alertmanager/alertmanager.yaml
  assets/control-plane/prometheus-rule.yaml
  assets/kube-state-metrics/deployment.yaml
  assets/node-exporter/daemonset.yaml
  assets/openshift-state-metrics/deployment.yaml
  assets/prometheus-k8s/prometheus-rule.yaml
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-operator-user-workload/deployment.yaml
  assets/prometheus-operator/deployment.yaml
  assets/prometheus-user-workload/prometheus.yaml
  assets/telemeter-client/deployment.yaml
  assets/thanos-querier/deployment.yaml
  assets/thanos-ruler/thanos-ruler.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/versions.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2530 MGMT-19498: Adding accelerators configuration file to the node-exporter
  assets/node-exporter/accelerators-collector-configmap.yaml
  assets/node-exporter/daemonset.yaml
  jsonnet/components/node-exporter.libsonnet
  pkg/manifests/manifests.go
  pkg/tasks/nodeexporter.go
Labels: lgtm, approved, jira/valid-reference

#2538 NO-JIRA: Bump prometheus-operator to v0.79.1
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, jira/valid-reference

#2537 OCPBUGS-46066: Add new metrics for OpenShift logging telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2540 MGMT-19498:Fixing the configmap data fields
  assets/node-exporter/accelerators-collector-configmap.yaml
  jsonnet/components/node-exporter.libsonnet
Labels: lgtm, approved, jira/valid-reference

#2542 NO-JIRA: Bump prometheus-operator to 0.79.2
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, jira/valid-reference

#2543 NO-JIRA: fix TestPrometheusRemoteWrite to align the image used for th…
  test/e2e/framework/prometheus.go
  test/e2e/prometheus_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
