Repository openshift/cluster-monitoring-operator, pull requests merged in 2024-03, with the labels that each got.

#2271 MON-3706: Revert "chore: poll immediately in the e2e tests"
  test/e2e/alertmanager_test.go
  test/e2e/alertmanager_user_workload_test.go
  test/e2e/framework/assertions.go
  test/e2e/framework/framework.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, jira/valid-reference

#2267 OCPBUGS-28246: fix Thanos ruler alert generator url
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/thanos_ruler_user_workload.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#2260 MON-3381: replace OAuth proxy for Alertmanager
  assets/alertmanager/alertmanager.yaml
  assets/alertmanager/kube-rbac-proxy-web-secret.yaml
  assets/alertmanager/proxy-secret.yaml
  assets/alertmanager/service-account.yaml
  assets/cluster-monitoring-operator/monitoring-alertmanager-edit-role.yaml
  jsonnet/components/alertmanager.libsonnet
  jsonnet/components/cluster-monitoring-operator.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-namespaced-cluster-role.yaml
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/tasks/alertmanager.go
  test/e2e/alertmanager_test.go
Labels: lgtm, approved, jira/valid-reference

#2279 MON-3380: adjust prometheus-k8s service openshift.io/description
  Documentation/resources.adoc
  Documentation/resources.md
  assets/prometheus-k8s/service.yaml
  jsonnet/components/prometheus.libsonnet
Labels: lgtm, approved, jira/valid-reference

#2280 MON-3748: Enable audit logs by default for metrics-server
  Documentation/api.md
  Documentation/openshiftdocs/modules/metricsserverconfig.adoc
  assets/metrics-server/configmap-audit-profiles.yaml
  assets/metrics-server/deployment.yaml
  jsonnet/components/metrics-server-audit.libsonnet
  jsonnet/main.jsonnet
  pkg/manifests/config.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
  pkg/tasks/metricsserver.go
Labels: lgtm, approved, jira/valid-reference

#2243 MON-3694: chore: encourage the use of the new 'slices' package instead of 'golang.org/x/exp/slices'
  .golangci.yaml
  go.mod
  pkg/client/client.go
  pkg/manifests/config.go
  pkg/manifests/manifests.go
Labels: lgtm, approved, docs-approved, jira/valid-reference, acknowledge-critical-fixes-only

#2257 OCPNODE-2100: jsonnet: update crio port to TLS port 9637
  assets/control-plane/minimal-service-monitor-kubelet.yaml
  assets/control-plane/service-monitor-kubelet.yaml
  jsonnet/components/control-plane.libsonnet
Labels: lgtm, approved, jira/valid-reference

#2269 OCPBUGS-30257: Making sure proxy settings are correctly forwarded in the generated remote write configs
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2196 MON-3498: Modify prometheus-adapter e2e tests to compact with metrics server
  test/e2e/framework/helpers.go
  test/e2e/metrics_adapter_test.go
Labels: lgtm, approved, jira/valid-reference

#2288 MON-3771: update Prometheus operator to v0.72.0
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only
