Repository openshift/cluster-monitoring-operator, pull requests merged in 2024-06, with the labels that each got.

#2367 MON-3884: Send metric acm_managed_cluster_worker_cores via Telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2277 OBSDOCS-883: change docs to correct retention time uwm prometheus
  Documentation/api.md
  Documentation/openshiftdocs/modules/prometheusrestrictedconfig.adoc
  pkg/manifests/types.go
Labels: lgtm, approved, docs-approved, jira/valid-reference

#2297 SDN-3817,MON-3795:Expose OVNKubernetes:AdminNetworkPolicy Metrics via telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, px-approved, qe-approved, jira/valid-reference

#2380 MON-3894: revert(monitoring-plugin): undo nginx caching tweaks as the issue was…
  assets/monitoring-plugin/config-map.yaml
  jsonnet/components/monitoring-plugin.libsonnet
Labels: lgtm, approved, jira/valid-reference

#2379 [release-4.16] OCPBUGS-35061,MON-3795:Backport anp telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2351 OCPBUGS-32696: opt-out of multi-cluster Prometheus dashboard
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2390 MON-3914: adjust Prometheus GOGC based on infra topology
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, jira/valid-reference

#2381 OCPBUGS-35480: Add deprecation for prometheus adapter
  Documentation/api.md
  Documentation/openshiftdocs/modules/k8sprometheusadapter.adoc
  Documentation/openshiftdocs/modules/metricsserverconfig.adoc
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests.go
  pkg/manifests/types.go
  test/e2e/config_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2392 MON-3800: jsonnet: update prometheus dep to fetch the PrometheusKuber…
  assets/prometheus-k8s/prometheus-rule.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2373 [release-4.16] OCPBUGS-34530: inject trusted CA bundle into UWM Alertmanager
  assets/alertmanager-user-workload/alertmanager.yaml
  jsonnet/components/alertmanager-user-workload.libsonnet
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2384 OCPBUGS-34596: Ipsec state backport
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#2398 OCPBUGS-36299: Revert #2392 "MON-3800: jsonnet: update prometheus dep to fetch the PrometheusKuber…"
  assets/prometheus-k8s/prometheus-rule.yaml
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, px-approved, docs-approved, qe-approved, jira/valid-bug, jira/valid-reference
