Repository openshift/cluster-monitoring-operator, pull requests merged in 2025-09, with the labels that each got.

#2651 MON-4343: Cleanup deprecate pa config
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  test/e2e/config_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2653 OCPBUGS-60948: Add selinux_warning_controller_selinux_volume_conflict to telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2658 OCPBUGS-61135: Revert "MON-4343: Cleanup deprecate pa config"
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  test/e2e/config_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only, verified

#2637 MON-4371: chore(prometheus): enable use-uncached-io feature flag
  assets/prometheus-k8s/prometheus.yaml
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/components/prometheus-user-workload.libsonnet
  jsonnet/components/prometheus.libsonnet
  test/e2e/config_test.go
Labels: lgtm, approved, jira/valid-reference, verified

#2638 OCPBUGS-60161: Add mcd_local_unsupported_packages metric from MCO to telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, verified

#2649 NO-JIRA: chore: bump jsonnet dependencies
  assets/control-plane/minimal-service-monitor-kubelet.yaml
  assets/control-plane/prometheus-rule.yaml
  assets/control-plane/service-monitor-kubelet.yaml
  assets/node-exporter/daemonset.yaml
  assets/node-exporter/prometheus-rule.yaml
  hack/build-jsonnet.sh
  jsonnet/components/dashboards.libsonnet
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/utils/sanitize-rules.libsonnet
  manifests/0000_90_cluster-monitoring-operator_01-dashboards.yaml
Labels: lgtm, approved, jira/valid-reference, verified

#2671 OCPBUGS-15430: remove Kubernetes API alerting rules
  assets/control-plane/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-low, jira/valid-reference, verified
