Repository openshift/cluster-monitoring-operator, pull requests merged in 2025-02, with the labels that each got.

#2536 MON-3866: create separate metrics client cert for metrics server
  assets/cluster-monitoring-operator/metrics-server-client-certs.yaml
  assets/metrics-server/deployment.yaml
  jsonnet/components/cluster-monitoring-operator.libsonnet
  jsonnet/components/metrics-server.libsonnet
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/tls.go
  pkg/operator/operator.go
  pkg/tasks/metricsserver.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2565 NO-JIRA: Bump prometheus-operator to v0.80.0
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2569 OCPBUGS-50703: Add incidents metric to telemetry
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#2568 OCPBUGS-50837: Fix opentelemetry metrics to use regexp on label match
  Documentation/data-collection.md
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only

#2567 MON-4147: test: remove unnecessary UWM configuration in TestUserWorkloadMonitoringXXX
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#2572 NO-JIRA: Bump prometheus-operator to 0.80.1
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, jira/valid-reference
