Repository openshift/cluster-monitoring-operator, pull requests merged in 2025-05, with the labels that each got.

#2549 MON-4200: disable --auto-gomemlimit for Prometheus on SNO until we can ensure it won't result in excessive CPU usage
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, jira/valid-reference, acknowledge-critical-fixes-only

#2598 OCPBUGS-33691: mixin: longer rate interval for Alertmanager[Cluster]FailedToSendAlerts
  assets/alertmanager/prometheus-rule.yaml
  jsonnet/utils/sanitize-rules.libsonnet
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2599 MON-4242: chore(metrics-server): allow setting log verbosity
  Documentation/api.md
  Documentation/openshiftdocs/modules/metricsserverconfig.adoc
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/manifests/types.go
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2602 NO-JIRA: metrics-client-ca: set owner annotation
  assets/cluster-monitoring-operator/metrics-client-ca.yaml
  jsonnet/components/cluster-monitoring-operator.libsonnet
Labels: lgtm, approved, jira/valid-reference
