Repository openshift/cluster-monitoring-operator, pull requests merged in 2025-07, with the labels that each got.

#2612 OCPBUGS-58427: pkg/manifests: don't reset annotations for metrics client CA
  pkg/manifests/tls.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#2595 MON-4282: Multi-tenant support for KSM's CRS
  CHANGELOG.md
  assets/kube-state-metrics/cluster-role.yaml
  assets/kube-state-metrics/deployment.yaml
  jsonnet/components/kube-state-metrics.libsonnet
  manifests/0000_50_cluster-monitoring-operator_02-role.yaml
  pkg/client/client.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  pkg/tasks/kubestatemetrics.go
Labels: lgtm, approved, jira/valid-reference

#2614 MON-4255: Bump prometheus-operator to v0.83
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, jira/valid-reference

#2618 OCPBUGS-58475: Enforce secure TLS settings in CMO
  pkg/manifests/amcfg.go
  pkg/manifests/manifests.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-low, jira/valid-reference
