Repository openshift/cluster-monitoring-operator, pull requests merged in 2025-03, with the labels that each got.

#2574 NO-JIRA: chore: versions: kubeRbacProxy's primary branch isn't main yet
  hack/go/generate_versions.go
Labels: lgtm, approved, jira/valid-reference

#2545 MON-3960: test: enable back TestTLSSecurityProfileConfiguration and m…
  pkg/manifests/manifests_test.go
  test/e2e/tls_security_profile_test.go
Labels: lgtm, approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#2576 OCPBUGS-52565: Bump prometheus-operator to 0.78.2
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2554 MON-4136: set up the PrometheusPossibleNarrowSelectors alert
  assets/cluster-monitoring-operator/prometheus-rule.yaml
  jsonnet/rules.libsonnet
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2558 MON-4189:Updating node-exporter accelerators configmap
  assets/node-exporter/accelerators-collector-configmap.yaml
  jsonnet/components/node-exporter.libsonnet
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2582 MON-4188: Add docs for proxy_url alertmanager
  Documentation/api.md
  Documentation/openshiftdocs/modules/thanosrulerconfig.adoc
  pkg/manifests/types.go
Labels: lgtm, approved, docs-approved, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#2583 OCPBUGS-54223: Fix opentelemetry processor/receiver/exporter/extensions labels
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
