Repository openshift/cluster-monitoring-operator, pull requests merged in 2025-04, with the labels that each got.

#2584 OCPBUGS-54516: provide context-rich and case-sensitive config validation
  go.mod
  pkg/configvalidate/configvalidate_test.go
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, qe-approved, jira/valid-bug, jira/valid-reference

#2590 MON-4126: set fallbackScrapeProtocol: 'PrometheusText1.0.0' as default for all UWM Prometheus targets for backward compatibility with Prometheus v2 until a better migration process is available
  assets/prometheus-user-workload/prometheus.yaml
  jsonnet/components/prometheus-user-workload.libsonnet
  pkg/manifests/manifests_test.go
Labels: lgtm, approved, jira/valid-reference

#2588 MON-4161: add topology telemetry signals
  Documentation/data-collection.md
  Documentation/sample-metrics.md
  Documentation/telemetry/telemeter_query
  manifests/0000_50_cluster-monitoring-operator_04-config.yaml
Labels: lgtm, approved, qe-approved, jira/valid-reference

#2593 MON-4207: Bump prometheus-operator to v0.81.0
  Documentation/api.md
  go.mod
  go.sum
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-config-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0alertmanager-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0podmonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0probe-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheus-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0prometheusrule-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0servicemonitor-custom-resource-definition.yaml
  manifests/0000_50_cluster-monitoring-operator_00_0thanosruler-custom-resource-definition.yaml
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/alertmanager_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/prometheus_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1/alertmanagerspec.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1/clustertlsconfig.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1/commonprometheusfields.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1/prometheusspec.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1/remotewritespec.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1/shardretentionpolicy.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1/thanosrulerspec.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1alpha1/openstacksdconfig.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/monitoring/v1alpha1/prometheusagentspec.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/applyconfiguration/utils.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2592 OCPBUGS-55005: chore: introduce context-rich anb case sensitive unmarshaller for the monitoring and set CMO to Upgradeable=false if errors are found
  go.mod
  pkg/configvalidate/configvalidate.go
  pkg/manifests/config.go
  pkg/manifests/config_test.go
  pkg/manifests/manifests_test.go
  pkg/operator/operator.go
  test/e2e/config_test.go
  test/e2e/user_workload_monitoring_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference
